<Project>
  <PropertyGroup>
    <DepotVersionMajor>0</DepotVersionMajor>
    <DepotVersionMinor>15</DepotVersionMinor>
    <DepotVersionPatch>32</DepotVersionPatch>
    <DepotVersionPrerelease>preview</DepotVersionPrerelease>
    <DepotVersionPrefix>$(DepotVersionMajor).$(DepotVersionMinor).$(DepotVersionPatch)</DepotVersionPrefix>
    <DepotVersionSuffix Condition="'$(DepotVersionPrerelease)' != ''">-$(DepotVersionPrerelease)</DepotVersionSuffix>
    <DepotVersion>$(DepotVersionPrefix)$(DepotVersionSuffix)</DepotVersion>
    <Version>$(DepotVersion)</Version>
    <VersionPrefix>$(DepotVersionPrefix)</VersionPrefix>
    <VersionSuffix Condition="'$(DepotVersionPrerelease)' != ''">$(DepotVersionPrerelease)</VersionSuffix>
    <AssemblyVersion>$(DepotVersionMajor).$(DepotVersionMinor).0.0</AssemblyVersion>
    <FileVersion>$(DepotVersionPrefix).0</FileVersion>
    <InformationalVersion>$(DepotVersion)</InformationalVersion>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
