// Copyright (c) 2026 David Beusing
// Licensed under the MIT License.

using System;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Controls;

namespace Depot.Controls;

/// <summary>
/// Applies Depot's shared checkbox styles to framework-generated DataGridCheckBoxColumn elements.
/// Native DataGridCheckBoxColumn behavior is retained; only presentation styles are supplied.
/// </summary>
internal static class DataGridCheckBoxStyleBootstrapper
{
    private const string ElementStyleKey = "AppDataGridCheckBoxElementStyle";
    private const string EditingElementStyleKey = "AppDataGridCheckBoxEditingElementStyle";

    [ModuleInitializer]
    internal static void Initialize()
    {
        EventManager.RegisterClassHandler(
            typeof(DataGrid),
            FrameworkElement.LoadedEvent,
            new RoutedEventHandler(OnDataGridLoaded));

        EventManager.RegisterClassHandler(
            typeof(DataGrid),
            FrameworkElement.UnloadedEvent,
            new RoutedEventHandler(OnDataGridUnloaded));
    }

    private static void OnDataGridLoaded(object sender, RoutedEventArgs e)
    {
        if (sender is not DataGrid dataGrid)
        {
            return;
        }

        dataGrid.AutoGeneratedColumns -= OnAutoGeneratedColumns;
        dataGrid.AutoGeneratedColumns += OnAutoGeneratedColumns;
        ApplyStyles(dataGrid);
    }

    private static void OnDataGridUnloaded(object sender, RoutedEventArgs e)
    {
        if (sender is DataGrid dataGrid)
        {
            dataGrid.AutoGeneratedColumns -= OnAutoGeneratedColumns;
        }
    }

    private static void OnAutoGeneratedColumns(object? sender, EventArgs e)
    {
        if (sender is DataGrid dataGrid)
        {
            ApplyStyles(dataGrid);
        }
    }

    private static void ApplyStyles(DataGrid dataGrid)
    {
        if (dataGrid.TryFindResource(ElementStyleKey) is not Style elementStyle
            || dataGrid.TryFindResource(EditingElementStyleKey) is not Style editingElementStyle)
        {
            return;
        }

        foreach (DataGridColumn column in dataGrid.Columns)
        {
            if (column is not DataGridCheckBoxColumn checkBoxColumn)
            {
                continue;
            }

            if (checkBoxColumn.ReadLocalValue(DataGridBoundColumn.ElementStyleProperty) == DependencyProperty.UnsetValue)
            {
                checkBoxColumn.ElementStyle = elementStyle;
            }

            if (checkBoxColumn.ReadLocalValue(DataGridBoundColumn.EditingElementStyleProperty) == DependencyProperty.UnsetValue)
            {
                checkBoxColumn.EditingElementStyle = editingElementStyle;
            }
        }
    }
}
