// Copyright (c) 2026 David Beusing
// Licensed under the MIT License.

using System.Data.Common;
using System.Globalization;
using Depot.Data;
using Depot.Models;

namespace Depot.Repositories;

public sealed class FinanceInventoryCostingRepository : DatabaseRepository
{
	public FinanceInventoryCostingRepository(DatabaseAccess database) : base(database) { }

	public Task<FinanceInventoryAccountingPolicy?> GetPolicyAsync(CancellationToken cancellationToken = default) =>
		Database.QuerySingleOrDefaultAsync("SELECT Id,Version,InventoryControlAccountId,InventoryAdjustmentPostingProfileId,PurchaseVariancePostingProfileId,LandedCostPostingProfileId,IsActive FROM FinanceInventoryAccountingPolicies ORDER BY Id;", ReadPolicy, cancellationToken);

	public Task<IReadOnlyList<FinanceInventoryValuationSummary>> GetValuationSummaryAsync(CancellationToken cancellationToken = default) =>
		Database.QueryAsync("SELECT ItemId,CurrencyCode,SUM(RemainingQuantity),SUM(RemainingQuantity*UnitCost) FROM FinanceInventoryValuationLayers WHERE ReversedAtUtc IS NULL AND RemainingQuantity>0 GROUP BY ItemId,CurrencyCode ORDER BY ItemId,CurrencyCode;", r => new FinanceInventoryValuationSummary(r.GetInt64(0), Convert.ToInt32(r.GetValue(2),CultureInfo.InvariantCulture), new CurrencyCode(r.GetString(1)), Decimal(r,3)), cancellationToken);

	public Task<IReadOnlyList<FinanceInventoryReconciliationRun>> GetRecentReconciliationsAsync(int count = 20, CancellationToken cancellationToken = default) =>
		Database.QueryAsync($"SELECT Id,OperationId,AccountingBookId,InventoryControlAccountId,AsOfDate,ReportingCurrencyCode,ValuationAmount,GeneralLedgerAmount,Difference,CreatedAtUtc,CreatedByUserId FROM FinanceInventoryReconciliationRuns ORDER BY AsOfDate DESC,Id DESC LIMIT {Math.Clamp(count,1,100)};", ReadRun, cancellationToken);

	internal Task<FinanceInventoryAccountingPolicy?> GetPolicyAsync(DatabaseTransactionContext tx, CancellationToken token) => tx.Session.QuerySingleOrDefaultAsync("SELECT Id,Version,InventoryControlAccountId,InventoryAdjustmentPostingProfileId,PurchaseVariancePostingProfileId,LandedCostPostingProfileId,IsActive FROM FinanceInventoryAccountingPolicies ORDER BY Id;", ReadPolicy, token);
	internal Task<long> CreatePolicyAsync(DatabaseTransactionContext tx, FinanceInventoryAccountingPolicy value, CancellationToken token) => tx.Session.InsertAsync("INSERT INTO FinanceInventoryAccountingPolicies (Version,InventoryControlAccountId,InventoryAdjustmentPostingProfileId,PurchaseVariancePostingProfileId,LandedCostPostingProfileId,IsActive) VALUES (1,$Account,$Adjustment,$Variance,$Landed,$Active);", token, PolicyParameters(value));
	internal Task<int> UpdatePolicyAsync(DatabaseTransactionContext tx, FinanceInventoryAccountingPolicy value, long version, CancellationToken token) => tx.Session.ExecuteAsync("UPDATE FinanceInventoryAccountingPolicies SET Version=Version+1,InventoryControlAccountId=$Account,InventoryAdjustmentPostingProfileId=$Adjustment,PurchaseVariancePostingProfileId=$Variance,LandedCostPostingProfileId=$Landed,IsActive=$Active WHERE Id=$Id AND Version=$Version;", token, PolicyParameters(value).Append(Parameter("$Id",value.Id)).Append(Parameter("$Version",version)).ToArray());

	internal async Task<IReadOnlyList<FinanceInventoryValuationLayer>> LockLayersAsync(DatabaseTransactionContext tx, IReadOnlyList<long> ids, CancellationToken token)
	{
		if (ids.Count == 0) return [];
		var result = new List<FinanceInventoryValuationLayer>(ids.Count);
		foreach (var id in ids.Distinct().OrderBy(x=>x))
		{
			await tx.Session.ExecuteAsync("UPDATE FinanceInventoryValuationLayers SET RemainingQuantity=RemainingQuantity WHERE Id=$Id;",token,Parameter("$Id",id));
			var layer = await tx.Session.QuerySingleOrDefaultAsync("SELECT Id,AccountingBookId,ItemId,SourceMovementId,AcquiredDate,CurrencyCode,OriginalQuantity,RemainingQuantity,UnitCost,CreatedAtUtc,CreatedByUserId,ReversedAtUtc,ReversedByUserId FROM FinanceInventoryValuationLayers WHERE Id=$Id;",ReadLayer,token,Parameter("$Id",id));
			if (layer is null) throw new InvalidOperationException($"Inventory valuation layer '{id}' was not found.");
			result.Add(layer);
		}
		return result;
	}

	internal Task<int> UpdateLayerUnitCostAsync(DatabaseTransactionContext tx,long layerId,decimal oldCost,decimal newCost,CancellationToken token) => tx.Session.ExecuteAsync("UPDATE FinanceInventoryValuationLayers SET UnitCost=$NewCost WHERE Id=$Id AND UnitCost=$OldCost AND ReversedAtUtc IS NULL;",token,Parameter("$NewCost",newCost),Parameter("$Id",layerId),Parameter("$OldCost",oldCost));

	internal Task<FinanceInventoryLandedCostOperation?> FindLandedCostByOperationAsync(DatabaseTransactionContext tx,Guid operationId,CancellationToken token) => tx.Session.QuerySingleOrDefaultAsync("SELECT Id,OperationId,RequestHash,PostingDate,CurrencyCode,Amount,AllocationMethod,Reference,JournalEntryId,CreatedAtUtc,CreatedByUserId,ReversalOperationId,ReversalJournalEntryId,ReversedAtUtc,ReversedByUserId FROM FinanceInventoryLandedCostOperations WHERE OperationId=$OperationId;",ReadLandedCost,token,Parameter("$OperationId",operationId.ToString("D")));
	internal Task<FinanceInventoryLandedCostOperation?> GetLandedCostAsync(DatabaseTransactionContext tx,long id,CancellationToken token) => tx.Session.QuerySingleOrDefaultAsync("SELECT Id,OperationId,RequestHash,PostingDate,CurrencyCode,Amount,AllocationMethod,Reference,JournalEntryId,CreatedAtUtc,CreatedByUserId,ReversalOperationId,ReversalJournalEntryId,ReversedAtUtc,ReversedByUserId FROM FinanceInventoryLandedCostOperations WHERE Id=$Id;",ReadLandedCost,token,Parameter("$Id",id));
	internal Task<long> CreateLandedCostAsync(DatabaseTransactionContext tx,FinanceInventoryLandedCostOperation value,CancellationToken token) => tx.Session.InsertAsync("INSERT INTO FinanceInventoryLandedCostOperations (OperationId,RequestHash,PostingDate,CurrencyCode,Amount,AllocationMethod,Reference,JournalEntryId,CreatedAtUtc,CreatedByUserId) VALUES ($OperationId,$Hash,$Date,$Currency,$Amount,$Method,$Reference,$Journal,$At,$User);",token,Parameter("$OperationId",value.OperationId.ToString("D")),Parameter("$Hash",value.RequestHash),Parameter("$Date",value.PostingDate.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture)),Parameter("$Currency",value.Currency.Value),Parameter("$Amount",value.Amount),Parameter("$Method",(int)value.AllocationMethod),Parameter("$Reference",value.Reference),Parameter("$Journal",value.JournalEntryId),Parameter("$At",value.CreatedAtUtc.ToString("O",CultureInfo.InvariantCulture)),Parameter("$User",value.CreatedByUserId));
	internal Task<int> CreateLandedCostAllocationAsync(DatabaseTransactionContext tx,FinanceInventoryLandedCostAllocation value,CancellationToken token) => tx.Session.ExecuteAsync("INSERT INTO FinanceInventoryLandedCostAllocations (LandedCostOperationId,LayerId,Amount,UnitCostIncrease) VALUES ($Operation,$Layer,$Amount,$Increase);",token,Parameter("$Operation",value.OperationId),Parameter("$Layer",value.LayerId),Parameter("$Amount",value.Amount),Parameter("$Increase",value.UnitCostIncrease));
	internal Task<IReadOnlyList<FinanceInventoryLandedCostAllocation>> GetLandedCostAllocationsAsync(DatabaseTransactionContext tx,long id,CancellationToken token) => tx.Session.QueryAsync("SELECT Id,LandedCostOperationId,LayerId,Amount,UnitCostIncrease FROM FinanceInventoryLandedCostAllocations WHERE LandedCostOperationId=$Id ORDER BY Id;",r=>new FinanceInventoryLandedCostAllocation { Id=r.GetInt64(0),OperationId=r.GetInt64(1),LayerId=r.GetInt64(2),Amount=Decimal(r,3),UnitCostIncrease=Decimal(r,4)},token,Parameter("$Id",id));
	internal Task<int> MarkLandedCostReversedAsync(DatabaseTransactionContext tx,long id,Guid operationId,long journalId,DateTime at,long user,CancellationToken token)=>tx.Session.ExecuteAsync("UPDATE FinanceInventoryLandedCostOperations SET ReversalOperationId=$Operation,ReversalJournalEntryId=$Journal,ReversedAtUtc=$At,ReversedByUserId=$User WHERE Id=$Id AND ReversedAtUtc IS NULL;",token,Parameter("$Operation",operationId.ToString("D")),Parameter("$Journal",journalId),Parameter("$At",at.ToString("O",CultureInfo.InvariantCulture)),Parameter("$User",user),Parameter("$Id",id));

	internal Task<FinanceInventoryPurchaseVariance?> GetPurchaseVarianceAsync(DatabaseTransactionContext tx,long documentId,CancellationToken token)=>tx.Session.QuerySingleOrDefaultAsync("SELECT Id,SupplierDocumentId,OperationId,CurrencyCode,ExpectedNetAmount,ActualNetAmount,SignedVarianceAmount,JournalEntryId,CreatedAtUtc,CreatedByUserId,ReversalOperationId,ReversalJournalEntryId,ReversedAtUtc,ReversedByUserId FROM FinanceInventoryPurchaseVariances WHERE SupplierDocumentId=$Id;",ReadVariance,token,Parameter("$Id",documentId));
	internal Task<long> CreatePurchaseVarianceAsync(DatabaseTransactionContext tx,FinanceInventoryPurchaseVariance value,CancellationToken token)=>tx.Session.InsertAsync("INSERT INTO FinanceInventoryPurchaseVariances (SupplierDocumentId,OperationId,CurrencyCode,ExpectedNetAmount,ActualNetAmount,SignedVarianceAmount,JournalEntryId,CreatedAtUtc,CreatedByUserId) VALUES ($Document,$Operation,$Currency,$Expected,$Actual,$Variance,$Journal,$At,$User);",token,Parameter("$Document",value.SupplierDocumentId),Parameter("$Operation",value.OperationId.ToString("D")),Parameter("$Currency",value.Currency.Value),Parameter("$Expected",value.ExpectedNetAmount),Parameter("$Actual",value.ActualNetAmount),Parameter("$Variance",value.SignedVarianceAmount),Parameter("$Journal",value.JournalEntryId),Parameter("$At",value.CreatedAtUtc.ToString("O",CultureInfo.InvariantCulture)),Parameter("$User",value.CreatedByUserId));
	internal Task<int> MarkPurchaseVarianceReversedAsync(DatabaseTransactionContext tx,long id,Guid operation,long journal,DateTime at,long user,CancellationToken token)=>tx.Session.ExecuteAsync("UPDATE FinanceInventoryPurchaseVariances SET ReversalOperationId=$Operation,ReversalJournalEntryId=$Journal,ReversedAtUtc=$At,ReversedByUserId=$User WHERE Id=$Id AND ReversedAtUtc IS NULL;",token,Parameter("$Operation",operation.ToString("D")),Parameter("$Journal",journal),Parameter("$At",at.ToString("O",CultureInfo.InvariantCulture)),Parameter("$User",user),Parameter("$Id",id));

	internal Task<IReadOnlyList<FinanceInventoryValuationReportingRow>> GetValuationReportingRowsAsync(DatabaseTransactionContext tx,Guid bookId,DateOnly asOfDate,CancellationToken token)=>tx.Session.QueryAsync("SELECT l.Id,l.ItemId,l.RemainingQuantity,l.UnitCost,l.CurrencyCode,e.JournalEntryId,j.ExchangeRate FROM FinanceInventoryValuationLayers l INNER JOIN FinanceInventoryAccountingEvents e ON e.MovementId=l.SourceMovementId INNER JOIN FinanceJournalEntries j ON j.Id=e.JournalEntryId WHERE l.AccountingBookId=$Book AND l.AcquiredDate<=$Date AND l.ReversedAtUtc IS NULL AND l.RemainingQuantity>0 ORDER BY l.ItemId,l.Id;",r=>new FinanceInventoryValuationReportingRow(r.GetInt64(0),r.GetInt64(1),Convert.ToInt32(r.GetValue(2),CultureInfo.InvariantCulture),Decimal(r,3),new CurrencyCode(r.GetString(4)),Decimal(r,6)),token,Parameter("$Book",bookId.ToString("D")),Parameter("$Date",asOfDate.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture)));
	internal Task<IReadOnlyList<FinanceInventoryLandedReportingRow>> GetLandedReportingRowsAsync(DatabaseTransactionContext tx,Guid bookId,DateOnly asOfDate,CancellationToken token)=>tx.Session.QueryAsync("SELECT a.LayerId,a.UnitCostIncrease,j.ExchangeRate FROM FinanceInventoryLandedCostAllocations a INNER JOIN FinanceInventoryLandedCostOperations o ON o.Id=a.LandedCostOperationId INNER JOIN FinanceJournalEntries j ON j.Id=o.JournalEntryId INNER JOIN FinanceInventoryValuationLayers l ON l.Id=a.LayerId WHERE l.AccountingBookId=$Book AND o.PostingDate<=$Date AND o.ReversedAtUtc IS NULL;",r=>new FinanceInventoryLandedReportingRow(r.GetInt64(0),Decimal(r,1),Decimal(r,2)),token,Parameter("$Book",bookId.ToString("D")),Parameter("$Date",asOfDate.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture)));
	internal async Task<decimal> GetGlBalanceAsync(DatabaseTransactionContext tx,Guid bookId,Guid accountId,DateOnly date,CancellationToken token)
	{
		var value=await tx.Session.ExecuteScalarAsync("SELECT COALESCE(SUM(l.ReportingDebit-l.ReportingCredit),0) FROM FinanceJournalEntryLines l INNER JOIN FinanceJournalEntries e ON e.Id=l.JournalEntryId WHERE e.AccountingBookId=$Book AND l.AccountId=$Account AND e.PostingDate<=$Date;",token,Parameter("$Book",bookId.ToString("D")),Parameter("$Account",accountId.ToString("D")),Parameter("$Date",date.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture)));
		return Convert.ToDecimal(value??0m,CultureInfo.InvariantCulture);
	}
	internal async Task<CurrencyCode> GetBookReportingCurrencyAsync(DatabaseTransactionContext tx,Guid bookId,CancellationToken token)
	{
		var value=await tx.Session.ExecuteScalarAsync("SELECT ReportingCurrencyCode FROM FinanceAccountingBooks WHERE Id=$Id AND IsActive=1;",token,Parameter("$Id",bookId.ToString("D"))) ?? throw new InvalidOperationException("Accounting book was not found or inactive.");
		return new CurrencyCode(Convert.ToString(value,CultureInfo.InvariantCulture)!);
	}
	internal async Task<bool> AccountBelongsToBookAsync(DatabaseTransactionContext tx,Guid bookId,Guid accountId,CancellationToken token)
	{
		var value=await tx.Session.ExecuteScalarAsync("SELECT COUNT(*) FROM FinanceAccounts a INNER JOIN FinanceAccountingBooks b ON b.ChartOfAccountsId=a.ChartOfAccountsId WHERE b.Id=$Book AND a.Id=$Account AND a.IsActive=1;",token,Parameter("$Book",bookId.ToString("D")),Parameter("$Account",accountId.ToString("D")));
		return Convert.ToInt64(value??0,CultureInfo.InvariantCulture)==1;
	}
	internal Task<FinanceInventoryReconciliationRun?> FindRunAsync(DatabaseTransactionContext tx,Guid operation,CancellationToken token)=>tx.Session.QuerySingleOrDefaultAsync("SELECT Id,OperationId,AccountingBookId,InventoryControlAccountId,AsOfDate,ReportingCurrencyCode,ValuationAmount,GeneralLedgerAmount,Difference,CreatedAtUtc,CreatedByUserId FROM FinanceInventoryReconciliationRuns WHERE OperationId=$Operation;",ReadRun,token,Parameter("$Operation",operation.ToString("D")));
	internal Task<long> CreateRunAsync(DatabaseTransactionContext tx,FinanceInventoryReconciliationRun value,CancellationToken token)=>tx.Session.InsertAsync("INSERT INTO FinanceInventoryReconciliationRuns (OperationId,AccountingBookId,InventoryControlAccountId,AsOfDate,ReportingCurrencyCode,ValuationAmount,GeneralLedgerAmount,Difference,CreatedAtUtc,CreatedByUserId) VALUES ($Operation,$Book,$Account,$Date,$Currency,$Valuation,$Gl,$Difference,$At,$User);",token,Parameter("$Operation",value.OperationId.ToString("D")),Parameter("$Book",value.AccountingBookId.ToString("D")),Parameter("$Account",value.InventoryControlAccountId.ToString("D")),Parameter("$Date",value.AsOfDate.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture)),Parameter("$Currency",value.ReportingCurrency.Value),Parameter("$Valuation",value.ValuationAmount),Parameter("$Gl",value.GeneralLedgerAmount),Parameter("$Difference",value.Difference),Parameter("$At",value.CreatedAtUtc.ToString("O",CultureInfo.InvariantCulture)),Parameter("$User",value.CreatedByUserId));
	internal Task<int> CreateRunLineAsync(DatabaseTransactionContext tx,long runId,FinanceInventoryReconciliationLine line,CancellationToken token)=>tx.Session.ExecuteAsync("INSERT INTO FinanceInventoryReconciliationLines (RunId,ItemId,Quantity,ReportingValue) VALUES ($Run,$Item,$Quantity,$Value);",token,Parameter("$Run",runId),Parameter("$Item",line.ItemId),Parameter("$Quantity",line.Quantity),Parameter("$Value",line.ReportingValue));

	private static DatabaseParameter[] PolicyParameters(FinanceInventoryAccountingPolicy v)=>[Parameter("$Account",v.InventoryControlAccountId.ToString("D")),Parameter("$Adjustment",v.InventoryAdjustmentPostingProfileId),Parameter("$Variance",v.PurchaseVariancePostingProfileId),Parameter("$Landed",v.LandedCostPostingProfileId),Parameter("$Active",v.IsActive)];
	private static FinanceInventoryAccountingPolicy ReadPolicy(DbDataReader r)=>new(){Id=r.GetInt64(0),Version=r.GetInt64(1),InventoryControlAccountId=Guid.Parse(r.GetString(2)),InventoryAdjustmentPostingProfileId=r.GetInt64(3),PurchaseVariancePostingProfileId=r.GetInt64(4),LandedCostPostingProfileId=r.GetInt64(5),IsActive=Bool(r,6)};
	private static FinanceInventoryValuationLayer ReadLayer(DbDataReader r)=>new(){Id=r.GetInt64(0),AccountingBookId=Guid.Parse(r.GetString(1)),ItemId=r.GetInt64(2),SourceMovementId=r.GetInt64(3),AcquiredDate=DateOnly.FromDateTime(Convert.ToDateTime(r.GetValue(4),CultureInfo.InvariantCulture)),Currency=new CurrencyCode(r.GetString(5)),OriginalQuantity=Convert.ToInt32(r.GetValue(6),CultureInfo.InvariantCulture),RemainingQuantity=Convert.ToInt32(r.GetValue(7),CultureInfo.InvariantCulture),UnitCost=Decimal(r,8),CreatedAtUtc=Convert.ToDateTime(r.GetValue(9),CultureInfo.InvariantCulture),CreatedByUserId=r.IsDBNull(10)?null:r.GetInt64(10),ReversedAtUtc=r.IsDBNull(11)?null:Convert.ToDateTime(r.GetValue(11),CultureInfo.InvariantCulture),ReversedByUserId=r.IsDBNull(12)?null:r.GetInt64(12)};
	private static FinanceInventoryLandedCostOperation ReadLandedCost(DbDataReader r)=>new(){Id=r.GetInt64(0),OperationId=Guid.Parse(r.GetString(1)),RequestHash=r.GetString(2),PostingDate=DateOnly.FromDateTime(Convert.ToDateTime(r.GetValue(3),CultureInfo.InvariantCulture)),Currency=new CurrencyCode(r.GetString(4)),Amount=Decimal(r,5),AllocationMethod=(FinanceLandedCostAllocationMethod)Convert.ToInt32(r.GetValue(6),CultureInfo.InvariantCulture),Reference=r.IsDBNull(7)?null:r.GetString(7),JournalEntryId=r.GetInt64(8),CreatedAtUtc=Convert.ToDateTime(r.GetValue(9),CultureInfo.InvariantCulture),CreatedByUserId=r.GetInt64(10),ReversalOperationId=r.IsDBNull(11)?null:Guid.Parse(r.GetString(11)),ReversalJournalEntryId=r.IsDBNull(12)?null:r.GetInt64(12),ReversedAtUtc=r.IsDBNull(13)?null:Convert.ToDateTime(r.GetValue(13),CultureInfo.InvariantCulture),ReversedByUserId=r.IsDBNull(14)?null:r.GetInt64(14)};
	private static FinanceInventoryPurchaseVariance ReadVariance(DbDataReader r)=>new(){Id=r.GetInt64(0),SupplierDocumentId=r.GetInt64(1),OperationId=Guid.Parse(r.GetString(2)),Currency=new CurrencyCode(r.GetString(3)),ExpectedNetAmount=Decimal(r,4),ActualNetAmount=Decimal(r,5),SignedVarianceAmount=Decimal(r,6),JournalEntryId=r.GetInt64(7),CreatedAtUtc=Convert.ToDateTime(r.GetValue(8),CultureInfo.InvariantCulture),CreatedByUserId=r.GetInt64(9),ReversalOperationId=r.IsDBNull(10)?null:Guid.Parse(r.GetString(10)),ReversalJournalEntryId=r.IsDBNull(11)?null:r.GetInt64(11),ReversedAtUtc=r.IsDBNull(12)?null:Convert.ToDateTime(r.GetValue(12),CultureInfo.InvariantCulture),ReversedByUserId=r.IsDBNull(13)?null:r.GetInt64(13)};
	private static FinanceInventoryReconciliationRun ReadRun(DbDataReader r)=>new(){Id=r.GetInt64(0),OperationId=Guid.Parse(r.GetString(1)),AccountingBookId=Guid.Parse(r.GetString(2)),InventoryControlAccountId=Guid.Parse(r.GetString(3)),AsOfDate=DateOnly.FromDateTime(Convert.ToDateTime(r.GetValue(4),CultureInfo.InvariantCulture)),ReportingCurrency=new CurrencyCode(r.GetString(5)),ValuationAmount=Decimal(r,6),GeneralLedgerAmount=Decimal(r,7),Difference=Decimal(r,8),CreatedAtUtc=Convert.ToDateTime(r.GetValue(9),CultureInfo.InvariantCulture),CreatedByUserId=r.GetInt64(10)};
	private static bool Bool(DbDataReader r,int i)=>Convert.ToBoolean(r.GetValue(i),CultureInfo.InvariantCulture);
	private static decimal Decimal(DbDataReader r,int i)=>Convert.ToDecimal(r.GetValue(i),CultureInfo.InvariantCulture);
}

internal sealed record FinanceInventoryValuationReportingRow(long LayerId,long ItemId,int Quantity,decimal CurrentUnitCost,CurrencyCode Currency,decimal ReceiptExchangeRate);
internal sealed record FinanceInventoryLandedReportingRow(long LayerId,decimal UnitCostIncrease,decimal ExchangeRate);
