// Copyright (c) 2026 David Beusing
// Licensed under the MIT License.

using System.Data.Common;
using System.Globalization;

using Depot.Data;
using Depot.Models;

namespace Depot.Repositories;

public sealed class FinanceAccountsReceivableRepository : DatabaseRepository
{
	private const string OpenItemColumns = "oi.Id,oi.Version,oi.LegalEntityId,oi.AccountingBookId,oi.CustomerId,c.Name,oi.Kind,oi.SourceType,oi.SourceId,oi.SourceReference,oi.DocumentDate,oi.DueDate,oi.CurrencyCode,oi.OriginalAmount,oi.RemainingAmount,oi.JournalEntryId,oi.OperationId,oi.IsVoided,oi.CreatedAtUtc,oi.CreatedByUserId";
	private const string PaymentColumns = "Id,Version,OperationId,RequestHash,CustomerId,CurrencyCode,PaymentDate,Amount,Reference,Description,OpenItemId,JournalEntryId,CreatedAtUtc,CreatedByUserId,IsReversed,ReversalOperationId,ReversalJournalEntryId,ReversedAtUtc,ReversedByUserId";
	private const string WriteOffColumns = "Id,Version,OperationId,RequestHash,OpenItemId,Amount,PostingDate,Reason,JournalEntryId,CreatedAtUtc,CreatedByUserId,IsReversed,ReversalOperationId,ReversalJournalEntryId,ReversedAtUtc,ReversedByUserId";

	public FinanceAccountsReceivableRepository(DatabaseAccess database) : base(database) { }

	public Task<FinanceReceivablesConfiguration?> GetConfigurationAsync(CancellationToken cancellationToken = default) =>
		Database.QuerySingleOrDefaultAsync("SELECT Id,Version,LegalEntityId,FiscalCalendarId,InvoicePostingProfileId,CreditNotePostingProfileId,PaymentPostingProfileId,WriteOffPostingProfileId,IsActive FROM FinanceReceivablesConfigurations ORDER BY Id;", ReadConfiguration, cancellationToken);

	public Task<PageResult<FinanceReceivableOpenItem>> SearchOpenItemsAsync(string? searchText, bool includeSettled, int pageNumber, int pageSize, CancellationToken cancellationToken)
	{
		var filters = new List<string> { "oi.IsVoided=0" };
		var parameters = new List<DatabaseParameter>();
		if (!includeSettled) filters.Add("oi.RemainingAmount>0");
		if (!string.IsNullOrWhiteSpace(searchText))
		{
			filters.Add("(c.Name LIKE $Search OR oi.SourceReference LIKE $Search OR oi.SourceId LIKE $Search)");
			parameters.Add(Parameter("$Search", $"%{searchText.Trim()}%"));
		}
		var from = "FROM FinanceReceivableOpenItems oi INNER JOIN Customers c ON c.Id=oi.CustomerId";
		var where = $"WHERE {string.Join(" AND ", filters)}";
		return Database.QueryPageAsync($"SELECT {OpenItemColumns} {from} {where} ORDER BY oi.DueDate,oi.Id", $"SELECT COUNT(*) {from} {where};", ReadOpenItem, pageNumber, pageSize, cancellationToken, parameters.ToArray());
	}

	public Task<FinanceReceivableOpenItem?> GetOpenItemAsync(long id, CancellationToken cancellationToken = default) =>
		Database.QuerySingleOrDefaultAsync($"SELECT {OpenItemColumns} FROM FinanceReceivableOpenItems oi INNER JOIN Customers c ON c.Id=oi.CustomerId WHERE oi.Id=$Id;", ReadOpenItem, cancellationToken, Parameter("$Id", id));

	public Task<FinanceReceivablePayment?> GetPaymentAsync(long id, CancellationToken cancellationToken = default) =>
		Database.QuerySingleOrDefaultAsync($"SELECT {PaymentColumns} FROM FinanceReceivablePayments WHERE Id=$Id;", ReadPayment, cancellationToken, Parameter("$Id", id));

	public Task<FinanceReceivableWriteOff?> GetWriteOffAsync(long id, CancellationToken cancellationToken = default) =>
		Database.QuerySingleOrDefaultAsync($"SELECT {WriteOffColumns} FROM FinanceReceivableWriteOffs WHERE Id=$Id;", ReadWriteOff, cancellationToken, Parameter("$Id", id));

	public Task<IReadOnlyList<FinanceReceivableAgingRow>> GetAgingRowsAsync(DateOnly asOfDate, CancellationToken cancellationToken = default) =>
		Database.QueryAsync(
			"SELECT oi.CustomerId,c.Name,oi.CurrencyCode,oi.DueDate,oi.RemainingAmount,oi.Kind FROM FinanceReceivableOpenItems oi INNER JOIN Customers c ON c.Id=oi.CustomerId WHERE oi.IsVoided=0 AND oi.RemainingAmount>0 AND oi.DocumentDate<=$AsOfDate ORDER BY c.Name,oi.CurrencyCode,oi.DueDate,oi.Id;",
			reader => new FinanceReceivableAgingRow(reader.GetInt64(0), reader.GetString(1), new CurrencyCode(reader.GetString(2)), ReadDateOnly(reader, 3), ReadDecimal(reader, 4), (FinanceReceivableOpenItemKind)Convert.ToInt32(reader.GetValue(5), CultureInfo.InvariantCulture)),
			cancellationToken,
			Parameter("$AsOfDate", asOfDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)));

	public Task<IReadOnlyList<FinanceCustomerStatementRow>> GetCustomerStatementAsync(long customerId, CurrencyCode currency, DateOnly fromDate, DateOnly toDate, CancellationToken cancellationToken = default) =>
		Database.QueryAsync(
			"SELECT DocumentDate,Kind,COALESCE(SourceReference,SourceId),SourceType,CurrencyCode,OriginalAmount,RemainingAmount FROM FinanceReceivableOpenItems WHERE CustomerId=$CustomerId AND CurrencyCode=$Currency AND DocumentDate>=$FromDate AND DocumentDate<=$ToDate AND IsVoided=0 ORDER BY DocumentDate,Id;",
			reader =>
			{
				var kind = (FinanceReceivableOpenItemKind)Convert.ToInt32(reader.GetValue(1), CultureInfo.InvariantCulture);
				var amount = ReadDecimal(reader, 5);
				return new FinanceCustomerStatementRow(ReadDateOnly(reader, 0), kind.ToString(), reader.GetString(2), reader.GetString(3), new CurrencyCode(reader.GetString(4)), kind == FinanceReceivableOpenItemKind.Invoice ? amount : 0m, kind == FinanceReceivableOpenItemKind.Invoice ? 0m : amount, ReadDecimal(reader, 6));
			},
			cancellationToken,
			Parameter("$CustomerId", customerId),
			Parameter("$Currency", currency.Value),
			Parameter("$FromDate", fromDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)),
			Parameter("$ToDate", toDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)));

	public async Task<IReadOnlyList<FinanceDunningPolicy>> GetDunningPoliciesAsync(CancellationToken cancellationToken = default)
	{
		var policies = await Database.QueryAsync("SELECT Id,Version,LegalEntityId,Code,Name,IsActive FROM FinanceDunningPolicies ORDER BY Code;", ReadPolicy, cancellationToken);
		var result = new List<FinanceDunningPolicy>(policies.Count);
		foreach (var policy in policies) result.Add(policy with { Levels = await LoadPolicyLevelsAsync(policy.Id, cancellationToken) });
		return result;
	}

	public async Task<FinanceDunningRun?> GetDunningRunAsync(long id, CancellationToken cancellationToken = default)
	{
		var run = await Database.QuerySingleOrDefaultAsync("SELECT Id,OperationId,RequestHash,PolicyId,AsOfDate,CreatedAtUtc,CreatedByUserId FROM FinanceDunningRuns WHERE Id=$Id;", ReadDunningRun, cancellationToken, Parameter("$Id", id));
		return run is null ? null : run with { Lines = await LoadRunLinesAsync(id, cancellationToken) };
	}

	internal Task<IReadOnlyList<FinanceReceivablesConfiguration>> GetActiveConfigurationsAsync(DatabaseTransactionContext transaction, CancellationToken cancellationToken) => transaction.Session.QueryAsync("SELECT Id,Version,LegalEntityId,FiscalCalendarId,InvoicePostingProfileId,CreditNotePostingProfileId,PaymentPostingProfileId,WriteOffPostingProfileId,IsActive FROM FinanceReceivablesConfigurations WHERE IsActive=1 ORDER BY Id;", ReadConfiguration, cancellationToken);
	internal Task<FinanceReceivablesConfiguration?> GetConfigurationAsync(DatabaseTransactionContext transaction, long id, CancellationToken cancellationToken) => transaction.Session.QuerySingleOrDefaultAsync("SELECT Id,Version,LegalEntityId,FiscalCalendarId,InvoicePostingProfileId,CreditNotePostingProfileId,PaymentPostingProfileId,WriteOffPostingProfileId,IsActive FROM FinanceReceivablesConfigurations WHERE Id=$Id;", ReadConfiguration, cancellationToken, Parameter("$Id", id));
	internal Task<long> CreateConfigurationAsync(DatabaseTransactionContext transaction, FinanceReceivablesConfiguration value, CancellationToken cancellationToken) => transaction.Session.InsertAsync("INSERT INTO FinanceReceivablesConfigurations (Version,LegalEntityId,FiscalCalendarId,InvoicePostingProfileId,CreditNotePostingProfileId,PaymentPostingProfileId,WriteOffPostingProfileId,IsActive) VALUES (1,$LegalEntityId,$FiscalCalendarId,$InvoiceProfile,$CreditProfile,$PaymentProfile,$WriteOffProfile,$IsActive);", cancellationToken, ConfigurationParameters(value));
	internal Task<int> UpdateConfigurationAsync(DatabaseTransactionContext transaction, FinanceReceivablesConfiguration value, long expectedVersion, CancellationToken cancellationToken) => transaction.Session.ExecuteAsync("UPDATE FinanceReceivablesConfigurations SET Version=Version+1,LegalEntityId=$LegalEntityId,FiscalCalendarId=$FiscalCalendarId,InvoicePostingProfileId=$InvoiceProfile,CreditNotePostingProfileId=$CreditProfile,PaymentPostingProfileId=$PaymentProfile,WriteOffPostingProfileId=$WriteOffProfile,IsActive=$IsActive WHERE Id=$Id AND Version=$ExpectedVersion;", cancellationToken, ConfigurationParameters(value).Append(Parameter("$Id", value.Id)).Append(Parameter("$ExpectedVersion", expectedVersion)).ToArray());
	internal Task<FinanceFiscalCalendarRecord?> GetFiscalCalendarAsync(DatabaseTransactionContext transaction, Guid id, CancellationToken cancellationToken) => transaction.Session.QuerySingleOrDefaultAsync("SELECT Id,LegalEntityId,IsActive FROM FinanceFiscalCalendars WHERE Id=$Id;", reader => new FinanceFiscalCalendarRecord(Guid.Parse(reader.GetString(0)), Guid.Parse(reader.GetString(1)), ReadBool(reader, 2)), cancellationToken, Parameter("$Id", id.ToString("D")));
	internal Task<IReadOnlyList<FinanceAccountingPeriodRecord>> FindOpenPeriodsAsync(DatabaseTransactionContext transaction, Guid fiscalCalendarId, DateOnly date, CancellationToken cancellationToken) => transaction.Session.QueryAsync("SELECT Id,StartDate,EndDate,Status FROM FinanceAccountingPeriods WHERE FiscalCalendarId=$CalendarId AND StartDate<=$Date AND EndDate>=$Date AND Status=0 ORDER BY StartDate,Id;", reader => new FinanceAccountingPeriodRecord(Guid.Parse(reader.GetString(0)), ReadDateOnly(reader, 1), ReadDateOnly(reader, 2), (AccountingPeriodStatus)Convert.ToInt32(reader.GetValue(3), CultureInfo.InvariantCulture)), cancellationToken, Parameter("$CalendarId", fiscalCalendarId.ToString("D")), Parameter("$Date", date.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)));
	internal Task<FinanceReceivableOpenItem?> FindOpenItemBySourceAsync(DatabaseTransactionContext transaction, string sourceType, string sourceId, CancellationToken cancellationToken) => transaction.Session.QuerySingleOrDefaultAsync($"SELECT {OpenItemColumns} FROM FinanceReceivableOpenItems oi INNER JOIN Customers c ON c.Id=oi.CustomerId WHERE oi.SourceType=$SourceType AND oi.SourceId=$SourceId;", ReadOpenItem, cancellationToken, Parameter("$SourceType", sourceType), Parameter("$SourceId", sourceId));

	internal async Task<FinanceReceivableOpenItem?> LockOpenItemAsync(DatabaseTransactionContext transaction, long id, CancellationToken cancellationToken)
	{
		await transaction.Session.ExecuteAsync("UPDATE FinanceReceivableOpenItems SET Version=Version WHERE Id=$Id;", cancellationToken, Parameter("$Id", id));
		return await transaction.Session.QuerySingleOrDefaultAsync($"SELECT {OpenItemColumns} FROM FinanceReceivableOpenItems oi INNER JOIN Customers c ON c.Id=oi.CustomerId WHERE oi.Id=$Id;", ReadOpenItem, cancellationToken, Parameter("$Id", id));
	}

	internal Task<long> CreateOpenItemAsync(DatabaseTransactionContext transaction, FinanceReceivableOpenItem value, CancellationToken cancellationToken) => transaction.Session.InsertAsync("INSERT INTO FinanceReceivableOpenItems (Version,LegalEntityId,AccountingBookId,CustomerId,Kind,SourceType,SourceId,SourceReference,DocumentDate,DueDate,CurrencyCode,OriginalAmount,RemainingAmount,JournalEntryId,OperationId,IsVoided,CreatedAtUtc,CreatedByUserId) VALUES (1,$LegalEntityId,$AccountingBookId,$CustomerId,$Kind,$SourceType,$SourceId,$SourceReference,$DocumentDate,$DueDate,$Currency,$OriginalAmount,$RemainingAmount,$JournalEntryId,$OperationId,$IsVoided,$CreatedAtUtc,$CreatedByUserId);", cancellationToken, Parameter("$LegalEntityId", value.LegalEntityId.ToString("D")), Parameter("$AccountingBookId", value.AccountingBookId.ToString("D")), Parameter("$CustomerId", value.CustomerId), Parameter("$Kind", (int)value.Kind), Parameter("$SourceType", value.SourceType), Parameter("$SourceId", value.SourceId), Parameter("$SourceReference", value.SourceReference), Parameter("$DocumentDate", value.DocumentDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)), Parameter("$DueDate", value.DueDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)), Parameter("$Currency", value.Currency.Value), Parameter("$OriginalAmount", value.OriginalAmount), Parameter("$RemainingAmount", value.RemainingAmount), Parameter("$JournalEntryId", value.JournalEntryId), Parameter("$OperationId", value.OperationId.ToString("D")), Parameter("$IsVoided", value.IsVoided), Parameter("$CreatedAtUtc", value.CreatedAtUtc.ToString("O", CultureInfo.InvariantCulture)), Parameter("$CreatedByUserId", value.CreatedByUserId));
	internal Task<int> UpdateOpenItemRemainingAsync(DatabaseTransactionContext transaction, long id, long expectedVersion, decimal remainingAmount, bool isVoided, CancellationToken cancellationToken) => transaction.Session.ExecuteAsync("UPDATE FinanceReceivableOpenItems SET RemainingAmount=$RemainingAmount,IsVoided=$IsVoided,Version=Version+1 WHERE Id=$Id AND Version=$ExpectedVersion;", cancellationToken, Parameter("$RemainingAmount", remainingAmount), Parameter("$IsVoided", isVoided), Parameter("$Id", id), Parameter("$ExpectedVersion", expectedVersion));
	internal Task<int> CreateAllocationAsync(DatabaseTransactionContext transaction, FinanceReceivableAllocation value, CancellationToken cancellationToken) => transaction.Session.ExecuteAsync("INSERT INTO FinanceReceivableAllocations (OperationId,DebitOpenItemId,CreditOpenItemId,Amount,AllocationDate,CreatedAtUtc,CreatedByUserId) VALUES ($OperationId,$DebitId,$CreditId,$Amount,$Date,$CreatedAtUtc,$CreatedByUserId);", cancellationToken, Parameter("$OperationId", value.OperationId.ToString("D")), Parameter("$DebitId", value.DebitOpenItemId), Parameter("$CreditId", value.CreditOpenItemId), Parameter("$Amount", value.Amount), Parameter("$Date", value.AllocationDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)), Parameter("$CreatedAtUtc", value.CreatedAtUtc.ToString("O", CultureInfo.InvariantCulture)), Parameter("$CreatedByUserId", value.CreatedByUserId));
	internal Task<IReadOnlyList<FinanceReceivableAllocation>> GetActiveAllocationsAsync(DatabaseTransactionContext transaction, Guid operationId, CancellationToken cancellationToken) => transaction.Session.QueryAsync("SELECT Id,OperationId,DebitOpenItemId,CreditOpenItemId,Amount,AllocationDate,CreatedAtUtc,CreatedByUserId,ReversedAtUtc,ReversedByUserId,ReversalOperationId FROM FinanceReceivableAllocations WHERE OperationId=$OperationId AND ReversedAtUtc IS NULL ORDER BY Id;", ReadAllocation, cancellationToken, Parameter("$OperationId", operationId.ToString("D")));
	internal Task<int> ReverseAllocationsAsync(DatabaseTransactionContext transaction, Guid operationId, Guid reversalOperationId, DateTime reversedAtUtc, long userId, CancellationToken cancellationToken) => transaction.Session.ExecuteAsync("UPDATE FinanceReceivableAllocations SET ReversedAtUtc=$At,ReversedByUserId=$UserId,ReversalOperationId=$ReversalOperationId WHERE OperationId=$OperationId AND ReversedAtUtc IS NULL;", cancellationToken, Parameter("$At", reversedAtUtc.ToString("O", CultureInfo.InvariantCulture)), Parameter("$UserId", userId), Parameter("$ReversalOperationId", reversalOperationId.ToString("D")), Parameter("$OperationId", operationId.ToString("D")));
	internal Task<FinanceReceivablePayment?> FindPaymentByOperationAsync(DatabaseTransactionContext transaction, Guid operationId, CancellationToken cancellationToken) => transaction.Session.QuerySingleOrDefaultAsync($"SELECT {PaymentColumns} FROM FinanceReceivablePayments WHERE OperationId=$OperationId;", ReadPayment, cancellationToken, Parameter("$OperationId", operationId.ToString("D")));
	internal async Task<FinanceReceivablePayment?> LockPaymentAsync(DatabaseTransactionContext transaction, long id, CancellationToken cancellationToken) { await transaction.Session.ExecuteAsync("UPDATE FinanceReceivablePayments SET Version=Version WHERE Id=$Id;", cancellationToken, Parameter("$Id", id)); return await transaction.Session.QuerySingleOrDefaultAsync($"SELECT {PaymentColumns} FROM FinanceReceivablePayments WHERE Id=$Id;", ReadPayment, cancellationToken, Parameter("$Id", id)); }
	internal Task<long> CreatePaymentAsync(DatabaseTransactionContext transaction, FinanceReceivablePayment value, CancellationToken cancellationToken) => transaction.Session.InsertAsync("INSERT INTO FinanceReceivablePayments (Version,OperationId,RequestHash,CustomerId,CurrencyCode,PaymentDate,Amount,Reference,Description,OpenItemId,JournalEntryId,CreatedAtUtc,CreatedByUserId,IsReversed) VALUES (1,$OperationId,$RequestHash,$CustomerId,$Currency,$PaymentDate,$Amount,$Reference,$Description,$OpenItemId,$JournalEntryId,$CreatedAtUtc,$CreatedByUserId,0);", cancellationToken, Parameter("$OperationId", value.OperationId.ToString("D")), Parameter("$RequestHash", value.RequestHash), Parameter("$CustomerId", value.CustomerId), Parameter("$Currency", value.Currency.Value), Parameter("$PaymentDate", value.PaymentDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)), Parameter("$Amount", value.Amount), Parameter("$Reference", value.Reference), Parameter("$Description", value.Description), Parameter("$OpenItemId", value.OpenItemId), Parameter("$JournalEntryId", value.JournalEntryId), Parameter("$CreatedAtUtc", value.CreatedAtUtc.ToString("O", CultureInfo.InvariantCulture)), Parameter("$CreatedByUserId", value.CreatedByUserId));
	internal Task<int> MarkPaymentReversedAsync(DatabaseTransactionContext transaction, FinanceReceivablePayment value, long expectedVersion, Guid reversalOperationId, long reversalJournalEntryId, DateTime reversedAtUtc, long userId, CancellationToken cancellationToken) => transaction.Session.ExecuteAsync("UPDATE FinanceReceivablePayments SET IsReversed=1,ReversalOperationId=$OperationId,ReversalJournalEntryId=$JournalEntryId,ReversedAtUtc=$At,ReversedByUserId=$UserId,Version=Version+1 WHERE Id=$Id AND Version=$ExpectedVersion AND IsReversed=0;", cancellationToken, Parameter("$OperationId", reversalOperationId.ToString("D")), Parameter("$JournalEntryId", reversalJournalEntryId), Parameter("$At", reversedAtUtc.ToString("O", CultureInfo.InvariantCulture)), Parameter("$UserId", userId), Parameter("$Id", value.Id), Parameter("$ExpectedVersion", expectedVersion));
	internal Task<FinanceReceivableWriteOff?> FindWriteOffByOperationAsync(DatabaseTransactionContext transaction, Guid operationId, CancellationToken cancellationToken) => transaction.Session.QuerySingleOrDefaultAsync($"SELECT {WriteOffColumns} FROM FinanceReceivableWriteOffs WHERE OperationId=$OperationId;", ReadWriteOff, cancellationToken, Parameter("$OperationId", operationId.ToString("D")));
	internal async Task<FinanceReceivableWriteOff?> LockWriteOffAsync(DatabaseTransactionContext transaction, long id, CancellationToken cancellationToken) { await transaction.Session.ExecuteAsync("UPDATE FinanceReceivableWriteOffs SET Version=Version WHERE Id=$Id;", cancellationToken, Parameter("$Id", id)); return await transaction.Session.QuerySingleOrDefaultAsync($"SELECT {WriteOffColumns} FROM FinanceReceivableWriteOffs WHERE Id=$Id;", ReadWriteOff, cancellationToken, Parameter("$Id", id)); }
	internal Task<long> CreateWriteOffAsync(DatabaseTransactionContext transaction, FinanceReceivableWriteOff value, CancellationToken cancellationToken) => transaction.Session.InsertAsync("INSERT INTO FinanceReceivableWriteOffs (Version,OperationId,RequestHash,OpenItemId,Amount,PostingDate,Reason,JournalEntryId,CreatedAtUtc,CreatedByUserId,IsReversed) VALUES (1,$OperationId,$RequestHash,$OpenItemId,$Amount,$PostingDate,$Reason,$JournalEntryId,$CreatedAtUtc,$CreatedByUserId,0);", cancellationToken, Parameter("$OperationId", value.OperationId.ToString("D")), Parameter("$RequestHash", value.RequestHash), Parameter("$OpenItemId", value.OpenItemId), Parameter("$Amount", value.Amount), Parameter("$PostingDate", value.PostingDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)), Parameter("$Reason", value.Reason), Parameter("$JournalEntryId", value.JournalEntryId), Parameter("$CreatedAtUtc", value.CreatedAtUtc.ToString("O", CultureInfo.InvariantCulture)), Parameter("$CreatedByUserId", value.CreatedByUserId));
	internal Task<int> MarkWriteOffReversedAsync(DatabaseTransactionContext transaction, FinanceReceivableWriteOff value, long expectedVersion, Guid reversalOperationId, long reversalJournalEntryId, DateTime reversedAtUtc, long userId, CancellationToken cancellationToken) => transaction.Session.ExecuteAsync("UPDATE FinanceReceivableWriteOffs SET IsReversed=1,ReversalOperationId=$OperationId,ReversalJournalEntryId=$JournalEntryId,ReversedAtUtc=$At,ReversedByUserId=$UserId,Version=Version+1 WHERE Id=$Id AND Version=$ExpectedVersion AND IsReversed=0;", cancellationToken, Parameter("$OperationId", reversalOperationId.ToString("D")), Parameter("$JournalEntryId", reversalJournalEntryId), Parameter("$At", reversedAtUtc.ToString("O", CultureInfo.InvariantCulture)), Parameter("$UserId", userId), Parameter("$Id", value.Id), Parameter("$ExpectedVersion", expectedVersion));

	internal async Task<FinanceDunningPolicy?> GetDunningPolicyAsync(DatabaseTransactionContext transaction, long id, CancellationToken cancellationToken) { var policy = await transaction.Session.QuerySingleOrDefaultAsync("SELECT Id,Version,LegalEntityId,Code,Name,IsActive FROM FinanceDunningPolicies WHERE Id=$Id;", ReadPolicy, cancellationToken, Parameter("$Id", id)); return policy is null ? null : policy with { Levels = await transaction.Session.QueryAsync("SELECT Id,PolicyId,LevelNumber,MinimumDaysOverdue,Code,Name FROM FinanceDunningPolicyLevels WHERE PolicyId=$Id ORDER BY LevelNumber;", ReadPolicyLevel, cancellationToken, Parameter("$Id", id)) }; }
	internal async Task<long> CreateDunningPolicyAsync(DatabaseTransactionContext transaction, FinanceDunningPolicy value, CancellationToken cancellationToken) { var id = await transaction.Session.InsertAsync("INSERT INTO FinanceDunningPolicies (Version,LegalEntityId,Code,Name,IsActive) VALUES (1,$LegalEntityId,$Code,$Name,$IsActive);", cancellationToken, Parameter("$LegalEntityId", value.LegalEntityId.ToString("D")), Parameter("$Code", value.Code), Parameter("$Name", value.Name), Parameter("$IsActive", value.IsActive)); await ReplaceDunningLevelsAsync(transaction, id, value.Levels, cancellationToken); return id; }
	internal async Task<int> UpdateDunningPolicyAsync(DatabaseTransactionContext transaction, FinanceDunningPolicy value, long expectedVersion, CancellationToken cancellationToken) { var changed = await transaction.Session.ExecuteAsync("UPDATE FinanceDunningPolicies SET Version=Version+1,LegalEntityId=$LegalEntityId,Code=$Code,Name=$Name,IsActive=$IsActive WHERE Id=$Id AND Version=$ExpectedVersion;", cancellationToken, Parameter("$LegalEntityId", value.LegalEntityId.ToString("D")), Parameter("$Code", value.Code), Parameter("$Name", value.Name), Parameter("$IsActive", value.IsActive), Parameter("$Id", value.Id), Parameter("$ExpectedVersion", expectedVersion)); if (changed == 0) return 0; await transaction.Session.ExecuteAsync("DELETE FROM FinanceDunningPolicyLevels WHERE PolicyId=$Id;", cancellationToken, Parameter("$Id", value.Id)); await ReplaceDunningLevelsAsync(transaction, value.Id, value.Levels, cancellationToken); return changed; }
	internal Task<FinanceDunningRun?> FindDunningRunByOperationAsync(DatabaseTransactionContext transaction, Guid operationId, CancellationToken cancellationToken) => transaction.Session.QuerySingleOrDefaultAsync("SELECT Id,OperationId,RequestHash,PolicyId,AsOfDate,CreatedAtUtc,CreatedByUserId FROM FinanceDunningRuns WHERE OperationId=$OperationId;", ReadDunningRun, cancellationToken, Parameter("$OperationId", operationId.ToString("D")));
	internal async Task<long> CreateDunningRunAsync(DatabaseTransactionContext transaction, FinanceDunningRun value, CancellationToken cancellationToken) { var id = await transaction.Session.InsertAsync("INSERT INTO FinanceDunningRuns (OperationId,RequestHash,PolicyId,AsOfDate,CreatedAtUtc,CreatedByUserId) VALUES ($OperationId,$RequestHash,$PolicyId,$AsOfDate,$CreatedAtUtc,$CreatedByUserId);", cancellationToken, Parameter("$OperationId", value.OperationId.ToString("D")), Parameter("$RequestHash", value.RequestHash), Parameter("$PolicyId", value.PolicyId), Parameter("$AsOfDate", value.AsOfDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)), Parameter("$CreatedAtUtc", value.CreatedAtUtc.ToString("O", CultureInfo.InvariantCulture)), Parameter("$CreatedByUserId", value.CreatedByUserId)); foreach (var line in value.Lines) await transaction.Session.ExecuteAsync("INSERT INTO FinanceDunningRunLines (RunId,OpenItemId,CustomerId,CurrencyCode,OutstandingAmount,DaysOverdue,LevelNumber,LevelCode) VALUES ($RunId,$OpenItemId,$CustomerId,$Currency,$Outstanding,$Days,$LevelNumber,$LevelCode);", cancellationToken, Parameter("$RunId", id), Parameter("$OpenItemId", line.OpenItemId), Parameter("$CustomerId", line.CustomerId), Parameter("$Currency", line.Currency.Value), Parameter("$Outstanding", line.OutstandingAmount), Parameter("$Days", line.DaysOverdue), Parameter("$LevelNumber", line.LevelNumber), Parameter("$LevelCode", line.LevelCode)); return id; }
	internal Task<IReadOnlyList<FinanceReceivableOpenItem>> GetDunningCandidatesAsync(DatabaseTransactionContext transaction, Guid legalEntityId, DateOnly asOfDate, CancellationToken cancellationToken) => transaction.Session.QueryAsync($"SELECT {OpenItemColumns} FROM FinanceReceivableOpenItems oi INNER JOIN Customers c ON c.Id=oi.CustomerId WHERE oi.LegalEntityId=$LegalEntityId AND oi.Kind=1 AND oi.IsVoided=0 AND oi.RemainingAmount>0 AND oi.DueDate<$AsOfDate ORDER BY oi.DueDate,oi.Id;", ReadOpenItem, cancellationToken, Parameter("$LegalEntityId", legalEntityId.ToString("D")), Parameter("$AsOfDate", asOfDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)));

	private static async Task ReplaceDunningLevelsAsync(DatabaseTransactionContext transaction, long policyId, IReadOnlyList<FinanceDunningLevel> levels, CancellationToken cancellationToken) { foreach (var level in levels.OrderBy(value => value.LevelNumber)) await transaction.Session.ExecuteAsync("INSERT INTO FinanceDunningPolicyLevels (PolicyId,LevelNumber,MinimumDaysOverdue,Code,Name) VALUES ($PolicyId,$LevelNumber,$MinimumDays,$Code,$Name);", cancellationToken, Parameter("$PolicyId", policyId), Parameter("$LevelNumber", level.LevelNumber), Parameter("$MinimumDays", level.MinimumDaysOverdue), Parameter("$Code", level.Code), Parameter("$Name", level.Name)); }
	private Task<IReadOnlyList<FinanceDunningLevel>> LoadPolicyLevelsAsync(long policyId, CancellationToken cancellationToken) => Database.QueryAsync("SELECT Id,PolicyId,LevelNumber,MinimumDaysOverdue,Code,Name FROM FinanceDunningPolicyLevels WHERE PolicyId=$Id ORDER BY LevelNumber;", ReadPolicyLevel, cancellationToken, Parameter("$Id", policyId));
	private Task<IReadOnlyList<FinanceDunningRunLine>> LoadRunLinesAsync(long runId, CancellationToken cancellationToken) => Database.QueryAsync("SELECT l.Id,l.RunId,l.OpenItemId,l.CustomerId,c.Name,l.CurrencyCode,l.OutstandingAmount,l.DaysOverdue,l.LevelNumber,l.LevelCode FROM FinanceDunningRunLines l INNER JOIN Customers c ON c.Id=l.CustomerId WHERE l.RunId=$RunId ORDER BY c.Name,l.CurrencyCode,l.OpenItemId;", ReadRunLine, cancellationToken, Parameter("$RunId", runId));
	private static DatabaseParameter[] ConfigurationParameters(FinanceReceivablesConfiguration value) => [Parameter("$LegalEntityId", value.LegalEntityId.ToString("D")), Parameter("$FiscalCalendarId", value.FiscalCalendarId.ToString("D")), Parameter("$InvoiceProfile", value.InvoicePostingProfileId), Parameter("$CreditProfile", value.CreditNotePostingProfileId), Parameter("$PaymentProfile", value.PaymentPostingProfileId), Parameter("$WriteOffProfile", value.WriteOffPostingProfileId), Parameter("$IsActive", value.IsActive)];
	private static FinanceReceivablesConfiguration ReadConfiguration(DbDataReader reader) => new() { Id=reader.GetInt64(0), Version=Convert.ToInt64(reader.GetValue(1),CultureInfo.InvariantCulture), LegalEntityId=Guid.Parse(reader.GetString(2)), FiscalCalendarId=Guid.Parse(reader.GetString(3)), InvoicePostingProfileId=reader.GetInt64(4), CreditNotePostingProfileId=reader.GetInt64(5), PaymentPostingProfileId=reader.GetInt64(6), WriteOffPostingProfileId=reader.GetInt64(7), IsActive=ReadBool(reader,8) };
	private static FinanceReceivableOpenItem ReadOpenItem(DbDataReader reader) => new() { Id=reader.GetInt64(0), Version=Convert.ToInt64(reader.GetValue(1),CultureInfo.InvariantCulture), LegalEntityId=Guid.Parse(reader.GetString(2)), AccountingBookId=Guid.Parse(reader.GetString(3)), CustomerId=reader.GetInt64(4), CustomerName=reader.GetString(5), Kind=(FinanceReceivableOpenItemKind)Convert.ToInt32(reader.GetValue(6),CultureInfo.InvariantCulture), SourceType=reader.GetString(7), SourceId=reader.GetString(8), SourceReference=reader.IsDBNull(9)?null:reader.GetString(9), DocumentDate=ReadDateOnly(reader,10), DueDate=ReadDateOnly(reader,11), Currency=new CurrencyCode(reader.GetString(12)), OriginalAmount=ReadDecimal(reader,13), RemainingAmount=ReadDecimal(reader,14), JournalEntryId=reader.GetInt64(15), OperationId=Guid.Parse(reader.GetString(16)), IsVoided=ReadBool(reader,17), CreatedAtUtc=ReadDateTimeUtc(reader,18), CreatedByUserId=reader.IsDBNull(19)?null:reader.GetInt64(19) };
	private static FinanceReceivableAllocation ReadAllocation(DbDataReader reader) => new() { Id=reader.GetInt64(0), OperationId=Guid.Parse(reader.GetString(1)), DebitOpenItemId=reader.GetInt64(2), CreditOpenItemId=reader.GetInt64(3), Amount=ReadDecimal(reader,4), AllocationDate=ReadDateOnly(reader,5), CreatedAtUtc=ReadDateTimeUtc(reader,6), CreatedByUserId=reader.IsDBNull(7)?null:reader.GetInt64(7), ReversedAtUtc=reader.IsDBNull(8)?null:ReadDateTimeUtc(reader,8), ReversedByUserId=reader.IsDBNull(9)?null:reader.GetInt64(9), ReversalOperationId=reader.IsDBNull(10)?null:Guid.Parse(reader.GetString(10)) };
	private static FinanceReceivablePayment ReadPayment(DbDataReader reader) => new() { Id=reader.GetInt64(0), Version=Convert.ToInt64(reader.GetValue(1),CultureInfo.InvariantCulture), OperationId=Guid.Parse(reader.GetString(2)), RequestHash=reader.GetString(3), CustomerId=reader.GetInt64(4), Currency=new CurrencyCode(reader.GetString(5)), PaymentDate=ReadDateOnly(reader,6), Amount=ReadDecimal(reader,7), Reference=reader.IsDBNull(8)?null:reader.GetString(8), Description=reader.GetString(9), OpenItemId=reader.GetInt64(10), JournalEntryId=reader.GetInt64(11), CreatedAtUtc=ReadDateTimeUtc(reader,12), CreatedByUserId=reader.IsDBNull(13)?null:reader.GetInt64(13), IsReversed=ReadBool(reader,14), ReversalOperationId=reader.IsDBNull(15)?null:Guid.Parse(reader.GetString(15)), ReversalJournalEntryId=reader.IsDBNull(16)?null:reader.GetInt64(16), ReversedAtUtc=reader.IsDBNull(17)?null:ReadDateTimeUtc(reader,17), ReversedByUserId=reader.IsDBNull(18)?null:reader.GetInt64(18) };
	private static FinanceReceivableWriteOff ReadWriteOff(DbDataReader reader) => new() { Id=reader.GetInt64(0), Version=Convert.ToInt64(reader.GetValue(1),CultureInfo.InvariantCulture), OperationId=Guid.Parse(reader.GetString(2)), RequestHash=reader.GetString(3), OpenItemId=reader.GetInt64(4), Amount=ReadDecimal(reader,5), PostingDate=ReadDateOnly(reader,6), Reason=reader.GetString(7), JournalEntryId=reader.GetInt64(8), CreatedAtUtc=ReadDateTimeUtc(reader,9), CreatedByUserId=reader.IsDBNull(10)?null:reader.GetInt64(10), IsReversed=ReadBool(reader,11), ReversalOperationId=reader.IsDBNull(12)?null:Guid.Parse(reader.GetString(12)), ReversalJournalEntryId=reader.IsDBNull(13)?null:reader.GetInt64(13), ReversedAtUtc=reader.IsDBNull(14)?null:ReadDateTimeUtc(reader,14), ReversedByUserId=reader.IsDBNull(15)?null:reader.GetInt64(15) };
	private static FinanceDunningPolicy ReadPolicy(DbDataReader reader) => new() { Id=reader.GetInt64(0), Version=Convert.ToInt64(reader.GetValue(1),CultureInfo.InvariantCulture), LegalEntityId=Guid.Parse(reader.GetString(2)), Code=reader.GetString(3), Name=reader.GetString(4), IsActive=ReadBool(reader,5) };
	private static FinanceDunningLevel ReadPolicyLevel(DbDataReader reader) => new() { Id=reader.GetInt64(0), PolicyId=reader.GetInt64(1), LevelNumber=Convert.ToInt32(reader.GetValue(2),CultureInfo.InvariantCulture), MinimumDaysOverdue=Convert.ToInt32(reader.GetValue(3),CultureInfo.InvariantCulture), Code=reader.GetString(4), Name=reader.GetString(5) };
	private static FinanceDunningRun ReadDunningRun(DbDataReader reader) => new() { Id=reader.GetInt64(0), OperationId=Guid.Parse(reader.GetString(1)), RequestHash=reader.GetString(2), PolicyId=reader.GetInt64(3), AsOfDate=ReadDateOnly(reader,4), CreatedAtUtc=ReadDateTimeUtc(reader,5), CreatedByUserId=reader.IsDBNull(6)?null:reader.GetInt64(6) };
	private static FinanceDunningRunLine ReadRunLine(DbDataReader reader) => new() { Id=reader.GetInt64(0), RunId=reader.GetInt64(1), OpenItemId=reader.GetInt64(2), CustomerId=reader.GetInt64(3), CustomerName=reader.GetString(4), Currency=new CurrencyCode(reader.GetString(5)), OutstandingAmount=ReadDecimal(reader,6), DaysOverdue=Convert.ToInt32(reader.GetValue(7),CultureInfo.InvariantCulture), LevelNumber=Convert.ToInt32(reader.GetValue(8),CultureInfo.InvariantCulture), LevelCode=reader.GetString(9) };
	private static bool ReadBool(DbDataReader reader, int ordinal) => Convert.ToBoolean(reader.GetValue(ordinal), CultureInfo.InvariantCulture);
	private static decimal ReadDecimal(DbDataReader reader, int ordinal) => Convert.ToDecimal(reader.GetValue(ordinal), CultureInfo.InvariantCulture);
	private static DateOnly ReadDateOnly(DbDataReader reader, int ordinal) => reader.GetValue(ordinal) is DateTime dateTime ? DateOnly.FromDateTime(dateTime) : DateOnly.Parse(Convert.ToString(reader.GetValue(ordinal),CultureInfo.InvariantCulture) ?? string.Empty,CultureInfo.InvariantCulture);
	private static DateTime ReadDateTimeUtc(DbDataReader reader, int ordinal) => reader.GetValue(ordinal) is DateTime dateTime ? DateTime.SpecifyKind(dateTime,DateTimeKind.Utc) : DateTime.Parse(Convert.ToString(reader.GetValue(ordinal),CultureInfo.InvariantCulture) ?? string.Empty,CultureInfo.InvariantCulture,DateTimeStyles.RoundtripKind).ToUniversalTime();
}

internal sealed record FinanceFiscalCalendarRecord(Guid Id, Guid LegalEntityId, bool IsActive);
internal sealed record FinanceAccountingPeriodRecord(Guid Id, DateOnly StartDate, DateOnly EndDate, AccountingPeriodStatus Status);
internal sealed record FinanceReceivableAgingRow(long CustomerId, string CustomerName, CurrencyCode Currency, DateOnly DueDate, decimal RemainingAmount, FinanceReceivableOpenItemKind Kind);
