// Copyright (c) 2026 David Beusing
// Licensed under the MIT License.

using System.Data.Common;
using System.Globalization;

using Depot.Data;
using Depot.Models;

namespace Depot.Repositories;

public sealed class FinanceAccountsPayableRepository : DatabaseRepository
{
	private const string DocumentColumns = "d.Id,d.Version,d.Kind,d.SupplierId,s.Name,d.SupplierDocumentNumber,d.InternalReference,d.DocumentDate,d.DueDate,d.CurrencyCode,d.Status,d.NetAmount,d.TaxAmount,d.GrossAmount,d.CreatedByUserId,d.CreatedAtUtc,d.SubmittedByUserId,d.SubmittedAtUtc,d.ApprovalDecisionByUserId,d.ApprovalDecisionAtUtc,d.ApprovalComment,d.MatchExceptionApproved,d.MatchExceptionReason,d.PostedByUserId,d.PostedAtUtc,d.PostingOperationId,d.OpenItemId,d.JournalEntryId,d.ReversalOperationId,d.ReversalJournalEntryId,d.ReversedAtUtc,d.ReversedByUserId";
	private const string LineColumns = "Id,DocumentId,LineNumber,PurchaseOrderLineId,GoodsReceiptLineId,Description,Quantity,UnitPrice,NetAmount,TaxAmount,GrossAmount,MatchStatus,OrderedUnitPrice,ReceivedQuantity,PreviouslyInvoicedQuantity,QuantityVariance,PriceVariance";
	private const string OpenItemColumns = "oi.Id,oi.Version,oi.LegalEntityId,oi.AccountingBookId,oi.SupplierId,s.Name,oi.Kind,oi.SourceType,oi.SourceId,oi.SourceReference,oi.DocumentDate,oi.DueDate,oi.CurrencyCode,oi.OriginalAmount,oi.RemainingAmount,oi.JournalEntryId,oi.OperationId,oi.IsVoided,oi.CreatedAtUtc,oi.CreatedByUserId";
	private const string PaymentColumns = "Id,Version,OperationId,RequestHash,SupplierId,CurrencyCode,PaymentDate,Amount,Reference,Description,OpenItemId,JournalEntryId,CreatedAtUtc,CreatedByUserId,IsReversed,ReversalOperationId,ReversalJournalEntryId,ReversedAtUtc,ReversedByUserId";

	public FinanceAccountsPayableRepository(DatabaseAccess database) : base(database) { }

	public Task<FinancePayablesConfiguration?> GetConfigurationAsync(CancellationToken cancellationToken = default) =>
		Database.QuerySingleOrDefaultAsync("SELECT Id,Version,LegalEntityId,FiscalCalendarId,InvoicePostingProfileId,CreditNotePostingProfileId,PaymentPostingProfileId,IsActive FROM FinancePayablesConfigurations ORDER BY Id;", ReadConfiguration, cancellationToken);

	public Task<PageResult<FinanceSupplierDocument>> SearchDocumentsAsync(string? searchText, FinancePayableDocumentStatus? status, int pageNumber, int pageSize, CancellationToken cancellationToken = default)
	{
		var filters = new List<string> { "1=1" };
		var parameters = new List<DatabaseParameter>();
		if (status.HasValue) { filters.Add("d.Status=$Status"); parameters.Add(Parameter("$Status", (int)status.Value)); }
		if (!string.IsNullOrWhiteSpace(searchText))
		{
			filters.Add("(s.Name LIKE $Search OR d.SupplierDocumentNumber LIKE $Search OR d.InternalReference LIKE $Search)");
			parameters.Add(Parameter("$Search", $"%{searchText.Trim()}%"));
		}
		var from = "FROM FinanceSupplierDocuments d INNER JOIN Suppliers s ON s.Id=d.SupplierId";
		var where = $"WHERE {string.Join(" AND ", filters)}";
		return Database.QueryPageAsync($"SELECT {DocumentColumns} {from} {where} ORDER BY d.DocumentDate DESC,d.Id DESC", $"SELECT COUNT(*) {from} {where};", ReadDocument, pageNumber, pageSize, cancellationToken, parameters.ToArray());
	}

	public async Task<FinanceSupplierDocument?> GetDocumentAsync(long id, CancellationToken cancellationToken = default)
	{
		var document = await Database.QuerySingleOrDefaultAsync($"SELECT {DocumentColumns} FROM FinanceSupplierDocuments d INNER JOIN Suppliers s ON s.Id=d.SupplierId WHERE d.Id=$Id;", ReadDocument, cancellationToken, Parameter("$Id", id));
		return document is null ? null : document with { Lines = await LoadLinesAsync(id, cancellationToken) };
	}

	public Task<PageResult<FinancePayableOpenItem>> SearchOpenItemsAsync(string? searchText, bool includeSettled, int pageNumber, int pageSize, CancellationToken cancellationToken = default)
	{
		var filters = new List<string> { "oi.IsVoided=0" };
		var parameters = new List<DatabaseParameter>();
		if (!includeSettled) filters.Add("oi.RemainingAmount>0");
		if (!string.IsNullOrWhiteSpace(searchText))
		{
			filters.Add("(s.Name LIKE $Search OR oi.SourceReference LIKE $Search OR oi.SourceId LIKE $Search)");
			parameters.Add(Parameter("$Search", $"%{searchText.Trim()}%"));
		}
		var from = "FROM FinancePayableOpenItems oi INNER JOIN Suppliers s ON s.Id=oi.SupplierId";
		var where = $"WHERE {string.Join(" AND ", filters)}";
		return Database.QueryPageAsync($"SELECT {OpenItemColumns} {from} {where} ORDER BY oi.DueDate,oi.Id", $"SELECT COUNT(*) {from} {where};", ReadOpenItem, pageNumber, pageSize, cancellationToken, parameters.ToArray());
	}

	public Task<FinancePayableOpenItem?> GetOpenItemAsync(long id, CancellationToken cancellationToken = default) =>
		Database.QuerySingleOrDefaultAsync($"SELECT {OpenItemColumns} FROM FinancePayableOpenItems oi INNER JOIN Suppliers s ON s.Id=oi.SupplierId WHERE oi.Id=$Id;", ReadOpenItem, cancellationToken, Parameter("$Id", id));

	public Task<FinancePayablePayment?> GetPaymentAsync(long id, CancellationToken cancellationToken = default) =>
		Database.QuerySingleOrDefaultAsync($"SELECT {PaymentColumns} FROM FinancePayablePayments WHERE Id=$Id;", ReadPayment, cancellationToken, Parameter("$Id", id));

	public Task<IReadOnlyList<FinancePayableAgingRow>> GetAgingRowsAsync(DateOnly asOfDate, CancellationToken cancellationToken = default) =>
		Database.QueryAsync("SELECT oi.SupplierId,s.Name,oi.CurrencyCode,oi.DueDate,oi.RemainingAmount,oi.Kind FROM FinancePayableOpenItems oi INNER JOIN Suppliers s ON s.Id=oi.SupplierId WHERE oi.IsVoided=0 AND oi.RemainingAmount>0 AND oi.DocumentDate<=$AsOfDate ORDER BY s.Name,oi.CurrencyCode,oi.DueDate,oi.Id;", reader => new FinancePayableAgingRow(reader.GetInt64(0), reader.GetString(1), new CurrencyCode(reader.GetString(2)), ReadDateOnly(reader,3), ReadDecimal(reader,4), (FinancePayableOpenItemKind)Convert.ToInt32(reader.GetValue(5),CultureInfo.InvariantCulture)), cancellationToken, Parameter("$AsOfDate", asOfDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)));

	public Task<IReadOnlyList<FinanceSupplierStatementRow>> GetSupplierStatementAsync(long supplierId, CurrencyCode currency, DateOnly fromDate, DateOnly toDate, CancellationToken cancellationToken = default) =>
		Database.QueryAsync("SELECT DocumentDate,Kind,COALESCE(SourceReference,SourceId),SourceType,CurrencyCode,OriginalAmount,RemainingAmount FROM FinancePayableOpenItems WHERE SupplierId=$SupplierId AND CurrencyCode=$Currency AND DocumentDate>=$FromDate AND DocumentDate<=$ToDate AND IsVoided=0 ORDER BY DocumentDate,Id;", reader =>
		{
			var kind = (FinancePayableOpenItemKind)Convert.ToInt32(reader.GetValue(1), CultureInfo.InvariantCulture);
			var amount = ReadDecimal(reader,5);
			return new FinanceSupplierStatementRow(ReadDateOnly(reader,0), kind.ToString(), reader.GetString(2), reader.GetString(3), new CurrencyCode(reader.GetString(4)), kind == FinancePayableOpenItemKind.Invoice ? 0m : amount, kind == FinancePayableOpenItemKind.Invoice ? amount : 0m, ReadDecimal(reader,6));
		}, cancellationToken, Parameter("$SupplierId", supplierId), Parameter("$Currency", currency.Value), Parameter("$FromDate", fromDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)), Parameter("$ToDate", toDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)));

	internal Task<FinancePayablesConfiguration?> GetAnyConfigurationAsync(DatabaseTransactionContext transaction, CancellationToken cancellationToken) => transaction.Session.QuerySingleOrDefaultAsync("SELECT Id,Version,LegalEntityId,FiscalCalendarId,InvoicePostingProfileId,CreditNotePostingProfileId,PaymentPostingProfileId,IsActive FROM FinancePayablesConfigurations ORDER BY Id;", ReadConfiguration, cancellationToken);
	internal Task<IReadOnlyList<FinancePayablesConfiguration>> GetActiveConfigurationsAsync(DatabaseTransactionContext transaction, CancellationToken cancellationToken) => transaction.Session.QueryAsync("SELECT Id,Version,LegalEntityId,FiscalCalendarId,InvoicePostingProfileId,CreditNotePostingProfileId,PaymentPostingProfileId,IsActive FROM FinancePayablesConfigurations WHERE IsActive=1 ORDER BY Id;", ReadConfiguration, cancellationToken);
	internal Task<FinancePayablesConfiguration?> GetConfigurationAsync(DatabaseTransactionContext transaction, long id, CancellationToken cancellationToken) => transaction.Session.QuerySingleOrDefaultAsync("SELECT Id,Version,LegalEntityId,FiscalCalendarId,InvoicePostingProfileId,CreditNotePostingProfileId,PaymentPostingProfileId,IsActive FROM FinancePayablesConfigurations WHERE Id=$Id;", ReadConfiguration, cancellationToken, Parameter("$Id", id));
	internal Task<long> CreateConfigurationAsync(DatabaseTransactionContext transaction, FinancePayablesConfiguration value, CancellationToken cancellationToken) => transaction.Session.InsertAsync("INSERT INTO FinancePayablesConfigurations (Version,LegalEntityId,FiscalCalendarId,InvoicePostingProfileId,CreditNotePostingProfileId,PaymentPostingProfileId,IsActive) VALUES (1,$LegalEntityId,$FiscalCalendarId,$InvoiceProfile,$CreditProfile,$PaymentProfile,$IsActive);", cancellationToken, ConfigurationParameters(value));
	internal Task<int> UpdateConfigurationAsync(DatabaseTransactionContext transaction, FinancePayablesConfiguration value, long expectedVersion, CancellationToken cancellationToken) => transaction.Session.ExecuteAsync("UPDATE FinancePayablesConfigurations SET Version=Version+1,LegalEntityId=$LegalEntityId,FiscalCalendarId=$FiscalCalendarId,InvoicePostingProfileId=$InvoiceProfile,CreditNotePostingProfileId=$CreditProfile,PaymentPostingProfileId=$PaymentProfile,IsActive=$IsActive WHERE Id=$Id AND Version=$ExpectedVersion;", cancellationToken, ConfigurationParameters(value).Append(Parameter("$Id", value.Id)).Append(Parameter("$ExpectedVersion", expectedVersion)).ToArray());
	internal Task<FinanceFiscalCalendarRecord?> GetFiscalCalendarAsync(DatabaseTransactionContext transaction, Guid id, CancellationToken cancellationToken) => transaction.Session.QuerySingleOrDefaultAsync("SELECT Id,LegalEntityId,IsActive FROM FinanceFiscalCalendars WHERE Id=$Id;", reader => new FinanceFiscalCalendarRecord(Guid.Parse(reader.GetString(0)), Guid.Parse(reader.GetString(1)), ReadBool(reader,2)), cancellationToken, Parameter("$Id", id.ToString("D")));
	internal Task<IReadOnlyList<FinanceAccountingPeriodRecord>> FindOpenPeriodsAsync(DatabaseTransactionContext transaction, Guid calendarId, DateOnly date, CancellationToken cancellationToken) => transaction.Session.QueryAsync("SELECT Id,StartDate,EndDate,Status FROM FinanceAccountingPeriods WHERE FiscalCalendarId=$CalendarId AND StartDate<=$Date AND EndDate>=$Date AND Status=0 ORDER BY StartDate,Id;", reader => new FinanceAccountingPeriodRecord(Guid.Parse(reader.GetString(0)),ReadDateOnly(reader,1),ReadDateOnly(reader,2),(AccountingPeriodStatus)Convert.ToInt32(reader.GetValue(3),CultureInfo.InvariantCulture)), cancellationToken, Parameter("$CalendarId", calendarId.ToString("D")), Parameter("$Date", date.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture)));
	internal Task<bool> SupplierExistsAsync(DatabaseTransactionContext transaction, long supplierId, CancellationToken cancellationToken) => transaction.Session.QuerySingleOrDefaultAsync("SELECT COUNT(*) FROM Suppliers WHERE Id=$Id AND IsActive=1;", reader => Convert.ToInt64(reader.GetValue(0),CultureInfo.InvariantCulture) > 0, cancellationToken, Parameter("$Id", supplierId)).ContinueWith(task => task.Result, cancellationToken, TaskContinuationOptions.ExecuteSynchronously, TaskScheduler.Default);

	internal async Task<FinanceSupplierDocument?> GetDocumentAsync(DatabaseTransactionContext transaction, long id, CancellationToken cancellationToken)
	{
		var document = await transaction.Session.QuerySingleOrDefaultAsync($"SELECT {DocumentColumns} FROM FinanceSupplierDocuments d INNER JOIN Suppliers s ON s.Id=d.SupplierId WHERE d.Id=$Id;", ReadDocument, cancellationToken, Parameter("$Id", id));
		return document is null ? null : document with { Lines = await LoadLinesAsync(transaction,id,cancellationToken) };
	}

	internal async Task<FinanceSupplierDocument?> LockDocumentAsync(DatabaseTransactionContext transaction, long id, CancellationToken cancellationToken)
	{
		await transaction.Session.ExecuteAsync("UPDATE FinanceSupplierDocuments SET Version=Version WHERE Id=$Id;", cancellationToken, Parameter("$Id", id));
		return await GetDocumentAsync(transaction,id,cancellationToken);
	}

	internal Task<long> CreateDocumentAsync(DatabaseTransactionContext transaction, FinanceSupplierDocument value, CancellationToken cancellationToken) => transaction.Session.InsertAsync("INSERT INTO FinanceSupplierDocuments (Version,Kind,SupplierId,SupplierDocumentNumber,InternalReference,DocumentDate,DueDate,CurrencyCode,Status,NetAmount,TaxAmount,GrossAmount,CreatedByUserId,CreatedAtUtc,MatchExceptionApproved) VALUES (1,$Kind,$SupplierId,$Number,$Reference,$DocumentDate,$DueDate,$Currency,$Status,$Net,$Tax,$Gross,$CreatedBy,$CreatedAt,0);", cancellationToken, DocumentBaseParameters(value));
	internal Task<int> UpdateDraftAsync(DatabaseTransactionContext transaction, FinanceSupplierDocument value, long expectedVersion, CancellationToken cancellationToken) => transaction.Session.ExecuteAsync("UPDATE FinanceSupplierDocuments SET Version=Version+1,Kind=$Kind,SupplierId=$SupplierId,SupplierDocumentNumber=$Number,InternalReference=$Reference,DocumentDate=$DocumentDate,DueDate=$DueDate,CurrencyCode=$Currency,NetAmount=$Net,TaxAmount=$Tax,GrossAmount=$Gross WHERE Id=$Id AND Version=$ExpectedVersion AND Status=0;", cancellationToken, DocumentBaseParameters(value).Append(Parameter("$Id",value.Id)).Append(Parameter("$ExpectedVersion",expectedVersion)).ToArray());
	internal Task<int> SetSubmittedAsync(DatabaseTransactionContext transaction, long id, long expectedVersion, long userId, DateTime atUtc, CancellationToken cancellationToken) => transaction.Session.ExecuteAsync("UPDATE FinanceSupplierDocuments SET Version=Version+1,Status=1,SubmittedByUserId=$UserId,SubmittedAtUtc=$At,ApprovalDecisionByUserId=NULL,ApprovalDecisionAtUtc=NULL,ApprovalComment=NULL,MatchExceptionApproved=0,MatchExceptionReason=NULL WHERE Id=$Id AND Version=$Version AND Status=0;", cancellationToken, Parameter("$UserId",userId),Parameter("$At",atUtc.ToString("O",CultureInfo.InvariantCulture)),Parameter("$Id",id),Parameter("$Version",expectedVersion));
	internal Task<int> SetApprovalAsync(DatabaseTransactionContext transaction, long id, long expectedVersion, FinancePayableDocumentStatus status, long userId, DateTime atUtc, string? comment, bool exceptionApproved, string? exceptionReason, CancellationToken cancellationToken) => transaction.Session.ExecuteAsync("UPDATE FinanceSupplierDocuments SET Version=Version+1,Status=$Status,ApprovalDecisionByUserId=$UserId,ApprovalDecisionAtUtc=$At,ApprovalComment=$Comment,MatchExceptionApproved=$ExceptionApproved,MatchExceptionReason=$ExceptionReason WHERE Id=$Id AND Version=$Version AND Status=1;", cancellationToken, Parameter("$Status",(int)status),Parameter("$UserId",userId),Parameter("$At",atUtc.ToString("O",CultureInfo.InvariantCulture)),Parameter("$Comment",comment),Parameter("$ExceptionApproved",exceptionApproved),Parameter("$ExceptionReason",exceptionReason),Parameter("$Id",id),Parameter("$Version",expectedVersion));
	internal Task<int> SetPostedAsync(DatabaseTransactionContext transaction, long id, long expectedVersion, Guid operationId, long openItemId, long journalEntryId, long userId, DateTime atUtc, CancellationToken cancellationToken) => transaction.Session.ExecuteAsync("UPDATE FinanceSupplierDocuments SET Version=Version+1,Status=4,PostingOperationId=$OperationId,OpenItemId=$OpenItemId,JournalEntryId=$JournalEntryId,PostedByUserId=$UserId,PostedAtUtc=$At WHERE Id=$Id AND Version=$Version AND Status=2;", cancellationToken, Parameter("$OperationId",operationId.ToString("D")),Parameter("$OpenItemId",openItemId),Parameter("$JournalEntryId",journalEntryId),Parameter("$UserId",userId),Parameter("$At",atUtc.ToString("O",CultureInfo.InvariantCulture)),Parameter("$Id",id),Parameter("$Version",expectedVersion));
	internal Task<int> SetReversedAsync(DatabaseTransactionContext transaction, long id, long expectedVersion, Guid operationId, long reversalEntryId, long userId, DateTime atUtc, CancellationToken cancellationToken) => transaction.Session.ExecuteAsync("UPDATE FinanceSupplierDocuments SET Version=Version+1,Status=5,ReversalOperationId=$OperationId,ReversalJournalEntryId=$JournalEntryId,ReversedByUserId=$UserId,ReversedAtUtc=$At WHERE Id=$Id AND Version=$Version AND Status=4;", cancellationToken, Parameter("$OperationId",operationId.ToString("D")),Parameter("$JournalEntryId",reversalEntryId),Parameter("$UserId",userId),Parameter("$At",atUtc.ToString("O",CultureInfo.InvariantCulture)),Parameter("$Id",id),Parameter("$Version",expectedVersion));
	internal Task<int> DeleteLinesAsync(DatabaseTransactionContext transaction, long documentId, CancellationToken cancellationToken) => transaction.Session.ExecuteAsync("DELETE FROM FinanceSupplierDocumentLines WHERE DocumentId=$DocumentId;", cancellationToken, Parameter("$DocumentId",documentId));
	internal Task<int> CreateLineAsync(DatabaseTransactionContext transaction, FinanceSupplierDocumentLine line, CancellationToken cancellationToken) => transaction.Session.ExecuteAsync("INSERT INTO FinanceSupplierDocumentLines (DocumentId,LineNumber,PurchaseOrderLineId,GoodsReceiptLineId,Description,Quantity,UnitPrice,NetAmount,TaxAmount,GrossAmount,MatchStatus,OrderedUnitPrice,ReceivedQuantity,PreviouslyInvoicedQuantity,QuantityVariance,PriceVariance) VALUES ($DocumentId,$LineNumber,$PoLineId,$ReceiptLineId,$Description,$Quantity,$UnitPrice,$Net,$Tax,$Gross,$MatchStatus,$OrderedUnitPrice,$ReceivedQuantity,$PreviouslyInvoiced,$QuantityVariance,$PriceVariance);", cancellationToken, LineParameters(line));
	internal Task<int> UpdateLineMatchAsync(DatabaseTransactionContext transaction, FinanceSupplierDocumentLine line, CancellationToken cancellationToken) => transaction.Session.ExecuteAsync("UPDATE FinanceSupplierDocumentLines SET MatchStatus=$MatchStatus,OrderedUnitPrice=$OrderedUnitPrice,ReceivedQuantity=$ReceivedQuantity,PreviouslyInvoicedQuantity=$PreviouslyInvoiced,QuantityVariance=$QuantityVariance,PriceVariance=$PriceVariance WHERE Id=$Id;", cancellationToken, Parameter("$MatchStatus",(int)line.MatchStatus),Parameter("$OrderedUnitPrice",line.OrderedUnitPrice),Parameter("$ReceivedQuantity",line.ReceivedQuantity),Parameter("$PreviouslyInvoiced",line.PreviouslyInvoicedQuantity),Parameter("$QuantityVariance",line.QuantityVariance),Parameter("$PriceVariance",line.PriceVariance),Parameter("$Id",line.Id));
	internal Task<FinancePurchaseMatchReference?> GetPurchaseMatchReferenceAsync(DatabaseTransactionContext transaction, long purchaseOrderLineId, long? goodsReceiptLineId, CancellationToken cancellationToken) => transaction.Session.QuerySingleOrDefaultAsync(goodsReceiptLineId.HasValue ? "SELECT po.SupplierId,pol.UnitPrice,pol.Quantity,grl.Quantity FROM PurchaseOrderLines pol INNER JOIN PurchaseOrders po ON po.Id=pol.PurchaseOrderId INNER JOIN GoodsReceiptLines grl ON grl.PurchaseOrderLineId=pol.Id INNER JOIN GoodsReceipts gr ON gr.Id=grl.GoodsReceiptId WHERE pol.Id=$PoLineId AND grl.Id=$ReceiptLineId AND gr.ReversedAtUtc IS NULL;" : "SELECT po.SupplierId,pol.UnitPrice,pol.Quantity,COALESCE(SUM(CASE WHEN gr.ReversedAtUtc IS NULL THEN grl.Quantity ELSE 0 END),0) FROM PurchaseOrderLines pol INNER JOIN PurchaseOrders po ON po.Id=pol.PurchaseOrderId LEFT JOIN GoodsReceiptLines grl ON grl.PurchaseOrderLineId=pol.Id LEFT JOIN GoodsReceipts gr ON gr.Id=grl.GoodsReceiptId WHERE pol.Id=$PoLineId GROUP BY po.SupplierId,pol.UnitPrice,pol.Quantity;", reader => new FinancePurchaseMatchReference(reader.GetInt64(0),ReadDecimal(reader,1),ReadDecimal(reader,2),ReadDecimal(reader,3)), cancellationToken, Parameter("$PoLineId",purchaseOrderLineId),Parameter("$ReceiptLineId",goodsReceiptLineId));
	internal Task<decimal> GetPreviouslyInvoicedQuantityAsync(DatabaseTransactionContext transaction, long purchaseOrderLineId, long excludeDocumentId, CancellationToken cancellationToken) => transaction.Session.QuerySingleOrDefaultAsync("SELECT COALESCE(SUM(l.Quantity),0) FROM FinanceSupplierDocumentLines l INNER JOIN FinanceSupplierDocuments d ON d.Id=l.DocumentId WHERE l.PurchaseOrderLineId=$PoLineId AND d.Id<>$DocumentId AND d.Kind=1 AND d.Status IN (2,4);", reader => ReadDecimal(reader,0), cancellationToken, Parameter("$PoLineId",purchaseOrderLineId),Parameter("$DocumentId",excludeDocumentId)).ContinueWith(task => task.Result, cancellationToken, TaskContinuationOptions.ExecuteSynchronously, TaskScheduler.Default);

	internal async Task<FinancePayableOpenItem?> LockOpenItemAsync(DatabaseTransactionContext transaction, long id, CancellationToken cancellationToken)
	{
		await transaction.Session.ExecuteAsync("UPDATE FinancePayableOpenItems SET Version=Version WHERE Id=$Id;", cancellationToken, Parameter("$Id",id));
		return await transaction.Session.QuerySingleOrDefaultAsync($"SELECT {OpenItemColumns} FROM FinancePayableOpenItems oi INNER JOIN Suppliers s ON s.Id=oi.SupplierId WHERE oi.Id=$Id;", ReadOpenItem, cancellationToken, Parameter("$Id",id));
	}
	internal Task<FinancePayableOpenItem?> FindOpenItemBySourceAsync(DatabaseTransactionContext transaction, string sourceType, string sourceId, CancellationToken cancellationToken) => transaction.Session.QuerySingleOrDefaultAsync($"SELECT {OpenItemColumns} FROM FinancePayableOpenItems oi INNER JOIN Suppliers s ON s.Id=oi.SupplierId WHERE oi.SourceType=$SourceType AND oi.SourceId=$SourceId;", ReadOpenItem, cancellationToken, Parameter("$SourceType",sourceType),Parameter("$SourceId",sourceId));
	internal Task<long> CreateOpenItemAsync(DatabaseTransactionContext transaction, FinancePayableOpenItem value, CancellationToken cancellationToken) => transaction.Session.InsertAsync("INSERT INTO FinancePayableOpenItems (Version,LegalEntityId,AccountingBookId,SupplierId,Kind,SourceType,SourceId,SourceReference,DocumentDate,DueDate,CurrencyCode,OriginalAmount,RemainingAmount,JournalEntryId,OperationId,IsVoided,CreatedAtUtc,CreatedByUserId) VALUES (1,$LegalEntityId,$BookId,$SupplierId,$Kind,$SourceType,$SourceId,$SourceReference,$DocumentDate,$DueDate,$Currency,$Original,$Remaining,$JournalEntryId,$OperationId,$IsVoided,$CreatedAt,$CreatedBy);", cancellationToken, Parameter("$LegalEntityId",value.LegalEntityId.ToString("D")),Parameter("$BookId",value.AccountingBookId.ToString("D")),Parameter("$SupplierId",value.SupplierId),Parameter("$Kind",(int)value.Kind),Parameter("$SourceType",value.SourceType),Parameter("$SourceId",value.SourceId),Parameter("$SourceReference",value.SourceReference),Parameter("$DocumentDate",value.DocumentDate.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture)),Parameter("$DueDate",value.DueDate.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture)),Parameter("$Currency",value.Currency.Value),Parameter("$Original",value.OriginalAmount),Parameter("$Remaining",value.RemainingAmount),Parameter("$JournalEntryId",value.JournalEntryId),Parameter("$OperationId",value.OperationId.ToString("D")),Parameter("$IsVoided",value.IsVoided),Parameter("$CreatedAt",value.CreatedAtUtc.ToString("O",CultureInfo.InvariantCulture)),Parameter("$CreatedBy",value.CreatedByUserId));
	internal Task<int> UpdateOpenItemRemainingAsync(DatabaseTransactionContext transaction, long id, long expectedVersion, decimal remaining, bool isVoided, CancellationToken cancellationToken) => transaction.Session.ExecuteAsync("UPDATE FinancePayableOpenItems SET Version=Version+1,RemainingAmount=$Remaining,IsVoided=$IsVoided WHERE Id=$Id AND Version=$Version;", cancellationToken, Parameter("$Remaining",remaining),Parameter("$IsVoided",isVoided),Parameter("$Id",id),Parameter("$Version",expectedVersion));
	internal Task<int> CreateAllocationAsync(DatabaseTransactionContext transaction, FinancePayableAllocation value, CancellationToken cancellationToken) => transaction.Session.ExecuteAsync("INSERT INTO FinancePayableAllocations (OperationId,DebitOpenItemId,CreditOpenItemId,Amount,AllocationDate,CreatedAtUtc,CreatedByUserId) VALUES ($OperationId,$DebitId,$CreditId,$Amount,$Date,$At,$UserId);", cancellationToken, Parameter("$OperationId",value.OperationId.ToString("D")),Parameter("$DebitId",value.DebitOpenItemId),Parameter("$CreditId",value.CreditOpenItemId),Parameter("$Amount",value.Amount),Parameter("$Date",value.AllocationDate.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture)),Parameter("$At",value.CreatedAtUtc.ToString("O",CultureInfo.InvariantCulture)),Parameter("$UserId",value.CreatedByUserId));
	internal Task<IReadOnlyList<FinancePayableAllocation>> GetActiveAllocationsForDebitAsync(DatabaseTransactionContext transaction, long debitOpenItemId, CancellationToken cancellationToken) => transaction.Session.QueryAsync("SELECT Id,OperationId,DebitOpenItemId,CreditOpenItemId,Amount,AllocationDate,CreatedAtUtc,CreatedByUserId,ReversedAtUtc,ReversedByUserId,ReversalOperationId FROM FinancePayableAllocations WHERE DebitOpenItemId=$Id AND ReversedAtUtc IS NULL ORDER BY Id;", ReadAllocation, cancellationToken, Parameter("$Id",debitOpenItemId));
	internal Task<int> ReverseAllocationsForDebitAsync(DatabaseTransactionContext transaction, long debitOpenItemId, Guid reversalOperationId, DateTime atUtc, long userId, CancellationToken cancellationToken) => transaction.Session.ExecuteAsync("UPDATE FinancePayableAllocations SET ReversedAtUtc=$At,ReversedByUserId=$UserId,ReversalOperationId=$OperationId WHERE DebitOpenItemId=$DebitId AND ReversedAtUtc IS NULL;", cancellationToken, Parameter("$At",atUtc.ToString("O",CultureInfo.InvariantCulture)),Parameter("$UserId",userId),Parameter("$OperationId",reversalOperationId.ToString("D")),Parameter("$DebitId",debitOpenItemId));
	internal Task<FinanceAllocationOperationRecord?> FindAllocationOperationAsync(DatabaseTransactionContext transaction, Guid operationId, CancellationToken cancellationToken) => transaction.Session.QuerySingleOrDefaultAsync("SELECT OperationId,RequestHash,DebitOpenItemId FROM FinancePayableAllocationOperations WHERE OperationId=$OperationId;", reader => new FinanceAllocationOperationRecord(Guid.Parse(reader.GetString(0)),reader.GetString(1),reader.GetInt64(2)), cancellationToken, Parameter("$OperationId",operationId.ToString("D")));
	internal Task<int> CreateAllocationOperationAsync(DatabaseTransactionContext transaction, Guid operationId, string hash, long debitOpenItemId, DateTime atUtc, long userId, CancellationToken cancellationToken) => transaction.Session.ExecuteAsync("INSERT INTO FinancePayableAllocationOperations (OperationId,RequestHash,DebitOpenItemId,CreatedAtUtc,CreatedByUserId) VALUES ($OperationId,$Hash,$DebitId,$At,$UserId);", cancellationToken, Parameter("$OperationId",operationId.ToString("D")),Parameter("$Hash",hash),Parameter("$DebitId",debitOpenItemId),Parameter("$At",atUtc.ToString("O",CultureInfo.InvariantCulture)),Parameter("$UserId",userId));
	internal Task<FinancePayablePayment?> FindPaymentByOperationAsync(DatabaseTransactionContext transaction, Guid operationId, CancellationToken cancellationToken) => transaction.Session.QuerySingleOrDefaultAsync($"SELECT {PaymentColumns} FROM FinancePayablePayments WHERE OperationId=$OperationId;", ReadPayment, cancellationToken, Parameter("$OperationId",operationId.ToString("D")));
	internal async Task<FinancePayablePayment?> LockPaymentAsync(DatabaseTransactionContext transaction, long id, CancellationToken cancellationToken) { await transaction.Session.ExecuteAsync("UPDATE FinancePayablePayments SET Version=Version WHERE Id=$Id;", cancellationToken, Parameter("$Id",id)); return await transaction.Session.QuerySingleOrDefaultAsync($"SELECT {PaymentColumns} FROM FinancePayablePayments WHERE Id=$Id;", ReadPayment, cancellationToken, Parameter("$Id",id)); }
	internal Task<long> CreatePaymentAsync(DatabaseTransactionContext transaction, FinancePayablePayment value, CancellationToken cancellationToken) => transaction.Session.InsertAsync("INSERT INTO FinancePayablePayments (Version,OperationId,RequestHash,SupplierId,CurrencyCode,PaymentDate,Amount,Reference,Description,OpenItemId,JournalEntryId,CreatedAtUtc,CreatedByUserId,IsReversed) VALUES (1,$OperationId,$Hash,$SupplierId,$Currency,$Date,$Amount,$Reference,$Description,$OpenItemId,$JournalEntryId,$At,$UserId,0);", cancellationToken, Parameter("$OperationId",value.OperationId.ToString("D")),Parameter("$Hash",value.RequestHash),Parameter("$SupplierId",value.SupplierId),Parameter("$Currency",value.Currency.Value),Parameter("$Date",value.PaymentDate.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture)),Parameter("$Amount",value.Amount),Parameter("$Reference",value.Reference),Parameter("$Description",value.Description),Parameter("$OpenItemId",value.OpenItemId),Parameter("$JournalEntryId",value.JournalEntryId),Parameter("$At",value.CreatedAtUtc.ToString("O",CultureInfo.InvariantCulture)),Parameter("$UserId",value.CreatedByUserId));
	internal Task<int> MarkPaymentReversedAsync(DatabaseTransactionContext transaction, FinancePayablePayment value, long expectedVersion, Guid operationId, long reversalEntryId, DateTime atUtc, long userId, CancellationToken cancellationToken) => transaction.Session.ExecuteAsync("UPDATE FinancePayablePayments SET Version=Version+1,IsReversed=1,ReversalOperationId=$OperationId,ReversalJournalEntryId=$JournalEntryId,ReversedAtUtc=$At,ReversedByUserId=$UserId WHERE Id=$Id AND Version=$Version AND IsReversed=0;", cancellationToken, Parameter("$OperationId",operationId.ToString("D")),Parameter("$JournalEntryId",reversalEntryId),Parameter("$At",atUtc.ToString("O",CultureInfo.InvariantCulture)),Parameter("$UserId",userId),Parameter("$Id",value.Id),Parameter("$Version",expectedVersion));

	private Task<IReadOnlyList<FinanceSupplierDocumentLine>> LoadLinesAsync(long documentId, CancellationToken cancellationToken) => Database.QueryAsync($"SELECT {LineColumns} FROM FinanceSupplierDocumentLines WHERE DocumentId=$DocumentId ORDER BY LineNumber,Id;", ReadLine, cancellationToken, Parameter("$DocumentId",documentId));
	private Task<IReadOnlyList<FinanceSupplierDocumentLine>> LoadLinesAsync(DatabaseTransactionContext transaction, long documentId, CancellationToken cancellationToken) => transaction.Session.QueryAsync($"SELECT {LineColumns} FROM FinanceSupplierDocumentLines WHERE DocumentId=$DocumentId ORDER BY LineNumber,Id;", ReadLine, cancellationToken, Parameter("$DocumentId",documentId));
	private static DatabaseParameter[] ConfigurationParameters(FinancePayablesConfiguration value) => [Parameter("$LegalEntityId",value.LegalEntityId.ToString("D")),Parameter("$FiscalCalendarId",value.FiscalCalendarId.ToString("D")),Parameter("$InvoiceProfile",value.InvoicePostingProfileId),Parameter("$CreditProfile",value.CreditNotePostingProfileId),Parameter("$PaymentProfile",value.PaymentPostingProfileId),Parameter("$IsActive",value.IsActive)];
	private static IEnumerable<DatabaseParameter> DocumentBaseParameters(FinanceSupplierDocument value) => [Parameter("$Kind",(int)value.Kind),Parameter("$SupplierId",value.SupplierId),Parameter("$Number",value.SupplierDocumentNumber),Parameter("$Reference",value.InternalReference),Parameter("$DocumentDate",value.DocumentDate.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture)),Parameter("$DueDate",value.DueDate.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture)),Parameter("$Currency",value.Currency.Value),Parameter("$Status",(int)value.Status),Parameter("$Net",value.NetAmount),Parameter("$Tax",value.TaxAmount),Parameter("$Gross",value.GrossAmount),Parameter("$CreatedBy",value.CreatedByUserId),Parameter("$CreatedAt",value.CreatedAtUtc.ToString("O",CultureInfo.InvariantCulture))];
	private static DatabaseParameter[] LineParameters(FinanceSupplierDocumentLine line) => [Parameter("$DocumentId",line.DocumentId),Parameter("$LineNumber",line.LineNumber),Parameter("$PoLineId",line.PurchaseOrderLineId),Parameter("$ReceiptLineId",line.GoodsReceiptLineId),Parameter("$Description",line.Description),Parameter("$Quantity",line.Quantity),Parameter("$UnitPrice",line.UnitPrice),Parameter("$Net",line.NetAmount),Parameter("$Tax",line.TaxAmount),Parameter("$Gross",line.GrossAmount),Parameter("$MatchStatus",(int)line.MatchStatus),Parameter("$OrderedUnitPrice",line.OrderedUnitPrice),Parameter("$ReceivedQuantity",line.ReceivedQuantity),Parameter("$PreviouslyInvoiced",line.PreviouslyInvoicedQuantity),Parameter("$QuantityVariance",line.QuantityVariance),Parameter("$PriceVariance",line.PriceVariance)];
	private static FinancePayablesConfiguration ReadConfiguration(DbDataReader reader) => new() { Id=reader.GetInt64(0),Version=Convert.ToInt64(reader.GetValue(1),CultureInfo.InvariantCulture),LegalEntityId=Guid.Parse(reader.GetString(2)),FiscalCalendarId=Guid.Parse(reader.GetString(3)),InvoicePostingProfileId=reader.GetInt64(4),CreditNotePostingProfileId=reader.GetInt64(5),PaymentPostingProfileId=reader.GetInt64(6),IsActive=ReadBool(reader,7) };
	private static FinanceSupplierDocument ReadDocument(DbDataReader reader) => new() { Id=reader.GetInt64(0),Version=Convert.ToInt64(reader.GetValue(1),CultureInfo.InvariantCulture),Kind=(FinancePayableDocumentKind)Convert.ToInt32(reader.GetValue(2),CultureInfo.InvariantCulture),SupplierId=reader.GetInt64(3),SupplierName=reader.GetString(4),SupplierDocumentNumber=reader.GetString(5),InternalReference=reader.IsDBNull(6)?null:reader.GetString(6),DocumentDate=ReadDateOnly(reader,7),DueDate=ReadDateOnly(reader,8),Currency=new CurrencyCode(reader.GetString(9)),Status=(FinancePayableDocumentStatus)Convert.ToInt32(reader.GetValue(10),CultureInfo.InvariantCulture),NetAmount=ReadDecimal(reader,11),TaxAmount=ReadDecimal(reader,12),GrossAmount=ReadDecimal(reader,13),CreatedByUserId=reader.GetInt64(14),CreatedAtUtc=ReadDateTimeUtc(reader,15),SubmittedByUserId=reader.IsDBNull(16)?null:reader.GetInt64(16),SubmittedAtUtc=reader.IsDBNull(17)?null:ReadDateTimeUtc(reader,17),ApprovalDecisionByUserId=reader.IsDBNull(18)?null:reader.GetInt64(18),ApprovalDecisionAtUtc=reader.IsDBNull(19)?null:ReadDateTimeUtc(reader,19),ApprovalComment=reader.IsDBNull(20)?null:reader.GetString(20),MatchExceptionApproved=ReadBool(reader,21),MatchExceptionReason=reader.IsDBNull(22)?null:reader.GetString(22),PostedByUserId=reader.IsDBNull(23)?null:reader.GetInt64(23),PostedAtUtc=reader.IsDBNull(24)?null:ReadDateTimeUtc(reader,24),PostingOperationId=reader.IsDBNull(25)?null:Guid.Parse(reader.GetString(25)),OpenItemId=reader.IsDBNull(26)?null:reader.GetInt64(26),JournalEntryId=reader.IsDBNull(27)?null:reader.GetInt64(27),ReversalOperationId=reader.IsDBNull(28)?null:Guid.Parse(reader.GetString(28)),ReversalJournalEntryId=reader.IsDBNull(29)?null:reader.GetInt64(29),ReversedAtUtc=reader.IsDBNull(30)?null:ReadDateTimeUtc(reader,30),ReversedByUserId=reader.IsDBNull(31)?null:reader.GetInt64(31) };
	private static FinanceSupplierDocumentLine ReadLine(DbDataReader reader) => new() { Id=reader.GetInt64(0),DocumentId=reader.GetInt64(1),LineNumber=Convert.ToInt32(reader.GetValue(2),CultureInfo.InvariantCulture),PurchaseOrderLineId=reader.IsDBNull(3)?null:reader.GetInt64(3),GoodsReceiptLineId=reader.IsDBNull(4)?null:reader.GetInt64(4),Description=reader.GetString(5),Quantity=ReadDecimal(reader,6),UnitPrice=ReadDecimal(reader,7),NetAmount=ReadDecimal(reader,8),TaxAmount=ReadDecimal(reader,9),GrossAmount=ReadDecimal(reader,10),MatchStatus=(FinancePayableMatchStatus)Convert.ToInt32(reader.GetValue(11),CultureInfo.InvariantCulture),OrderedUnitPrice=reader.IsDBNull(12)?null:ReadDecimal(reader,12),ReceivedQuantity=reader.IsDBNull(13)?null:ReadDecimal(reader,13),PreviouslyInvoicedQuantity=reader.IsDBNull(14)?null:ReadDecimal(reader,14),QuantityVariance=ReadDecimal(reader,15),PriceVariance=ReadDecimal(reader,16) };
	private static FinancePayableOpenItem ReadOpenItem(DbDataReader reader) => new() { Id=reader.GetInt64(0),Version=Convert.ToInt64(reader.GetValue(1),CultureInfo.InvariantCulture),LegalEntityId=Guid.Parse(reader.GetString(2)),AccountingBookId=Guid.Parse(reader.GetString(3)),SupplierId=reader.GetInt64(4),SupplierName=reader.GetString(5),Kind=(FinancePayableOpenItemKind)Convert.ToInt32(reader.GetValue(6),CultureInfo.InvariantCulture),SourceType=reader.GetString(7),SourceId=reader.GetString(8),SourceReference=reader.IsDBNull(9)?null:reader.GetString(9),DocumentDate=ReadDateOnly(reader,10),DueDate=ReadDateOnly(reader,11),Currency=new CurrencyCode(reader.GetString(12)),OriginalAmount=ReadDecimal(reader,13),RemainingAmount=ReadDecimal(reader,14),JournalEntryId=reader.GetInt64(15),OperationId=Guid.Parse(reader.GetString(16)),IsVoided=ReadBool(reader,17),CreatedAtUtc=ReadDateTimeUtc(reader,18),CreatedByUserId=reader.IsDBNull(19)?null:reader.GetInt64(19) };
	private static FinancePayableAllocation ReadAllocation(DbDataReader reader) => new() { Id=reader.GetInt64(0),OperationId=Guid.Parse(reader.GetString(1)),DebitOpenItemId=reader.GetInt64(2),CreditOpenItemId=reader.GetInt64(3),Amount=ReadDecimal(reader,4),AllocationDate=ReadDateOnly(reader,5),CreatedAtUtc=ReadDateTimeUtc(reader,6),CreatedByUserId=reader.IsDBNull(7)?null:reader.GetInt64(7),ReversedAtUtc=reader.IsDBNull(8)?null:ReadDateTimeUtc(reader,8),ReversedByUserId=reader.IsDBNull(9)?null:reader.GetInt64(9),ReversalOperationId=reader.IsDBNull(10)?null:Guid.Parse(reader.GetString(10)) };
	private static FinancePayablePayment ReadPayment(DbDataReader reader) => new() { Id=reader.GetInt64(0),Version=Convert.ToInt64(reader.GetValue(1),CultureInfo.InvariantCulture),OperationId=Guid.Parse(reader.GetString(2)),RequestHash=reader.GetString(3),SupplierId=reader.GetInt64(4),Currency=new CurrencyCode(reader.GetString(5)),PaymentDate=ReadDateOnly(reader,6),Amount=ReadDecimal(reader,7),Reference=reader.IsDBNull(8)?null:reader.GetString(8),Description=reader.GetString(9),OpenItemId=reader.GetInt64(10),JournalEntryId=reader.GetInt64(11),CreatedAtUtc=ReadDateTimeUtc(reader,12),CreatedByUserId=reader.IsDBNull(13)?null:reader.GetInt64(13),IsReversed=ReadBool(reader,14),ReversalOperationId=reader.IsDBNull(15)?null:Guid.Parse(reader.GetString(15)),ReversalJournalEntryId=reader.IsDBNull(16)?null:reader.GetInt64(16),ReversedAtUtc=reader.IsDBNull(17)?null:ReadDateTimeUtc(reader,17),ReversedByUserId=reader.IsDBNull(18)?null:reader.GetInt64(18) };
	private static bool ReadBool(DbDataReader reader, int ordinal) => Convert.ToBoolean(reader.GetValue(ordinal),CultureInfo.InvariantCulture);
	private static decimal ReadDecimal(DbDataReader reader, int ordinal) => Convert.ToDecimal(reader.GetValue(ordinal),CultureInfo.InvariantCulture);
	private static DateOnly ReadDateOnly(DbDataReader reader, int ordinal) => reader.GetValue(ordinal) is DateTime dt ? DateOnly.FromDateTime(dt) : DateOnly.Parse(Convert.ToString(reader.GetValue(ordinal),CultureInfo.InvariantCulture) ?? string.Empty,CultureInfo.InvariantCulture);
	private static DateTime ReadDateTimeUtc(DbDataReader reader, int ordinal) => reader.GetValue(ordinal) is DateTime dt ? DateTime.SpecifyKind(dt,DateTimeKind.Utc) : DateTime.Parse(Convert.ToString(reader.GetValue(ordinal),CultureInfo.InvariantCulture) ?? string.Empty,CultureInfo.InvariantCulture,DateTimeStyles.RoundtripKind).ToUniversalTime();
}

internal sealed record FinancePurchaseMatchReference(long SupplierId, decimal OrderedUnitPrice, decimal OrderedQuantity, decimal ReceivedQuantity);
internal sealed record FinanceAllocationOperationRecord(Guid OperationId, string RequestHash, long DebitOpenItemId);
public sealed record FinancePayableAgingRow(long SupplierId, string SupplierName, CurrencyCode Currency, DateOnly DueDate, decimal RemainingAmount, FinancePayableOpenItemKind Kind);
