// Copyright (c) 2026 David Beusing
// Licensed under the MIT License.

using System.Data.Common;
using System.Globalization;
using Depot.Data;
using Depot.Models;

namespace Depot.Repositories;

public sealed class SubscriptionBillingRepository : DatabaseRepository
{
	private const string ContractColumns="sc.Id,sc.Version,sc.TermsRevision,sc.ContractNumber,sc.CustomerId,c.Name,sc.LegalEntityId,sc.Currency,sc.StartDate,sc.EndDate,sc.Cadence,sc.NextBillingDate,sc.Status,sc.StatusEffectiveDate,sc.OwnerUserId,sc.Notes,sc.CreatedAtUtc,sc.CreatedByUserId,sc.UpdatedAtUtc,sc.UpdatedByUserId";
	private const string ContractFrom="FROM SubscriptionContracts sc INNER JOIN Customers c ON c.Id=sc.CustomerId";
	private const string InstanceColumns="bi.Id,bi.Version,bi.ContractId,sc.ContractNumber,bi.TermsRevision,bi.PeriodStart,bi.PeriodEnd,bi.BillingDate,bi.Status,bi.SalesInvoiceId,si.InvoiceNumber,bi.BlockReason,bi.CreatedAtUtc,bi.GeneratedAtUtc,bi.GeneratedByUserId";
	private const string InstanceFrom="FROM SubscriptionBillingInstances bi INNER JOIN SubscriptionContracts sc ON sc.Id=bi.ContractId LEFT JOIN SalesInvoices si ON si.Id=bi.SalesInvoiceId";

	public SubscriptionBillingRepository(DatabaseAccess database):base(database){}

	public Task<PageResult<SubscriptionContract>> SearchContractsAsync(string? searchText,SubscriptionContractStatus? status,int pageNumber,int pageSize,CancellationToken token)
	{
		var filters=new List<string>();var parameters=new List<DatabaseParameter>();var plan=SearchQueryPlan.Create(searchText);string? rank=null;
		if(plan is{} search){var columns=new[]{"sc.ContractNumber","c.Name"};filters.Add(search.BuildPredicate(columns,columns));parameters.Add(Parameter("$SearchExact",search.Exact));parameters.Add(Parameter("$SearchPrefix",search.Prefix));if(search.AllowContains){parameters.Add(Parameter("$SearchWordPrefix",search.WordPrefix));parameters.Add(Parameter("$SearchContains",search.Contains));}rank=search.BuildRankExpression(columns,["c.Name"]);}
		if(status is not null){filters.Add("sc.Status=$Status");parameters.Add(Parameter("$Status",(int)status.Value));}
		var where=filters.Count==0?string.Empty:$"WHERE {string.Join(" AND ",filters)}";var order=rank is null?"sc.ContractNumber DESC":$"{rank},sc.ContractNumber DESC";
		return Database.QueryPageAsync($"SELECT {ContractColumns} {ContractFrom} {where} ORDER BY {order}",$"SELECT COUNT(*) {ContractFrom} {where}",ReadContract,pageNumber,pageSize,token,parameters.ToArray());
	}

	public async Task<SubscriptionContract?> GetContractAsync(long id,CancellationToken token){var value=await Database.QuerySingleOrDefaultAsync($"SELECT {ContractColumns} {ContractFrom} WHERE sc.Id=$Id;",ReadContract,token,Parameter("$Id",id));if(value is null)return null;return value with{Lines=await ListLinesAsync(id,value.TermsRevision,token)};}
	public async Task<SubscriptionContract?> GetContractAsync(DatabaseTransactionContext tx,long id,CancellationToken token){var value=await tx.Session.QuerySingleOrDefaultAsync($"SELECT {ContractColumns} {ContractFrom} WHERE sc.Id=$Id;",ReadContract,token,Parameter("$Id",id));if(value is null)return null;return value with{Lines=await ListLinesAsync(tx,id,value.TermsRevision,token)};}
	public Task<IReadOnlyList<SubscriptionContract>> ListDueContractsAsync(DateOnly asOf,int count,CancellationToken token)=>Database.QuerySliceAsync($"SELECT {ContractColumns} {ContractFrom} WHERE sc.Status=$Active AND sc.NextBillingDate<=$AsOf ORDER BY sc.NextBillingDate,sc.Id",ReadContract,0,Math.Clamp(count,1,500),token,Parameter("$Active",(int)SubscriptionContractStatus.Active),Parameter("$AsOf",D(asOf)));
	public Task<IReadOnlyList<SubscriptionContractLine>> ListLinesAsync(long contractId,int termsRevision,CancellationToken token)=>Database.QueryAsync(LineSql+" WHERE ContractId=$ContractId AND TermsRevision=$Revision ORDER BY LineNumber;",ReadLine,token,Parameter("$ContractId",contractId),Parameter("$Revision",termsRevision));
	public Task<IReadOnlyList<SubscriptionContractLine>> ListLinesAsync(DatabaseTransactionContext tx,long contractId,int termsRevision,CancellationToken token)=>tx.Session.QueryAsync(LineSql+" WHERE ContractId=$ContractId AND TermsRevision=$Revision ORDER BY LineNumber;",ReadLine,token,Parameter("$ContractId",contractId),Parameter("$Revision",termsRevision));

	public async Task<long> CreateContractAsync(DatabaseTransactionContext tx,SubscriptionContract value,CancellationToken token)
	{
		var pending=$"PENDING-{Guid.NewGuid():N}";
		var id=await tx.Session.InsertAsync("INSERT INTO SubscriptionContracts (Version,TermsRevision,ContractNumber,CustomerId,LegalEntityId,Currency,StartDate,EndDate,Cadence,NextBillingDate,Status,StatusEffectiveDate,OwnerUserId,Notes,CreatedAtUtc,CreatedByUserId,UpdatedAtUtc,UpdatedByUserId) VALUES (1,1,$Number,$Customer,$Entity,$Currency,$Start,$End,$Cadence,$Next,$Status,$StatusDate,$Owner,$Notes,$Created,$CreatedBy,$Updated,$UpdatedBy);",token,Parameter("$Number",pending),Parameter("$Customer",value.CustomerId),Parameter("$Entity",value.LegalEntityId.ToString("D")),Parameter("$Currency",value.Currency),Parameter("$Start",D(value.StartDate)),Parameter("$End",value.EndDate is null?null:D(value.EndDate.Value)),Parameter("$Cadence",(int)value.Cadence),Parameter("$Next",D(value.NextBillingDate)),Parameter("$Status",(int)value.Status),Parameter("$StatusDate",D(value.StatusEffectiveDate)),Parameter("$Owner",value.OwnerUserId),Parameter("$Notes",value.Notes),Parameter("$Created",T(value.CreatedAtUtc)),Parameter("$CreatedBy",value.CreatedByUserId),Parameter("$Updated",T(value.UpdatedAtUtc)),Parameter("$UpdatedBy",value.UpdatedByUserId));
		await tx.Session.ExecuteAsync("UPDATE SubscriptionContracts SET ContractNumber=$Number WHERE Id=$Id;",token,Parameter("$Number",$"SUB-{id:000000}"),Parameter("$Id",id));
		await InsertLinesAsync(tx,id,1,value.Lines,token);return id;
	}

	public async Task<bool> UpdateTermsAsync(DatabaseTransactionContext tx,SubscriptionContract value,long expectedVersion,int newTermsRevision,long userId,DateTime at,CancellationToken token)
	{
		var changed=await tx.Session.ExecuteAsync("UPDATE SubscriptionContracts SET Version=Version+1,TermsRevision=$TermsRevision,Currency=$Currency,EndDate=$End,Cadence=$Cadence,Notes=$Notes,UpdatedAtUtc=$Updated,UpdatedByUserId=$UpdatedBy WHERE Id=$Id AND Version=$Version;",token,Parameter("$TermsRevision",newTermsRevision),Parameter("$Currency",value.Currency),Parameter("$End",value.EndDate is null?null:D(value.EndDate.Value)),Parameter("$Cadence",(int)value.Cadence),Parameter("$Notes",value.Notes),Parameter("$Updated",T(at)),Parameter("$UpdatedBy",userId),Parameter("$Id",value.Id),Parameter("$Version",expectedVersion));
		if(changed==1)await InsertLinesAsync(tx,value.Id,newTermsRevision,value.Lines,token);return changed==1;
	}

	public Task<int> SetLifecycleAsync(DatabaseTransactionContext tx,long id,long expectedVersion,SubscriptionContractStatus status,DateOnly effectiveDate,long userId,DateTime at,CancellationToken token)=>tx.Session.ExecuteAsync("UPDATE SubscriptionContracts SET Version=Version+1,Status=$Status,StatusEffectiveDate=$Effective,UpdatedAtUtc=$Updated,UpdatedByUserId=$User WHERE Id=$Id AND Version=$Version;",token,Parameter("$Status",(int)status),Parameter("$Effective",D(effectiveDate)),Parameter("$Updated",T(at)),Parameter("$User",userId),Parameter("$Id",id),Parameter("$Version",expectedVersion));
	public Task<int> AdvanceNextBillingDateAsync(DatabaseTransactionContext tx,long id,long expectedVersion,DateOnly expectedDate,DateOnly nextDate,long userId,DateTime at,CancellationToken token)=>tx.Session.ExecuteAsync("UPDATE SubscriptionContracts SET Version=Version+1,NextBillingDate=$Next,UpdatedAtUtc=$Updated,UpdatedByUserId=$User WHERE Id=$Id AND Version=$Version AND NextBillingDate=$Expected;",token,Parameter("$Next",D(nextDate)),Parameter("$Updated",T(at)),Parameter("$User",userId),Parameter("$Id",id),Parameter("$Version",expectedVersion),Parameter("$Expected",D(expectedDate)));
	public Task<int> InsertRevisionAsync(DatabaseTransactionContext tx,SubscriptionContractRevision revision,CancellationToken token)=>tx.Session.ExecuteAsync("INSERT INTO SubscriptionContractRevisions (ContractId,TermsRevision,EffectiveFrom,TermsSnapshotJson,CreatedAtUtc,CreatedByUserId) VALUES ($Contract,$Revision,$Effective,$Snapshot,$At,$User);",token,Parameter("$Contract",revision.ContractId),Parameter("$Revision",revision.TermsRevision),Parameter("$Effective",D(revision.EffectiveFrom)),Parameter("$Snapshot",revision.TermsSnapshotJson),Parameter("$At",T(revision.CreatedAtUtc)),Parameter("$User",revision.CreatedByUserId));
	public Task<int> InsertLifecycleEventAsync(DatabaseTransactionContext tx,SubscriptionLifecycleEvent value,CancellationToken token)=>tx.Session.ExecuteAsync("INSERT INTO SubscriptionLifecycleEvents (ContractId,Action,EffectiveDate,PreviousStatus,NewStatus,Comment,CreatedAtUtc,CreatedByUserId) VALUES ($Contract,$Action,$Effective,$Previous,$New,$Comment,$At,$User);",token,Parameter("$Contract",value.ContractId),Parameter("$Action",value.Action),Parameter("$Effective",D(value.EffectiveDate)),Parameter("$Previous",(int)value.PreviousStatus),Parameter("$New",(int)value.NewStatus),Parameter("$Comment",value.Comment),Parameter("$At",T(value.CreatedAtUtc)),Parameter("$User",value.CreatedByUserId));
	public async Task<DateOnly?> GetLatestGeneratedPeriodEndAsync(DatabaseTransactionContext tx,long contractId,CancellationToken token){var value=await tx.Session.ExecuteScalarAsync("SELECT MAX(PeriodEnd) FROM SubscriptionBillingInstances WHERE ContractId=$Contract AND Status=$Generated;",token,Parameter("$Contract",contractId),Parameter("$Generated",(int)SubscriptionBillingInstanceStatus.Generated));return value is null or DBNull?null:DateOnly.FromDateTime(Convert.ToDateTime(value,CultureInfo.InvariantCulture));}

	public Task<IReadOnlyList<SubscriptionBillingInstance>> ListBillingInstancesAsync(long contractId,int count,CancellationToken token)=>Database.QuerySliceAsync($"SELECT {InstanceColumns} {InstanceFrom} WHERE bi.ContractId=$Contract ORDER BY bi.PeriodStart DESC,bi.Id DESC",ReadInstance,0,Math.Clamp(count,1,500),token,Parameter("$Contract",contractId));
	public Task<IReadOnlyList<SubscriptionBillingInstance>> ListDueBillingInstancesAsync(DateOnly asOf,int count,CancellationToken token)=>Database.QuerySliceAsync($"SELECT {InstanceColumns} {InstanceFrom} WHERE bi.Status IN ($Due,$Blocked) AND bi.BillingDate<=$AsOf ORDER BY bi.BillingDate,bi.Id",ReadInstance,0,Math.Clamp(count,1,500),token,Parameter("$Due",(int)SubscriptionBillingInstanceStatus.Due),Parameter("$Blocked",(int)SubscriptionBillingInstanceStatus.Blocked),Parameter("$AsOf",D(asOf)));
	public Task<SubscriptionBillingInstance?> GetBillingInstanceAsync(long id,CancellationToken token)=>Database.QuerySingleOrDefaultAsync($"SELECT {InstanceColumns} {InstanceFrom} WHERE bi.Id=$Id;",ReadInstance,token,Parameter("$Id",id));
	public Task<SubscriptionBillingInstance?> GetBillingInstanceAsync(DatabaseTransactionContext tx,long id,CancellationToken token)=>tx.Session.QuerySingleOrDefaultAsync($"SELECT {InstanceColumns} {InstanceFrom} WHERE bi.Id=$Id;",ReadInstance,token,Parameter("$Id",id));
	public Task<SubscriptionBillingInstance?> FindBillingInstanceAsync(DatabaseTransactionContext tx,long contractId,DateOnly periodStart,CancellationToken token)=>tx.Session.QuerySingleOrDefaultAsync($"SELECT {InstanceColumns} {InstanceFrom} WHERE bi.ContractId=$Contract AND bi.PeriodStart=$Start;",ReadInstance,token,Parameter("$Contract",contractId),Parameter("$Start",D(periodStart)));
	public Task<long> CreateBillingInstanceAsync(DatabaseTransactionContext tx,SubscriptionBillingInstance value,CancellationToken token)=>tx.Session.InsertAsync("INSERT INTO SubscriptionBillingInstances (Version,ContractId,TermsRevision,PeriodStart,PeriodEnd,BillingDate,Status,SalesInvoiceId,BlockReason,CreatedAtUtc,GeneratedAtUtc,GeneratedByUserId) VALUES (1,$Contract,$TermsRevision,$Start,$End,$Billing,$Status,NULL,NULL,$Created,NULL,NULL);",token,Parameter("$Contract",value.ContractId),Parameter("$TermsRevision",value.TermsRevision),Parameter("$Start",D(value.PeriodStart)),Parameter("$End",D(value.PeriodEnd)),Parameter("$Billing",D(value.BillingDate)),Parameter("$Status",(int)value.Status),Parameter("$Created",T(value.CreatedAtUtc)));
	public Task<int> TryClaimBillingInstanceAsync(DatabaseTransactionContext tx,long id,long version,CancellationToken token)=>tx.Session.ExecuteAsync("UPDATE SubscriptionBillingInstances SET Version=Version+1,Status=$Generating,BlockReason=NULL WHERE Id=$Id AND Version=$Version AND Status IN ($Due,$Blocked) AND SalesInvoiceId IS NULL;",token,Parameter("$Generating",(int)SubscriptionBillingInstanceStatus.Generating),Parameter("$Id",id),Parameter("$Version",version),Parameter("$Due",(int)SubscriptionBillingInstanceStatus.Due),Parameter("$Blocked",(int)SubscriptionBillingInstanceStatus.Blocked));
	public Task<int> MarkBillingGeneratedAsync(DatabaseTransactionContext tx,long id,long version,long invoiceId,long userId,DateTime at,CancellationToken token)=>tx.Session.ExecuteAsync("UPDATE SubscriptionBillingInstances SET Version=Version+1,Status=$Generated,SalesInvoiceId=$Invoice,BlockReason=NULL,GeneratedAtUtc=$At,GeneratedByUserId=$User WHERE Id=$Id AND Version=$Version AND Status=$Generating;",token,Parameter("$Generated",(int)SubscriptionBillingInstanceStatus.Generated),Parameter("$Invoice",invoiceId),Parameter("$At",T(at)),Parameter("$User",userId),Parameter("$Id",id),Parameter("$Version",version),Parameter("$Generating",(int)SubscriptionBillingInstanceStatus.Generating));
	public Task<int> MarkBillingBlockedAsync(DatabaseTransactionContext tx,long id,long version,string reason,CancellationToken token)=>tx.Session.ExecuteAsync("UPDATE SubscriptionBillingInstances SET Version=Version+1,Status=$Blocked,BlockReason=$Reason WHERE Id=$Id AND Version=$Version AND Status=$Generating;",token,Parameter("$Blocked",(int)SubscriptionBillingInstanceStatus.Blocked),Parameter("$Reason",reason),Parameter("$Id",id),Parameter("$Version",version),Parameter("$Generating",(int)SubscriptionBillingInstanceStatus.Generating));
	public Task<int> InsertPriceEvidenceAsync(DatabaseTransactionContext tx,SubscriptionBillingPriceEvidence value,CancellationToken token)=>tx.Session.ExecuteAsync("INSERT INTO SubscriptionBillingPriceEvidence (BillingInstanceId,ContractLineId,LineNumber,UnitPrice,DiscountPercent,PriceSourceListId,PriceSourceName,PriceSourceScope,PriceSourceCurrency,ResolvedAtUtc) VALUES ($Instance,$Line,$LineNumber,$Price,$Discount,$List,$Name,$Scope,$Currency,$At);",token,Parameter("$Instance",value.BillingInstanceId),Parameter("$Line",value.ContractLineId),Parameter("$LineNumber",value.LineNumber),Parameter("$Price",value.UnitPrice),Parameter("$Discount",value.DiscountPercent),Parameter("$List",value.PriceSourceListId),Parameter("$Name",value.PriceSourceName),Parameter("$Scope",value.PriceSourceScope is null?null:(int)value.PriceSourceScope.Value),Parameter("$Currency",value.PriceSourceCurrency),Parameter("$At",T(value.ResolvedAtUtc)));

	private static async Task InsertLinesAsync(DatabaseTransactionContext tx,long contractId,int revision,IReadOnlyList<SubscriptionContractLine> lines,CancellationToken token){var number=1;foreach(var line in lines)await tx.Session.InsertAsync("INSERT INTO SubscriptionContractLines (ContractId,TermsRevision,LineNumber,ItemId,PartNumber,Description,Quantity,UnitPrice,DiscountPercent,TaxRate,PricePolicy,PriceSourceListId,PriceSourceName,PriceSourceScope,PriceSourceCurrency) VALUES ($Contract,$Revision,$LineNumber,$Item,$Part,$Description,$Quantity,$Price,$Discount,$Tax,$Policy,$List,$Name,$Scope,$Currency);",token,Parameter("$Contract",contractId),Parameter("$Revision",revision),Parameter("$LineNumber",number++),Parameter("$Item",line.ItemId),Parameter("$Part",line.PartNumber),Parameter("$Description",line.Description),Parameter("$Quantity",line.Quantity),Parameter("$Price",line.UnitPrice),Parameter("$Discount",line.DiscountPercent),Parameter("$Tax",line.TaxRate),Parameter("$Policy",(int)line.PricePolicy),Parameter("$List",line.PriceSourceListId),Parameter("$Name",line.PriceSourceName),Parameter("$Scope",line.PriceSourceScope is null?null:(int)line.PriceSourceScope.Value),Parameter("$Currency",line.PriceSourceCurrency));}
	private const string LineSql="SELECT Id,ContractId,TermsRevision,LineNumber,ItemId,PartNumber,Description,Quantity,UnitPrice,DiscountPercent,TaxRate,PricePolicy,PriceSourceListId,PriceSourceName,PriceSourceScope,PriceSourceCurrency FROM SubscriptionContractLines";
	private static SubscriptionContract ReadContract(DbDataReader r)=>new(){Id=r.GetInt64(0),Version=r.GetInt64(1),TermsRevision=r.GetInt32(2),ContractNumber=r.GetString(3),CustomerId=r.GetInt64(4),CustomerName=r.GetString(5),LegalEntityId=Guid.Parse(r.GetString(6)),Currency=r.GetString(7),StartDate=DO(r,8),EndDate=r.IsDBNull(9)?null:DO(r,9),Cadence=(SubscriptionBillingCadence)r.GetInt32(10),NextBillingDate=DO(r,11),Status=(SubscriptionContractStatus)r.GetInt32(12),StatusEffectiveDate=DO(r,13),OwnerUserId=r.GetInt64(14),Notes=r.IsDBNull(15)?null:r.GetString(15),CreatedAtUtc=DT(r,16),CreatedByUserId=r.GetInt64(17),UpdatedAtUtc=DT(r,18),UpdatedByUserId=r.GetInt64(19)};
	private static SubscriptionContractLine ReadLine(DbDataReader r)=>new(){Id=r.GetInt64(0),ContractId=r.GetInt64(1),TermsRevision=r.GetInt32(2),LineNumber=r.GetInt32(3),ItemId=r.GetInt64(4),PartNumber=r.GetString(5),Description=r.GetString(6),Quantity=r.GetInt32(7),UnitPrice=Convert.ToDecimal(r.GetValue(8),CultureInfo.InvariantCulture),DiscountPercent=Convert.ToDecimal(r.GetValue(9),CultureInfo.InvariantCulture),TaxRate=Convert.ToDecimal(r.GetValue(10),CultureInfo.InvariantCulture),PricePolicy=(SubscriptionPricePolicy)r.GetInt32(11),PriceSourceListId=r.IsDBNull(12)?null:r.GetInt64(12),PriceSourceName=r.IsDBNull(13)?null:r.GetString(13),PriceSourceScope=r.IsDBNull(14)?null:(SalesPriceListScope)r.GetInt32(14),PriceSourceCurrency=r.IsDBNull(15)?null:r.GetString(15)};
	private static SubscriptionBillingInstance ReadInstance(DbDataReader r)=>new(){Id=r.GetInt64(0),Version=r.GetInt64(1),ContractId=r.GetInt64(2),ContractNumber=r.GetString(3),TermsRevision=r.GetInt32(4),PeriodStart=DO(r,5),PeriodEnd=DO(r,6),BillingDate=DO(r,7),Status=(SubscriptionBillingInstanceStatus)r.GetInt32(8),SalesInvoiceId=r.IsDBNull(9)?null:r.GetInt64(9),SalesInvoiceNumber=r.IsDBNull(10)?null:r.GetString(10),BlockReason=r.IsDBNull(11)?null:r.GetString(11),CreatedAtUtc=DT(r,12),GeneratedAtUtc=r.IsDBNull(13)?null:DT(r,13),GeneratedByUserId=r.IsDBNull(14)?null:r.GetInt64(14)};
	private static string D(DateOnly v)=>v.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture);private static string T(DateTime v)=>v.ToUniversalTime().ToString("O",CultureInfo.InvariantCulture);private static DateOnly DO(DbDataReader r,int i)=>DateOnly.FromDateTime(Convert.ToDateTime(r.GetValue(i),CultureInfo.InvariantCulture));private static DateTime DT(DbDataReader r,int i)=>Convert.ToDateTime(r.GetValue(i),CultureInfo.InvariantCulture);
}
