// Copyright (c) 2026 David Beusing
// Licensed under the MIT License.

using System.Data.Common;
using System.Globalization;

using Depot.Data;
using Depot.Models;

namespace Depot.Repositories;

public sealed class SupplierReturnRepository : DatabaseRepository
{
    private const string HeaderColumns = "sr.Id, sr.ReturnNumber, sr.SupplierId, s.Name, sr.ReturnDate, sr.Status, sr.PurchaseOrderId, po.OrderNumber, sr.GoodsReceiptId, gr.ReceiptNumber, sr.SupplierReference, sr.Notes, sr.CreatedByUserId, sr.PostedByUserId, sr.PostedAtUtc, sr.ReversedByUserId, sr.ReversedAtUtc, sr.ReversalReason, sr.Version";
    private const string HeaderFrom = "FROM SupplierReturns sr INNER JOIN Suppliers s ON s.Id = sr.SupplierId INNER JOIN PurchaseOrders po ON po.Id = sr.PurchaseOrderId INNER JOIN GoodsReceipts gr ON gr.Id = sr.GoodsReceiptId";
    private const string LineColumns = "srl.Id, srl.SupplierReturnId, srl.InventoryId, srl.ItemId, srl.Quantity, srl.UnitCost, srl.ReasonCodeId, srl.GoodsReceiptLineId, srl.Version, i.PartNumber, i.Description, w.Name, sl.Name, p.Name, rc.Name, grl.Quantity";

    public SupplierReturnRepository(DatabaseAccess database) : base(database) { }

    public Task<PageResult<SupplierReturnOverviewItem>> SearchAsync(string? searchText, long? supplierId, SupplierReturnStatus? status, int pageNumber, int pageSize, CancellationToken cancellationToken)
    {
        var filters = new List<string>(); var parameters = new List<DatabaseParameter>();
        if (!string.IsNullOrWhiteSpace(searchText)) { filters.Add("(sr.ReturnNumber LIKE $Search OR s.Name LIKE $Search OR po.OrderNumber LIKE $Search OR gr.ReceiptNumber LIKE $Search OR sr.SupplierReference LIKE $Search)"); parameters.Add(Parameter("$Search", $"%{searchText.Trim()}%")); }
        if (supplierId is not null) { filters.Add("sr.SupplierId = $SupplierId"); parameters.Add(Parameter("$SupplierId", supplierId.Value)); }
        if (status is not null) { filters.Add("sr.Status = $Status"); parameters.Add(Parameter("$Status", (int)status.Value)); }
        var where = filters.Count == 0 ? string.Empty : $"WHERE {string.Join(" AND ", filters)}";
		return Database.QueryPageAsync($"SELECT sr.Id, sr.ReturnNumber, sr.SupplierId, s.Name, sr.ReturnDate, sr.Status, po.OrderNumber, gr.ReceiptNumber, sr.SupplierReference, (SELECT COUNT(*) FROM SupplierReturnLines srl WHERE srl.SupplierReturnId = sr.Id), sr.Version, CASE WHEN sr.ReversedAtUtc IS NULL THEN 0 ELSE 1 END {HeaderFrom} {where} ORDER BY sr.ReturnDate DESC, sr.Id DESC", $"SELECT COUNT(*) {HeaderFrom} {where}", ReadOverview, pageNumber, pageSize, cancellationToken, parameters.ToArray());
    }

	public Task<SupplierReturnOverviewItem?> GetOverviewByIdAsync(long id, CancellationToken cancellationToken) => Database.QuerySingleOrDefaultAsync($"SELECT sr.Id, sr.ReturnNumber, sr.SupplierId, s.Name, sr.ReturnDate, sr.Status, po.OrderNumber, gr.ReceiptNumber, sr.SupplierReference, (SELECT COUNT(*) FROM SupplierReturnLines srl WHERE srl.SupplierReturnId = sr.Id), sr.Version, CASE WHEN sr.ReversedAtUtc IS NULL THEN 0 ELSE 1 END {HeaderFrom} WHERE sr.Id = $Id;", ReadOverview, cancellationToken, Parameter("$Id", id));

    public Task<IReadOnlyList<SupplierReturnReceiptOption>> SearchReceiptOptionsAsync(string? searchText, long? supplierId, CancellationToken cancellationToken)
    {
        var filters = new List<string> { "gr.ReversedAtUtc IS NULL" }; var parameters = new List<DatabaseParameter>();
        if (!string.IsNullOrWhiteSpace(searchText)) { filters.Add("(gr.ReceiptNumber LIKE $Search OR po.OrderNumber LIKE $Search OR s.Name LIKE $Search OR gr.SupplierDeliveryNoteNumber LIKE $Search)"); parameters.Add(Parameter("$Search", $"%{searchText.Trim()}%")); }
        if (supplierId is not null) { filters.Add("po.SupplierId = $SupplierId"); parameters.Add(Parameter("$SupplierId", supplierId.Value)); }
        return Database.QuerySliceAsync($"SELECT gr.Id, gr.ReceiptNumber, gr.ReceiptDate, po.Id, po.OrderNumber, s.Id, s.Name FROM GoodsReceipts gr INNER JOIN PurchaseOrders po ON po.Id = gr.PurchaseOrderId INNER JOIN Suppliers s ON s.Id = po.SupplierId WHERE {string.Join(" AND ", filters)} ORDER BY gr.ReceiptDate DESC, gr.Id DESC", ReadReceiptOption, 0, 100, cancellationToken, parameters.ToArray());
    }

    public Task<IReadOnlyList<SupplierReturnableLine>> ListReturnableLinesAsync(long goodsReceiptId, CancellationToken cancellationToken) => Database.QueryAsync(ReturnableLineSql, ReadReturnable, cancellationToken, Parameter("$GoodsReceiptId", goodsReceiptId), Parameter("$Posted", (int)SupplierReturnStatus.Posted));
    public Task<IReadOnlyList<SupplierReturnableLine>> ListReturnableLinesAsync(DatabaseTransactionContext transaction, long goodsReceiptId, CancellationToken cancellationToken) => transaction.Session.QueryAsync(ReturnableLineSql, ReadReturnable, cancellationToken, Parameter("$GoodsReceiptId", goodsReceiptId), Parameter("$Posted", (int)SupplierReturnStatus.Posted));

    public async Task<SupplierReturn?> GetByIdAsync(long id, CancellationToken cancellationToken) { var value = await Database.QuerySingleOrDefaultAsync($"SELECT {HeaderColumns} {HeaderFrom} WHERE sr.Id = $Id;", ReadHeader, cancellationToken, Parameter("$Id", id)); if (value is not null) value.Lines = await ListLinesAsync(id, cancellationToken); return value; }
    public async Task<SupplierReturn?> GetByIdAsync(DatabaseTransactionContext transaction, long id, CancellationToken cancellationToken) { if (await transaction.Session.ExecuteScalarAsync(Database.SupplierReturnLockSql, cancellationToken, Parameter("$SupplierReturnId", id)) is null) return null; var value = await transaction.Session.QuerySingleOrDefaultAsync($"SELECT {HeaderColumns} {HeaderFrom} WHERE sr.Id = $Id;", ReadHeader, cancellationToken, Parameter("$Id", id)); if (value is not null) value.Lines = await ListLinesAsync(transaction.Session, id, cancellationToken); return value; }
    public Task<IReadOnlyList<SupplierReturnLine>> ListLinesAsync(long id, CancellationToken cancellationToken) => Database.QueryAsync(LineSql, ReadLine, cancellationToken, Parameter("$SupplierReturnId", id), Parameter("$Posted", (int)SupplierReturnStatus.Posted));

    public Task<long> CreateAsync(DatabaseTransactionContext transaction, SupplierReturn value, CancellationToken cancellationToken) => transaction.Session.InsertAsync("INSERT INTO SupplierReturns (ReturnNumber, SupplierId, ReturnDate, Status, PurchaseOrderId, GoodsReceiptId, SupplierReference, Notes, CreatedByUserId) VALUES ($ReturnNumber, $SupplierId, $ReturnDate, $Status, $PurchaseOrderId, $GoodsReceiptId, $SupplierReference, $Notes, $CreatedByUserId);", cancellationToken, HeaderParameters(value));
    public Task<int> UpdateNumberAsync(DatabaseTransactionContext transaction, long id, string number, CancellationToken cancellationToken) => transaction.Session.ExecuteAsync("UPDATE SupplierReturns SET ReturnNumber = $ReturnNumber WHERE Id = $Id;", cancellationToken, Parameter("$ReturnNumber", number), Parameter("$Id", id));
    public async Task<bool> UpdateDraftAsync(DatabaseTransactionContext transaction, SupplierReturn value, CancellationToken cancellationToken) => await transaction.Session.ExecuteAsync("UPDATE SupplierReturns SET SupplierId = $SupplierId, ReturnDate = $ReturnDate, PurchaseOrderId = $PurchaseOrderId, GoodsReceiptId = $GoodsReceiptId, SupplierReference = $SupplierReference, Notes = $Notes, Version = Version + 1 WHERE Id = $Id AND Version = $Version AND Status = $Draft;", cancellationToken, Parameter("$SupplierId", value.SupplierId), Parameter("$ReturnDate", Date(value.ReturnDate)), Parameter("$PurchaseOrderId", value.PurchaseOrderId), Parameter("$GoodsReceiptId", value.GoodsReceiptId), Parameter("$SupplierReference", value.SupplierReference), Parameter("$Notes", value.Notes), Parameter("$Id", value.Id), Parameter("$Version", value.Version), Parameter("$Draft", (int)SupplierReturnStatus.Draft)) == 1;
    public Task<int> DeleteLinesAsync(DatabaseTransactionContext transaction, long id, IReadOnlyList<long> lineIds, CancellationToken cancellationToken) { if (lineIds.Count == 0) return Task.FromResult(0); var parameters = lineIds.Select((lineId, index) => Parameter($"$LineId{index}", lineId)).ToArray(); return transaction.Session.ExecuteAsync($"DELETE FROM SupplierReturnLines WHERE SupplierReturnId = $SupplierReturnId AND Id IN ({string.Join(", ", parameters.Select(parameter => parameter.Name))});", cancellationToken, [.. parameters, Parameter("$SupplierReturnId", id)]); }
    public Task<long> CreateLineAsync(DatabaseTransactionContext transaction, SupplierReturnLine line, CancellationToken cancellationToken) => transaction.Session.InsertAsync("INSERT INTO SupplierReturnLines (SupplierReturnId, InventoryId, ItemId, Quantity, UnitCost, ReasonCodeId, GoodsReceiptLineId) VALUES ($SupplierReturnId, $InventoryId, $ItemId, $Quantity, $UnitCost, $ReasonCodeId, $GoodsReceiptLineId);", cancellationToken, LineParameters(line));
    public async Task<bool> UpdateLineAsync(DatabaseTransactionContext transaction, SupplierReturnLine line, CancellationToken cancellationToken) => await transaction.Session.ExecuteAsync("UPDATE SupplierReturnLines SET InventoryId = $InventoryId, ItemId = $ItemId, Quantity = $Quantity, UnitCost = $UnitCost, ReasonCodeId = $ReasonCodeId, GoodsReceiptLineId = $GoodsReceiptLineId, Version = Version + 1 WHERE Id = $Id AND SupplierReturnId = $SupplierReturnId AND Version = $Version;", cancellationToken, [.. LineParameters(line), Parameter("$Id", line.Id), Parameter("$Version", line.Version)]) == 1;
    public async Task<bool> SetPostedAsync(DatabaseTransactionContext transaction, long id, long version, long userId, DateTime atUtc, CancellationToken cancellationToken) => await transaction.Session.ExecuteAsync("UPDATE SupplierReturns SET Status = $Posted, PostedByUserId = $UserId, PostedAtUtc = $AtUtc, Version = Version + 1 WHERE Id = $Id AND Version = $Version AND Status = $Draft;", cancellationToken, Parameter("$Posted", (int)SupplierReturnStatus.Posted), Parameter("$UserId", userId), Parameter("$AtUtc", DateTimeValue(atUtc)), Parameter("$Id", id), Parameter("$Version", version), Parameter("$Draft", (int)SupplierReturnStatus.Draft)) == 1;
    public async Task<bool> CancelAsync(DatabaseTransactionContext transaction, long id, long version, CancellationToken cancellationToken) => await transaction.Session.ExecuteAsync("UPDATE SupplierReturns SET Status = $Cancelled, Version = Version + 1 WHERE Id = $Id AND Version = $Version AND Status = $Draft;", cancellationToken, Parameter("$Cancelled", (int)SupplierReturnStatus.Cancelled), Parameter("$Id", id), Parameter("$Version", version), Parameter("$Draft", (int)SupplierReturnStatus.Draft)) == 1;
    public async Task<bool> MarkReversedAsync(DatabaseTransactionContext transaction, long id, long version, long userId, DateTime reversedAtUtc, string reason, CancellationToken cancellationToken) => await transaction.Session.ExecuteAsync("UPDATE SupplierReturns SET ReversedByUserId = $UserId, ReversedAtUtc = $ReversedAtUtc, ReversalReason = $Reason, Version = Version + 1 WHERE Id = $Id AND Version = $Version AND Status = $Posted AND ReversedAtUtc IS NULL;", cancellationToken, Parameter("$UserId", userId), Parameter("$ReversedAtUtc", DateTimeValue(reversedAtUtc)), Parameter("$Reason", reason), Parameter("$Id", id), Parameter("$Version", version), Parameter("$Posted", (int)SupplierReturnStatus.Posted)) == 1;

    private string ReturnableLineSql => $"SELECT grl.Id, grl.InventoryId, pol.ItemId, i.PartNumber, i.Description, w.Name, sl.Name, p.Name, grl.Quantity, COALESCE((SELECT SUM({Database.CastToInt64("srl.Quantity")}) FROM SupplierReturnLines srl INNER JOIN SupplierReturns sr ON sr.Id = srl.SupplierReturnId WHERE srl.GoodsReceiptLineId = grl.Id AND sr.Status = $Posted AND sr.ReversedAtUtc IS NULL), 0), COALESCE((SELECT SUM({Database.CastToInt64("sm.Quantity")}) FROM StockMovements sm WHERE sm.InventoryId = grl.InventoryId), 0), pol.UnitPrice FROM GoodsReceiptLines grl INNER JOIN PurchaseOrderLines pol ON pol.Id = grl.PurchaseOrderLineId INNER JOIN Items i ON i.Id = pol.ItemId INNER JOIN Inventories inv ON inv.Id = grl.InventoryId INNER JOIN Purposes p ON p.Id = inv.PurposeId INNER JOIN StorageLocations sl ON sl.Id = inv.StorageLocationId INNER JOIN Warehouses w ON w.Id = sl.WarehouseId WHERE grl.GoodsReceiptId = $GoodsReceiptId ORDER BY pol.LineNumber, grl.Id;";
    private string LineSql => $"SELECT {LineColumns}, COALESCE((SELECT SUM({Database.CastToInt64("posted.Quantity")}) FROM SupplierReturnLines posted INNER JOIN SupplierReturns header ON header.Id = posted.SupplierReturnId WHERE posted.GoodsReceiptLineId = srl.GoodsReceiptLineId AND header.Status = $Posted AND header.ReversedAtUtc IS NULL), 0), COALESCE((SELECT SUM({Database.CastToInt64("sm.Quantity")}) FROM StockMovements sm WHERE sm.InventoryId = srl.InventoryId), 0) FROM SupplierReturnLines srl INNER JOIN GoodsReceiptLines grl ON grl.Id = srl.GoodsReceiptLineId INNER JOIN Items i ON i.Id = srl.ItemId INNER JOIN Inventories inv ON inv.Id = srl.InventoryId INNER JOIN Purposes p ON p.Id = inv.PurposeId INNER JOIN StorageLocations sl ON sl.Id = inv.StorageLocationId INNER JOIN Warehouses w ON w.Id = sl.WarehouseId INNER JOIN ReasonCodes rc ON rc.Id = srl.ReasonCodeId WHERE srl.SupplierReturnId = $SupplierReturnId ORDER BY srl.Id;";
    private Task<IReadOnlyList<SupplierReturnLine>> ListLinesAsync(DatabaseSession session, long id, CancellationToken cancellationToken) => session.QueryAsync(LineSql, ReadLine, cancellationToken, Parameter("$SupplierReturnId", id), Parameter("$Posted", (int)SupplierReturnStatus.Posted));
    private static DatabaseParameter[] HeaderParameters(SupplierReturn value) => [Parameter("$ReturnNumber", value.ReturnNumber), Parameter("$SupplierId", value.SupplierId), Parameter("$ReturnDate", Date(value.ReturnDate)), Parameter("$Status", (int)value.Status), Parameter("$PurchaseOrderId", value.PurchaseOrderId), Parameter("$GoodsReceiptId", value.GoodsReceiptId), Parameter("$SupplierReference", value.SupplierReference), Parameter("$Notes", value.Notes), Parameter("$CreatedByUserId", value.CreatedByUserId)];
    private static DatabaseParameter[] LineParameters(SupplierReturnLine line) => [Parameter("$SupplierReturnId", line.SupplierReturnId), Parameter("$InventoryId", line.InventoryId), Parameter("$ItemId", line.ItemId), Parameter("$Quantity", line.Quantity), Parameter("$UnitCost", line.UnitCost), Parameter("$ReasonCodeId", line.ReasonCodeId), Parameter("$GoodsReceiptLineId", line.GoodsReceiptLineId)];
    private static SupplierReturn ReadHeader(DbDataReader r) => new() { Id = r.GetInt64(0), ReturnNumber = r.GetString(1), SupplierId = r.GetInt64(2), SupplierName = r.GetString(3), ReturnDate = ParseDate(r.GetString(4)), Status = (SupplierReturnStatus)r.GetInt32(5), PurchaseOrderId = r.GetInt64(6), PurchaseOrderNumber = r.GetString(7), GoodsReceiptId = r.GetInt64(8), GoodsReceiptNumber = r.GetString(9), SupplierReference = r.IsDBNull(10) ? null : r.GetString(10), Notes = r.IsDBNull(11) ? null : r.GetString(11), CreatedByUserId = r.GetInt64(12), PostedByUserId = r.IsDBNull(13) ? null : r.GetInt64(13), PostedAtUtc = r.IsDBNull(14) ? null : ParseDateTime(r.GetString(14)), ReversedByUserId = r.IsDBNull(15) ? null : r.GetInt64(15), ReversedAtUtc = r.IsDBNull(16) ? null : ParseDateTime(r.GetString(16)), ReversalReason = r.IsDBNull(17) ? null : r.GetString(17), Version = r.GetInt64(18) };
	private static SupplierReturnOverviewItem ReadOverview(DbDataReader r) => new() { Id = r.GetInt64(0), ReturnNumber = r.GetString(1), SupplierId = r.GetInt64(2), SupplierName = r.GetString(3), ReturnDate = ParseDate(r.GetString(4)), Status = (SupplierReturnStatus)r.GetInt32(5), PurchaseOrderNumber = r.GetString(6), GoodsReceiptNumber = r.GetString(7), SupplierReference = r.IsDBNull(8) ? null : r.GetString(8), LineCount = Convert.ToInt32(r.GetValue(9), CultureInfo.InvariantCulture), Version = r.GetInt64(10), IsReversed = Convert.ToInt32(r.GetValue(11), CultureInfo.InvariantCulture) != 0 };
    private static SupplierReturnReceiptOption ReadReceiptOption(DbDataReader r) => new() { GoodsReceiptId = r.GetInt64(0), ReceiptNumber = r.GetString(1), ReceiptDate = ParseDate(r.GetString(2)), PurchaseOrderId = r.GetInt64(3), PurchaseOrderNumber = r.GetString(4), SupplierId = r.GetInt64(5), SupplierName = r.GetString(6) };
    private static SupplierReturnableLine ReadReturnable(DbDataReader r) => new() { GoodsReceiptLineId = r.GetInt64(0), InventoryId = r.GetInt64(1), ItemId = r.GetInt64(2), PartNumber = r.GetString(3), ItemDescription = r.GetString(4), InventoryDisplay = $"{r.GetString(5)} / {r.GetString(6)} / {r.GetString(7)}", ReceivedQuantity = r.GetInt32(8), AlreadyReturnedQuantity = Convert.ToInt32(r.GetValue(9), CultureInfo.InvariantCulture), AvailableStock = Convert.ToInt64(r.GetValue(10), CultureInfo.InvariantCulture), UnitCost = r.GetDecimal(11) };
    private static SupplierReturnLine ReadLine(DbDataReader r) => new() { Id = r.GetInt64(0), SupplierReturnId = r.GetInt64(1), InventoryId = r.GetInt64(2), ItemId = r.GetInt64(3), Quantity = r.GetInt32(4), UnitCost = r.GetDecimal(5), ReasonCodeId = r.GetInt64(6), GoodsReceiptLineId = r.GetInt64(7), Version = r.GetInt64(8), PartNumber = r.GetString(9), ItemDescription = r.GetString(10), InventoryDisplay = $"{r.GetString(11)} / {r.GetString(12)} / {r.GetString(13)}", ReasonCodeName = r.GetString(14), ReceivedQuantity = r.GetInt32(15), AlreadyReturnedQuantity = Convert.ToInt32(r.GetValue(16), CultureInfo.InvariantCulture), AvailableStock = Convert.ToInt64(r.GetValue(17), CultureInfo.InvariantCulture) };
    private static string Date(DateTime value) => value.Date.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture); private static DateTime ParseDate(string value) => DateTime.Parse(value, CultureInfo.InvariantCulture, DateTimeStyles.AssumeLocal); private static string DateTimeValue(DateTime value) => value.ToUniversalTime().ToString("O", CultureInfo.InvariantCulture); private static DateTime ParseDateTime(string value) => DateTime.Parse(value, CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind).ToUniversalTime();
}
