// Copyright (c) 2026 David Beusing
// Licensed under the MIT License.

using Depot.Data;
using Depot.Models;
using Depot.Repositories;

namespace Depot.Services;

public sealed class PriceListGenerationService
{
	private readonly IDatabaseTransactionRunner _transactions;
	private readonly ItemCostRepository _costRepository;
	private readonly ItemCostCalculationService _costs;
	private readonly SalesPriceListRepository _prices;
	private readonly SalesPricingService _pricing;
	private readonly AuditRepository _auditEntries;
	private readonly AuditService _audit;
	private readonly IAuthorizationService _authorization;
	public PriceListGenerationService(IDatabaseTransactionRunner transactions,ItemCostRepository costRepository,ItemCostCalculationService costs,SalesPriceListRepository prices,SalesPricingService pricing,AuditRepository auditEntries,AuditService audit,IAuthorizationService authorization){_transactions=transactions;_costRepository=costRepository;_costs=costs;_prices=prices;_pricing=pricing;_auditEntries=auditEntries;_audit=audit;_authorization=authorization;}
	public bool CanPreview=>_authorization.HasPermission(ApplicationPermission.SalesPricingView)&&_authorization.HasPermission(ApplicationPermission.ItemsView);
	public bool CanApply=>_authorization.HasPermission(ApplicationPermission.SalesPricingManage)&&_costs.CanView;

	public async Task<PriceListGenerationPreview> PreviewAsync(PriceListGenerationRequest request,CancellationToken token=default)
	{
		ArgumentNullException.ThrowIfNull(request);RequirePreview();ValidateRequest(request);var target=await ResolvePreviewTargetAsync(request,token);var candidates=Filter(await _costRepository.ListCandidatesAsync(token),request).ToArray();var existing=target.Id>0?target.Items.ToDictionary(item=>item.ItemId):new Dictionary<long,SalesPriceListItem>();var rows=new List<BulkPricePreviewRow>(candidates.Length);
		foreach(var candidate in candidates){token.ThrowIfCancellationRequested();existing.TryGetValue(candidate.ItemId,out var current);var cost=await _costs.CalculateAsync(candidate.ItemId,request.EffectiveDate,target.Currency,token);if(!cost.IsSuccess){rows.Add(ErrorRow(candidate,current,request.MarkupPercentage,cost));continue;}var newPrice=CurrencyRounding.Round(cost.CalculatedCost*(1m+request.MarkupPercentage/100m),target.Currency);rows.Add(CreateRow(candidate,current,cost,newPrice,request));}
		return new PriceListGenerationPreview{Request=SnapshotRequest(request),TargetPriceListId=target.Id>0?target.Id:null,TargetPriceListVersion=target.Version,TargetPriceListName=target.Name,Currency=target.Currency,Rows=rows};
	}

	public async Task<PriceListGenerationApplyResult> ApplyAsync(PriceListGenerationPreview preview,CancellationToken token=default)
	{
		ArgumentNullException.ThrowIfNull(preview);RequireApply();if(preview.ErrorCount>0)throw new InvalidOperationException("Bulk price preview contains calculation errors. Resolve them and calculate a new preview before applying.");
		return await _transactions.ExecuteAsync(async(transaction,ct)=>
		{
			SalesPriceList target;if(preview.TargetPriceListId is long targetId){target=await _prices.GetByIdAsync(transaction,targetId,ct)??throw new ConcurrencyConflictException("sales price list");if(target.Version!=preview.TargetPriceListVersion)throw new ConcurrencyConflictException("sales price list");if(!string.Equals(target.Currency,preview.Currency,StringComparison.OrdinalIgnoreCase))throw new ConcurrencyConflictException("sales price list currency");}else{var draft=preview.Request.NewPriceList is null?throw new InvalidOperationException("New price-list definition is missing."):Copy(preview.Request.NewPriceList);target=await _pricing.SaveInTransactionAsync(transaction,draft,ct);}
			var created=0;var updated=0;var skipped=0;
			foreach(var row in preview.Rows){ct.ThrowIfCancellationRequested();if(row.Action==BulkPricePreviewAction.Skip){skipped++;continue;}if(row.Action==BulkPricePreviewAction.Error)throw new InvalidOperationException($"Item {row.PartNumber} is not calculable.");var current=await _prices.GetItemAsync(transaction,target.Id,row.ItemId,ct);if(row.ExistingPriceItemId is null){if(current is not null)throw new ConcurrencyConflictException("sales price list item");}else if(current is null||current.Id!=row.ExistingPriceItemId||current.Version!=row.ExistingPriceItemVersion)throw new ConcurrencyConflictException("sales price list item");var cost=await _costs.CalculateAsync(transaction,row.ItemId,preview.Request.EffectiveDate,target.Currency,ct);if(!cost.IsSuccess||!string.Equals(cost.EvidenceVersion,row.CostEvidenceVersion,StringComparison.Ordinal))throw new ConcurrencyConflictException("item cost calculation evidence");var newPrice=CurrencyRounding.Round(cost.CalculatedCost*(1m+preview.Request.MarkupPercentage/100m),target.Currency);if(newPrice!=row.CalculatedNewPrice)throw new ConcurrencyConflictException("bulk price calculation");var expectedAction=DecideAction(current?.UnitPrice,newPrice,preview.Request.ApplyMode);if(expectedAction!=row.Action)throw new ConcurrencyConflictException("bulk price apply mode");if(expectedAction==BulkPricePreviewAction.Skip){skipped++;continue;}var entry=new SalesPriceListItem{Id=current?.Id??0,SalesPriceListId=target.Id,ItemId=row.ItemId,PartNumber=row.PartNumber,Description=row.Description,UnitPrice=newPrice,DiscountPercent=current?.DiscountPercent??0m,Version=current?.Version??1};await _prices.SaveItemAsync(transaction,entry,ct);if(current is null)created++;else updated++;}
			var evidence=new PriceListGenerationAuditRecord{PriceListId=target.Id,PriceListName=target.Name,MarkupPercentage=preview.Request.MarkupPercentage,ApplyMode=preview.Request.ApplyMode,Created=created,Updated=updated,Skipped=skipped,Failed=0};await _auditEntries.CreateAsync(transaction,_audit.CreateActionEntry(target.Id,"Bulk prices applied",(PriceListGenerationAuditRecord?)null,evidence),ct);return new PriceListGenerationApplyResult(target.Id,created,updated,skipped,0);
		},token);
	}

	private async Task<SalesPriceList> ResolvePreviewTargetAsync(PriceListGenerationRequest request,CancellationToken token){if(request.ExistingPriceListId is long id)return await _prices.GetByIdAsync(id,token)??throw new InvalidOperationException("Target sales price list was not found.");var draft=request.NewPriceList??throw new ArgumentException("Select an existing price list or define a new one.",nameof(request));var copy=Copy(draft);SalesPricingService.NormalizeAndValidate(copy);return copy;}
	private static IEnumerable<ItemCostCandidate> Filter(IEnumerable<ItemCostCandidate> candidates,PriceListGenerationRequest request)=>request.FilterType switch{BulkPriceFilterType.AllActiveItems=>candidates,BulkPriceFilterType.Category=>candidates.Where(item=>item.CategoryId==request.FilterId),BulkPriceFilterType.Manufacturer=>candidates.Where(item=>item.ManufacturerId==request.FilterId),BulkPriceFilterType.SelectedItems=>candidates.Where(item=>request.SelectedItemIds.Contains(item.ItemId)),_=>throw new ArgumentOutOfRangeException(nameof(request.FilterType))};
	private static BulkPricePreviewRow CreateRow(ItemCostCandidate candidate,SalesPriceListItem? current,ItemCostCalculationResult cost,decimal newPrice,PriceListGenerationRequest request){var change=current is null?(decimal?)null:newPrice-current.UnitPrice;var percent=current is null||current.UnitPrice==0m?(decimal?)null:decimal.Round((newPrice-current.UnitPrice)/current.UnitPrice*100m,2,MidpointRounding.ToEven);return new BulkPricePreviewRow{ItemId=candidate.ItemId,PartNumber=candidate.PartNumber,Description=candidate.Description,IsCalculable=true,CalculatedCost=cost.CalculatedCost,CurrentPrice=current?.UnitPrice,CalculatedNewPrice=newPrice,AbsoluteChange=change,PercentageChange=percent,MarkupPercentage=request.MarkupPercentage,Action=DecideAction(current?.UnitPrice,newPrice,request.ApplyMode),ExistingPriceItemId=current?.Id,ExistingPriceItemVersion=current?.Version,CostEvidenceVersion=cost.EvidenceVersion,CostComponents=cost.Components};}
	private static BulkPricePreviewRow ErrorRow(ItemCostCandidate candidate,SalesPriceListItem? current,decimal markup,ItemCostCalculationResult cost)=>new(){ItemId=candidate.ItemId,PartNumber=candidate.PartNumber,Description=candidate.Description,IsCalculable=false,Error=cost.Error,CurrentPrice=current?.UnitPrice,MarkupPercentage=markup,Action=BulkPricePreviewAction.Error,ExistingPriceItemId=current?.Id,ExistingPriceItemVersion=current?.Version,CostComponents=cost.Components};
	private static BulkPricePreviewAction DecideAction(decimal? current,decimal calculated,BulkPriceApplyMode mode)=>mode switch{BulkPriceApplyMode.ReplaceCalculatedPrices=>current is null?BulkPricePreviewAction.Create:BulkPricePreviewAction.Update,BulkPriceApplyMode.OnlyIncreasePrices=>current is null?BulkPricePreviewAction.Create:calculated>current?BulkPricePreviewAction.Update:BulkPricePreviewAction.Skip,BulkPriceApplyMode.OnlyCreateMissingPrices=>current is null?BulkPricePreviewAction.Create:BulkPricePreviewAction.Skip,_=>throw new ArgumentOutOfRangeException(nameof(mode))};
	private static PriceListGenerationRequest SnapshotRequest(PriceListGenerationRequest r)=>new(){ExistingPriceListId=r.ExistingPriceListId,NewPriceList=r.NewPriceList is null?null:Copy(r.NewPriceList),FilterType=r.FilterType,FilterId=r.FilterId,SelectedItemIds=r.SelectedItemIds.Distinct().OrderBy(id=>id).ToArray(),MarkupPercentage=r.MarkupPercentage,ApplyMode=r.ApplyMode,EffectiveDate=r.EffectiveDate.Date};
	private static SalesPriceList Copy(SalesPriceList v)=>new(){Id=v.Id,Code=v.Code,Name=v.Name,Scope=v.Scope,RegionId=v.RegionId,RegionName=v.RegionName,Currency=v.Currency,ValidFrom=v.ValidFrom,ValidTo=v.ValidTo,IsActive=v.IsActive,Version=v.Version,Items=v.Items};
	private static void ValidateRequest(PriceListGenerationRequest r){if((r.ExistingPriceListId is null)==(r.NewPriceList is null))throw new ArgumentException("Exactly one price-list target is required.");if(r.ExistingPriceListId is <=0)throw new ArgumentOutOfRangeException(nameof(r.ExistingPriceListId));if(r.MarkupPercentage<0m)throw new ArgumentOutOfRangeException(nameof(r.MarkupPercentage));if(!Enum.IsDefined(r.FilterType)||!Enum.IsDefined(r.ApplyMode))throw new ArgumentException("Valid filter and apply mode are required.");if((r.FilterType is BulkPriceFilterType.Category or BulkPriceFilterType.Manufacturer)&&r.FilterId is not >0)throw new ArgumentException("Selected filter requires a master-data value.");if(r.FilterType==BulkPriceFilterType.SelectedItems&&r.SelectedItemIds.Count==0)throw new ArgumentException("Select at least one item.");}
	private void RequirePreview(){if(!CanPreview)throw new UnauthorizedAccessException("Viewing item costs and sales pricing is required for bulk price preview.");}
	private void RequireApply(){if(!CanApply)throw new UnauthorizedAccessException("Managing sales pricing and viewing item costs is required for bulk price apply.");}
}
