// Copyright (c) 2026 David Beusing
// Licensed under the MIT License.

using System.Globalization;
using Depot.Data;
using Depot.Models;
using Depot.Repositories;

namespace Depot.Services;

public sealed class PriceListGenerationService
{
	private readonly IDatabaseTransactionRunner _transactions;
	private readonly ItemCostRepository _costRepository;
	private readonly ItemCostCalculationService _costs;
	private readonly SalesPriceListRepository _prices;
	private readonly SalesPricingService _pricing;
	private readonly AuditRepository _auditEntries;
	private readonly AuditService _audit;
	private readonly IAuthorizationService _authorization;
	public PriceListGenerationService(IDatabaseTransactionRunner transactions,ItemCostRepository costRepository,ItemCostCalculationService costs,SalesPriceListRepository prices,SalesPricingService pricing,AuditRepository auditEntries,AuditService audit,IAuthorizationService authorization){_transactions=transactions;_costRepository=costRepository;_costs=costs;_prices=prices;_pricing=pricing;_auditEntries=auditEntries;_audit=audit;_authorization=authorization;}
	public bool CanPreview=>_authorization.HasPermission(ApplicationPermission.SalesPricingView)&&_authorization.HasPermission(ApplicationPermission.ItemsView);
	public bool CanApply=>_authorization.HasPermission(ApplicationPermission.SalesPricingManage)&&_costs.CanView;
	public bool CanManageExchangeRates=>_authorization.HasPermission(ApplicationPermission.SalesPricingManage);

	public Task<IReadOnlyList<PricingExchangeRate>> ListExchangeRatesAsync(CancellationToken token=default){_authorization.RequirePermission(ApplicationPermission.SalesPricingView);return _costRepository.ListExchangeRatesAsync(token);}
	public async Task<PricingExchangeRate> SaveExchangeRateAsync(PricingExchangeRate value,CancellationToken token=default)
	{
		if(!CanManageExchangeRates)throw new UnauthorizedAccessException("Managing pricing exchange rates requires sales pricing management permission.");NormalizeExchangeRate(value);return await _transactions.ExecuteAsync(async(transaction,ct)=>{var before=value.Id==0?null:await _costRepository.GetExchangeRateAsync(transaction,value.Id,ct)??throw new InvalidOperationException("Pricing exchange rate was not found.");var saved=await _costRepository.SaveExchangeRateAsync(transaction,value,ct);await _auditEntries.CreateAsync(transaction,before is null?_audit.CreateCreatedEntry(saved.Id,saved):_audit.CreateUpdatedEntry(saved.Id,before,saved),ct);return saved;},token);
	}

	public async Task<PriceListGenerationPreview> PreviewAsync(PriceListGenerationRequest request,CancellationToken token=default)
	{
		ArgumentNullException.ThrowIfNull(request);RequirePreview();ValidateRequest(request);var target=await ResolvePreviewTargetAsync(request,token);ValidateTargetCurrency(request,target.Currency);var candidates=Filter(await _costRepository.ListCandidatesAsync(token),request).ToArray();var existing=target.Id>0?target.Items.ToDictionary(item=>item.ItemId):new Dictionary<long,SalesPriceListItem>();var rows=new List<BulkPricePreviewRow>(candidates.Length);
		foreach(var candidate in candidates){token.ThrowIfCancellationRequested();existing.TryGetValue(candidate.ItemId,out var current);var calculation=await CalculatePriceAsync(null,candidate.ItemId,target.Currency,request,token);if(!calculation.IsSuccess){rows.Add(ErrorRow(candidate,current,request,target.Currency,calculation));continue;}rows.Add(CreateRow(candidate,current,calculation,request,target.Currency));}
		return new PriceListGenerationPreview{Request=SnapshotRequest(request),TargetPriceListId=target.Id>0?target.Id:null,TargetPriceListVersion=target.Version,TargetPriceListName=target.Name,Currency=target.Currency,Rows=rows};
	}

	public async Task<PriceListGenerationApplyResult> ApplyAsync(PriceListGenerationPreview preview,CancellationToken token=default)
	{
		ArgumentNullException.ThrowIfNull(preview);RequireApply();if(preview.ErrorCount>0)throw new InvalidOperationException("Bulk price preview contains calculation errors. Resolve them and calculate a new preview before applying.");
		return await _transactions.ExecuteAsync(async(transaction,ct)=>
		{
			SalesPriceList target;if(preview.TargetPriceListId is long targetId){target=await _prices.GetByIdAsync(transaction,targetId,ct)??throw new ConcurrencyConflictException("sales price list");if(target.Version!=preview.TargetPriceListVersion)throw new ConcurrencyConflictException("sales price list");if(!string.Equals(target.Currency,preview.Currency,StringComparison.OrdinalIgnoreCase))throw new ConcurrencyConflictException("sales price list currency");}else{var draft=preview.Request.NewPriceList is null?throw new InvalidOperationException("New price-list definition is missing."):Copy(preview.Request.NewPriceList);target=await _pricing.SaveInTransactionAsync(transaction,draft,ct);}
			ValidateTargetCurrency(preview.Request,target.Currency);var created=0;var updated=0;var skipped=0;var exchangeRates=new Dictionary<long,PricingExchangeRateEvidence>();
			foreach(var row in preview.Rows){ct.ThrowIfCancellationRequested();if(row.Action==BulkPricePreviewAction.Skip){var skippedCalculation=await CalculatePriceAsync(transaction,row.ItemId,target.Currency,preview.Request,ct);EnsureCalculationStillMatches(row,skippedCalculation);AddExchangeRate(exchangeRates,skippedCalculation.ExchangeRate);skipped++;continue;}if(row.Action==BulkPricePreviewAction.Error)throw new InvalidOperationException($"Item {row.PartNumber} is not calculable.");var current=await _prices.GetItemAsync(transaction,target.Id,row.ItemId,ct);if(row.ExistingPriceItemId is null){if(current is not null)throw new ConcurrencyConflictException("sales price list item");}else if(current is null||current.Id!=row.ExistingPriceItemId||current.Version!=row.ExistingPriceItemVersion)throw new ConcurrencyConflictException("sales price list item");var calculation=await CalculatePriceAsync(transaction,row.ItemId,target.Currency,preview.Request,ct);EnsureCalculationStillMatches(row,calculation);AddExchangeRate(exchangeRates,calculation.ExchangeRate);var newPrice=calculation.FinalPrice!.Value;var expectedAction=DecideAction(current?.UnitPrice,newPrice,preview.Request.ApplyMode);if(expectedAction!=row.Action)throw new ConcurrencyConflictException("bulk price apply mode");if(expectedAction==BulkPricePreviewAction.Skip){skipped++;continue;}var entry=new SalesPriceListItem{Id=current?.Id??0,SalesPriceListId=target.Id,ItemId=row.ItemId,PartNumber=row.PartNumber,Description=row.Description,UnitPrice=newPrice,DiscountPercent=current?.DiscountPercent??0m,Version=current?.Version??1};await _prices.SaveItemAsync(transaction,entry,ct);if(current is null)created++;else updated++;}
			var evidence=new PriceListGenerationAuditRecord{PriceListId=target.Id,PriceListName=target.Name,PricingMethod=preview.Request.PricingMethod.ToString(),PricingPercentage=preview.Request.PricingPercentage,MarkupPercentage=preview.Request.MarkupPercentage,GrossMarginPercentage=preview.Request.GrossMarginPercentage,RoundingStrategy=preview.Request.RoundingStrategy,ApplyMode=preview.Request.ApplyMode,EffectiveDate=preview.Request.EffectiveDate.Date,ExchangeRates=exchangeRates.Values.OrderBy(rate=>rate.RateId).ToArray(),Created=created,Updated=updated,Skipped=skipped,Failed=0};await _auditEntries.CreateAsync(transaction,_audit.CreateActionEntry(target.Id,"Bulk prices applied",(PriceListGenerationAuditRecord?)null,evidence),ct);return new PriceListGenerationApplyResult(target.Id,created,updated,skipped,0);
		},token);
	}

	private async Task<PriceCalculation> CalculatePriceAsync(DatabaseTransactionContext? transaction,long itemId,string targetCurrency,PriceListGenerationRequest request,CancellationToken token)
	{
		var cost=transaction is null?await _costs.CalculateAsync(itemId,request.EffectiveDate,null,token):await _costs.CalculateAsync(transaction,itemId,request.EffectiveDate,null,token);if(!cost.IsSuccess)return PriceCalculation.Fail(cost,cost.Error??"Item cost calculation failed.");PricingExchangeRateEvidence fx;
		if(string.Equals(cost.Currency,targetCurrency,StringComparison.OrdinalIgnoreCase))fx=new(null,"Identity",request.EffectiveDate.Date,1m,cost.Currency,targetCurrency,0);
		else
		{
			var rate=transaction is null?await _costRepository.ResolveExchangeRateAsync(cost.Currency,targetCurrency,request.EffectiveDate,token):await _costRepository.ResolveExchangeRateAsync(transaction,cost.Currency,targetCurrency,request.EffectiveDate,token);if(rate is null)return PriceCalculation.Fail(cost,$"No effective direct FX rate exists for {cost.Currency} → {targetCurrency} on {request.EffectiveDate:yyyy-MM-dd}.");fx=new(rate.Id,rate.RateSource,rate.EffectiveDate,rate.Rate,rate.SourceCurrency,rate.TargetCurrency,rate.Version);
		}
		var converted=CurrencyRounding.Round(cost.CalculatedCost*fx.Rate,targetCurrency);decimal unrounded=request.PricingMethod switch{BulkPricePricingMethod.PercentageMarkup=>converted*(1m+request.MarkupPercentage/100m),BulkPricePricingMethod.TargetGrossMargin=>converted/(1m-request.GrossMarginPercentage/100m),_=>throw new ArgumentOutOfRangeException(nameof(request.PricingMethod))};decimal final;try{final=CommercialPriceRounding.Round(unrounded,targetCurrency,request.RoundingStrategy);}catch(InvalidOperationException ex){return PriceCalculation.Fail(cost,ex.Message,fx,converted,unrounded);}var pricingEvidence=BuildPricingEvidence(cost,fx,request,targetCurrency);return new(true,null,cost,fx,converted,unrounded,final,final-unrounded,pricingEvidence);
	}

	private static void EnsureCalculationStillMatches(BulkPricePreviewRow row,PriceCalculation calculation){if(!calculation.IsSuccess||!string.Equals(calculation.Cost.EvidenceVersion,row.CostEvidenceVersion,StringComparison.Ordinal)||!string.Equals(calculation.PricingEvidenceVersion,row.PricingEvidenceVersion,StringComparison.Ordinal)||calculation.FinalPrice!=row.CalculatedNewPrice)throw new ConcurrencyConflictException("bulk price calculation evidence");}
	private static string BuildPricingEvidence(ItemCostCalculationResult cost,PricingExchangeRateEvidence fx,PriceListGenerationRequest request,string targetCurrency)=>string.Join('|',cost.EvidenceVersion,$"fx:{fx.RateId?.ToString(CultureInfo.InvariantCulture)??"identity"}:{fx.Version}:{fx.EffectiveDate:yyyyMMdd}:{fx.Rate.ToString(CultureInfo.InvariantCulture)}:{fx.SourceCurrency}:{fx.TargetCurrency}",$"method:{(int)request.PricingMethod}:{request.PricingPercentage.ToString(CultureInfo.InvariantCulture)}",$"round:{(int)request.RoundingStrategy}:{targetCurrency.ToUpperInvariant()}");
	private static void AddExchangeRate(Dictionary<long,PricingExchangeRateEvidence> rates,PricingExchangeRateEvidence? rate){if(rate?.RateId is long id)rates[id]=rate;}
	private async Task<SalesPriceList> ResolvePreviewTargetAsync(PriceListGenerationRequest request,CancellationToken token){if(request.ExistingPriceListId is long id)return await _prices.GetByIdAsync(id,token)??throw new InvalidOperationException("Target sales price list was not found.");var draft=request.NewPriceList??throw new ArgumentException("Select an existing price list or define a new one.",nameof(request));var copy=Copy(draft);SalesPricingService.NormalizeAndValidate(copy);return copy;}
	private static IEnumerable<ItemCostCandidate> Filter(IEnumerable<ItemCostCandidate> candidates,PriceListGenerationRequest request)=>request.FilterType switch{BulkPriceFilterType.AllActiveItems=>candidates,BulkPriceFilterType.Category=>candidates.Where(item=>item.CategoryId==request.FilterId),BulkPriceFilterType.Manufacturer=>candidates.Where(item=>item.ManufacturerId==request.FilterId),BulkPriceFilterType.SelectedItems=>candidates.Where(item=>request.SelectedItemIds.Contains(item.ItemId)),_=>throw new ArgumentOutOfRangeException(nameof(request.FilterType))};
	private static BulkPricePreviewRow CreateRow(ItemCostCandidate candidate,SalesPriceListItem? current,PriceCalculation calculation,PriceListGenerationRequest request,string targetCurrency){var newPrice=calculation.FinalPrice!.Value;var change=current is null?(decimal?)null:newPrice-current.UnitPrice;var percent=current is null||current.UnitPrice==0m?(decimal?)null:decimal.Round((newPrice-current.UnitPrice)/current.UnitPrice*100m,2,MidpointRounding.ToEven);return new BulkPricePreviewRow{ItemId=candidate.ItemId,PartNumber=candidate.PartNumber,Description=candidate.Description,IsCalculable=true,BaseCostSource=calculation.Cost.BaseCostSource,BaseCost=calculation.Cost.BaseCost,CalculatedCost=calculation.Cost.CalculatedCost,SourceCurrency=calculation.Cost.Currency,ExchangeRate=calculation.ExchangeRate,ConvertedCost=calculation.ConvertedCost,TargetCurrency=targetCurrency,PricingMethod=request.PricingMethod,MarkupPercentage=request.MarkupPercentage,GrossMarginPercentage=request.GrossMarginPercentage,PricingPercentage=request.PricingPercentage,UnroundedPrice=calculation.UnroundedPrice,RoundingStrategy=request.RoundingStrategy,RoundingAdjustment=calculation.RoundingAdjustment,CurrentPrice=current?.UnitPrice,CalculatedNewPrice=newPrice,AbsoluteChange=change,PercentageChange=percent,Action=DecideAction(current?.UnitPrice,newPrice,request.ApplyMode),ExistingPriceItemId=current?.Id,ExistingPriceItemVersion=current?.Version,CostEvidenceVersion=calculation.Cost.EvidenceVersion,PricingEvidenceVersion=calculation.PricingEvidenceVersion,CostComponents=calculation.Cost.Components};}
	private static BulkPricePreviewRow ErrorRow(ItemCostCandidate candidate,SalesPriceListItem? current,PriceListGenerationRequest request,string targetCurrency,PriceCalculation calculation)=>new(){ItemId=candidate.ItemId,PartNumber=candidate.PartNumber,Description=candidate.Description,IsCalculable=false,Error=calculation.Error,BaseCostSource=calculation.Cost.BaseCostSource,BaseCost=calculation.Cost.IsSuccess?calculation.Cost.BaseCost:null,CalculatedCost=calculation.Cost.IsSuccess?calculation.Cost.CalculatedCost:null,SourceCurrency=calculation.Cost.Currency,ExchangeRate=calculation.ExchangeRate,ConvertedCost=calculation.ConvertedCost,TargetCurrency=targetCurrency,PricingMethod=request.PricingMethod,MarkupPercentage=request.MarkupPercentage,GrossMarginPercentage=request.GrossMarginPercentage,PricingPercentage=request.PricingPercentage,UnroundedPrice=calculation.UnroundedPrice,RoundingStrategy=request.RoundingStrategy,CurrentPrice=current?.UnitPrice,Action=BulkPricePreviewAction.Error,ExistingPriceItemId=current?.Id,ExistingPriceItemVersion=current?.Version,CostEvidenceVersion=calculation.Cost.EvidenceVersion,CostComponents=calculation.Cost.Components};
	private static BulkPricePreviewAction DecideAction(decimal? current,decimal calculated,BulkPriceApplyMode mode)=>mode switch{BulkPriceApplyMode.ReplaceCalculatedPrices=>current is null?BulkPricePreviewAction.Create:BulkPricePreviewAction.Update,BulkPriceApplyMode.OnlyIncreasePrices=>current is null?BulkPricePreviewAction.Create:calculated>current?BulkPricePreviewAction.Update:BulkPricePreviewAction.Skip,BulkPriceApplyMode.OnlyCreateMissingPrices=>current is null?BulkPricePreviewAction.Create:BulkPricePreviewAction.Skip,_=>throw new ArgumentOutOfRangeException(nameof(mode))};
	private static PriceListGenerationRequest SnapshotRequest(PriceListGenerationRequest r)=>new(){ExistingPriceListId=r.ExistingPriceListId,NewPriceList=r.NewPriceList is null?null:Copy(r.NewPriceList),FilterType=r.FilterType,FilterId=r.FilterId,SelectedItemIds=r.SelectedItemIds.Distinct().OrderBy(id=>id).ToArray(),PricingMethod=r.PricingMethod,MarkupPercentage=r.MarkupPercentage,GrossMarginPercentage=r.GrossMarginPercentage,RoundingStrategy=r.RoundingStrategy,ApplyMode=r.ApplyMode,EffectiveDate=r.EffectiveDate.Date};
	private static SalesPriceList Copy(SalesPriceList v)=>new(){Id=v.Id,Code=v.Code,Name=v.Name,Scope=v.Scope,RegionId=v.RegionId,RegionName=v.RegionName,Currency=v.Currency,ValidFrom=v.ValidFrom,ValidTo=v.ValidTo,IsActive=v.IsActive,Version=v.Version,Items=v.Items};
	private static void ValidateRequest(PriceListGenerationRequest r){if((r.ExistingPriceListId is null)==(r.NewPriceList is null))throw new ArgumentException("Exactly one price-list target is required.");if(r.ExistingPriceListId is <=0)throw new ArgumentOutOfRangeException(nameof(r.ExistingPriceListId));if(!Enum.IsDefined(r.PricingMethod)||!Enum.IsDefined(r.RoundingStrategy)||!Enum.IsDefined(r.FilterType)||!Enum.IsDefined(r.ApplyMode))throw new ArgumentException("Valid pricing, rounding, filter and apply strategies are required.");if(r.MarkupPercentage<0m)throw new ArgumentOutOfRangeException(nameof(r.MarkupPercentage));if(r.GrossMarginPercentage<0m||r.GrossMarginPercentage>=100m)throw new ArgumentOutOfRangeException(nameof(r.GrossMarginPercentage),"Gross margin must be at least 0% and below 100%.");if((r.FilterType is BulkPriceFilterType.Category or BulkPriceFilterType.Manufacturer)&&r.FilterId is not >0)throw new ArgumentException("Selected filter requires a master-data value.");if(r.FilterType==BulkPriceFilterType.SelectedItems&&r.SelectedItemIds.Count==0)throw new ArgumentException("Select at least one item.");}
	private static void ValidateTargetCurrency(PriceListGenerationRequest request,string currency){if(request.RoundingStrategy==CommercialRoundingStrategy.Ending99&&CurrencyRounding.Precision(currency)!=2)throw new ArgumentException("The .99 ending strategy requires a two-decimal target currency.",nameof(request));}
	private static void NormalizeExchangeRate(PricingExchangeRate value){ArgumentNullException.ThrowIfNull(value);value.SourceCurrency=NormalizeCurrency(value.SourceCurrency,nameof(value.SourceCurrency));value.TargetCurrency=NormalizeCurrency(value.TargetCurrency,nameof(value.TargetCurrency));if(string.Equals(value.SourceCurrency,value.TargetCurrency,StringComparison.Ordinal))throw new ArgumentException("FX source and target currency must differ.");value.RateSource=value.RateSource.Trim();if(value.RateSource.Length is 0 or >200)throw new ArgumentException("FX rate source is required and limited to 200 characters.");if(value.Rate<=0m)throw new ArgumentOutOfRangeException(nameof(value.Rate));value.EffectiveDate=value.EffectiveDate.Date;}
	private static string NormalizeCurrency(string value,string parameterName){var normalized=value.Trim().ToUpperInvariant();if(normalized.Length!=3||!normalized.All(char.IsLetter))throw new ArgumentException("Currency must be a three-letter ISO code.",parameterName);return normalized;}
	private void RequirePreview(){if(!CanPreview)throw new UnauthorizedAccessException("Viewing item costs and sales pricing is required for bulk price preview.");}
	private void RequireApply(){if(!CanApply)throw new UnauthorizedAccessException("Managing sales pricing and viewing item costs is required for bulk price apply.");}

	private sealed record PriceCalculation(bool IsSuccess,string? Error,ItemCostCalculationResult Cost,PricingExchangeRateEvidence? ExchangeRate,decimal? ConvertedCost,decimal? UnroundedPrice,decimal? FinalPrice,decimal? RoundingAdjustment,string PricingEvidenceVersion)
	{
		public static PriceCalculation Fail(ItemCostCalculationResult cost,string error,PricingExchangeRateEvidence? fx=null,decimal? converted=null,decimal? unrounded=null)=>new(false,error,cost,fx,converted,unrounded,null,null,string.Empty);
	}
}
