// Copyright (c) 2026 David Beusing
// Licensed under the MIT License.

using System.Text.Json;
using Depot.Data;
using Depot.Models;
using Depot.Repositories;

namespace Depot.Services;

public sealed record SubscriptionInvoiceGenerationResult(SubscriptionBillingInstance Instance,SalesInvoice? Invoice);

public sealed class SubscriptionBillingService
{
	private static readonly JsonSerializerOptions SnapshotJson=new(JsonSerializerDefaults.Web);
	private readonly IDatabaseTransactionRunner _transactions;private readonly SubscriptionBillingRepository _subscriptions;private readonly CustomerRepository _customers;private readonly ItemRepository _items;private readonly SalesPricingService _pricing;private readonly SalesInvoiceService _invoices;private readonly AuditRepository _auditEntries;private readonly AuditService _audit;private readonly IAuthorizationService _authorization;
	public SubscriptionBillingService(IDatabaseTransactionRunner transactions,SubscriptionBillingRepository subscriptions,CustomerRepository customers,ItemRepository items,SalesPricingService pricing,SalesInvoiceService invoices,AuditRepository auditEntries,AuditService audit,IAuthorizationService authorization){_transactions=transactions;_subscriptions=subscriptions;_customers=customers;_items=items;_pricing=pricing;_invoices=invoices;_auditEntries=auditEntries;_audit=audit;_authorization=authorization;}
	public bool CanView=>_authorization.HasPermission(ApplicationPermission.SubscriptionContractsView);public bool CanManage=>_authorization.HasPermission(ApplicationPermission.SubscriptionContractsManage);public bool CanGenerate=>_authorization.HasPermission(ApplicationPermission.SubscriptionBillingGenerate)&&_authorization.HasPermission(ApplicationPermission.SalesInvoicesCreate);
	public Task<PageResult<SubscriptionContract>> SearchAsync(string? searchText=null,SubscriptionContractStatus? status=null,int pageNumber=1,int pageSize=100,CancellationToken token=default){_authorization.RequirePermission(ApplicationPermission.SubscriptionContractsView);return _subscriptions.SearchContractsAsync(searchText,status,pageNumber,pageSize,token);}
	public Task<SubscriptionContract?> GetAsync(long id,CancellationToken token=default){_authorization.RequirePermission(ApplicationPermission.SubscriptionContractsView);return _subscriptions.GetContractAsync(id,token);}
	public Task<IReadOnlyList<SubscriptionBillingInstance>> ListHistoryAsync(long contractId,int count=100,CancellationToken token=default){_authorization.RequirePermission(ApplicationPermission.SubscriptionContractsView);return _subscriptions.ListBillingInstancesAsync(contractId,count,token);}
	public Task<IReadOnlyList<SubscriptionBillingInstance>> ListDueAsync(DateOnly asOf,int count=200,CancellationToken token=default){_authorization.RequirePermission(ApplicationPermission.SubscriptionContractsView);return _subscriptions.ListDueBillingInstancesAsync(asOf,count,token);}

	public async Task<SubscriptionContract> SaveAsync(SubscriptionContract input,DateOnly? effectiveFrom=null,CancellationToken token=default)
	{
		_authorization.RequirePermission(ApplicationPermission.SubscriptionContractsManage);var user=RequireUser();var normalized=await NormalizeAsync(input,token);var now=DateTime.UtcNow;var today=DateOnly.FromDateTime(DateTime.Today);
		return await _transactions.ExecuteAsync(async(tx,ct)=>
		{
			if(normalized.Id==0){var createdInput=normalized with{Version=1,TermsRevision=1,ContractNumber=string.Empty,Status=SubscriptionContractStatus.Draft,StatusEffectiveDate=today,NextBillingDate=normalized.StartDate,OwnerUserId=normalized.OwnerUserId==0?user.Id:normalized.OwnerUserId,CreatedAtUtc=now,CreatedByUserId=user.Id,UpdatedAtUtc=now,UpdatedByUserId=user.Id};var id=await _subscriptions.CreateContractAsync(tx,createdInput,ct);var created=await _subscriptions.GetContractAsync(tx,id,ct)??throw new InvalidOperationException("Subscription contract could not be reloaded.");await _subscriptions.InsertRevisionAsync(tx,new(id,1,effectiveFrom??created.StartDate,Snapshot(created),now,user.Id),ct);await _auditEntries.CreateAsync(tx,_audit.CreateCreatedEntry(id,created),ct);return created;}
			var before=await _subscriptions.GetContractAsync(tx,normalized.Id,ct)??throw new InvalidOperationException("Subscription contract was not found.");if(before.Version!=normalized.Version)throw new ConcurrencyConflictException("subscription contract");if(before.Status is SubscriptionContractStatus.Cancelled or SubscriptionContractStatus.Expired)throw new InvalidOperationException("Cancelled or expired subscription contracts cannot be amended.");if(before.CustomerId!=normalized.CustomerId||before.LegalEntityId!=normalized.LegalEntityId||before.StartDate!=normalized.StartDate)throw new InvalidOperationException("Customer, legal entity and start date become immutable after contract creation.");
			var effective=effectiveFrom??(before.Status==SubscriptionContractStatus.Draft?today:before.NextBillingDate);var latest=await _subscriptions.GetLatestGeneratedPeriodEndAsync(tx,before.Id,ct);if(latest is{} last&&effective<=last)throw new InvalidOperationException("Contract amendments cannot rewrite an already billed period.");if(before.Status!=SubscriptionContractStatus.Draft&&effective!=before.NextBillingDate)throw new InvalidOperationException("Active contract amendments must take effect on the next unbilled billing date.");var revision=before.TermsRevision+1;var amended=normalized with{ContractNumber=before.ContractNumber,Version=before.Version,TermsRevision=revision,Status=before.Status,StatusEffectiveDate=before.StatusEffectiveDate,NextBillingDate=before.NextBillingDate,OwnerUserId=before.OwnerUserId,CreatedAtUtc=before.CreatedAtUtc,CreatedByUserId=before.CreatedByUserId,UpdatedAtUtc=now,UpdatedByUserId=user.Id};if(!await _subscriptions.UpdateTermsAsync(tx,amended,before.Version,revision,user.Id,now,ct))throw new ConcurrencyConflictException("subscription contract");var after=await _subscriptions.GetContractAsync(tx,before.Id,ct)??throw new InvalidOperationException("Subscription contract could not be reloaded.");await _subscriptions.InsertRevisionAsync(tx,new(after.Id,revision,effective,Snapshot(after),now,user.Id),ct);await _auditEntries.CreateAsync(tx,_audit.CreateActionEntry(after.Id,"TermsAmended",before,after),ct);return after;
		},token);
	}

	public Task<SubscriptionContract> ActivateAsync(long id,long version,DateOnly effectiveDate,CancellationToken token=default)=>TransitionAsync(id,version,SubscriptionContractStatus.Active,effectiveDate,"Activated",token);
	public Task<SubscriptionContract> PauseAsync(long id,long version,DateOnly effectiveDate,CancellationToken token=default)=>TransitionAsync(id,version,SubscriptionContractStatus.Paused,effectiveDate,"Paused",token);
	public Task<SubscriptionContract> ResumeAsync(long id,long version,DateOnly effectiveDate,CancellationToken token=default)=>TransitionAsync(id,version,SubscriptionContractStatus.Active,effectiveDate,"Resumed",token);
	public Task<SubscriptionContract> CancelAsync(long id,long version,DateOnly effectiveDate,CancellationToken token=default)=>TransitionAsync(id,version,SubscriptionContractStatus.Cancelled,effectiveDate,"Cancelled",token);

	public async Task<IReadOnlyList<SubscriptionBillingInstance>> EnsureDueInstancesAsync(DateOnly asOf,CancellationToken token=default){_authorization.RequirePermission(ApplicationPermission.SubscriptionBillingGenerate);RequireUser();var candidates=await _subscriptions.ListDueContractsAsync(asOf,200,token);foreach(var candidate in candidates)await EnsureContractScheduleAsync(candidate.Id,asOf,token);return await _subscriptions.ListDueBillingInstancesAsync(asOf,500,token);}

	public async Task<SubscriptionInvoiceGenerationResult> GenerateInvoiceDraftAsync(long billingInstanceId,CancellationToken token=default)
	{
		_authorization.RequirePermission(ApplicationPermission.SubscriptionBillingGenerate);_authorization.RequirePermission(ApplicationPermission.SalesInvoicesCreate);var user=RequireUser();var instance=await _subscriptions.GetBillingInstanceAsync(billingInstanceId,token)??throw new InvalidOperationException("Billing instance was not found.");if(instance.Status==SubscriptionBillingInstanceStatus.Generated&&instance.SalesInvoiceId is long existingId)return new(instance,await _invoices.GetByIdAsync(existingId,token));
		var contract=await _subscriptions.GetContractAsync(instance.ContractId,token)??throw new InvalidOperationException("Subscription contract was not found.");var lines=await _subscriptions.ListLinesAsync(contract.Id,instance.TermsRevision,token);if(lines.Count==0)throw new InvalidOperationException("Billing instance has no contract terms.");var customer=await _customers.GetByIdAsync(contract.CustomerId,token)??throw new InvalidOperationException("Customer was not found.");if(!customer.IsActive)throw new InvalidOperationException("Inactive customers cannot be billed.");
		var resolved=new List<(SubscriptionContractLine Line,decimal Price,decimal Discount,long? ListId,string? Name,SalesPriceListScope? Scope,string? Currency)>();string? blockReason=null;
		foreach(var line in lines){if(line.PricePolicy==SubscriptionPricePolicy.FixedContractPrice){resolved.Add((line,line.UnitPrice,line.DiscountPercent,line.PriceSourceListId,line.PriceSourceName??"Contract snapshot",line.PriceSourceScope,line.PriceSourceCurrency??contract.Currency));continue;}var price=await _pricing.ResolveAsync(contract.CustomerId,line.ItemId,line.Quantity,instance.BillingDate.ToDateTime(TimeOnly.MinValue),contract.Currency,token);if(price is null){blockReason=$"No active {contract.Currency} sales price is available for {line.PartNumber} on {instance.BillingDate:yyyy-MM-dd}.";break;}resolved.Add((line,price.UnitPrice,price.DiscountPercent,price.PriceListId,price.PriceListName,price.Scope,price.Currency));}
		var outcome=await _transactions.ExecuteAsync(async(tx,ct)=>
		{
			var current=await _subscriptions.GetBillingInstanceAsync(tx,billingInstanceId,ct)??throw new InvalidOperationException("Billing instance was not found.");if(current.Status==SubscriptionBillingInstanceStatus.Generated&&current.SalesInvoiceId is long already)return((long?)already,current);if(await _subscriptions.TryClaimBillingInstanceAsync(tx,current.Id,current.Version,ct)!=1)throw new ConcurrencyConflictException("subscription billing instance");var claimed=current with{Version=current.Version+1,Status=SubscriptionBillingInstanceStatus.Generating,BlockReason=null};
			if(blockReason is not null){if(await _subscriptions.MarkBillingBlockedAsync(tx,claimed.Id,claimed.Version,blockReason,ct)!=1)throw new ConcurrencyConflictException("subscription billing instance");var blocked=claimed with{Version=claimed.Version+1,Status=SubscriptionBillingInstanceStatus.Blocked,BlockReason=blockReason};await _auditEntries.CreateAsync(tx,_audit.CreateActionEntry(blocked.Id,"BillingBlocked",current,blocked),ct);return((long?)null,blocked);}
			var now=DateTime.UtcNow;var invoice=new SalesInvoice{CustomerId=contract.CustomerId,InvoiceDate=instance.BillingDate.ToDateTime(TimeOnly.MinValue),DueDate=instance.BillingDate.AddDays(customer.PaymentTermsDays).ToDateTime(TimeOnly.MinValue),Currency=contract.Currency,CustomerReference=$"{contract.ContractNumber} {instance.PeriodStart:yyyy-MM-dd}/{instance.PeriodEnd:yyyy-MM-dd}",BillingAddress=customer.BillingAddress,Notes=$"Recurring billing contract {contract.ContractNumber}, period {instance.PeriodStart:yyyy-MM-dd} to {instance.PeriodEnd:yyyy-MM-dd}.",Lines=resolved.Select((x,index)=>new SalesInvoiceLine{LineNumber=index+1,PartNumber=x.Line.PartNumber,Description=x.Line.Description,Quantity=x.Line.Quantity,UnitPrice=x.Price,DiscountPercent=x.Discount,TaxRate=x.Line.TaxRate,TaxCategoryCode=x.Line.TaxRate==0m?ElectronicInvoiceTaxCategories.ZeroRated:ElectronicInvoiceTaxCategories.StandardRated}).ToArray()};var draft=await _invoices.CreateDirectDraftAsync(tx,invoice,ct);foreach(var x in resolved)await _subscriptions.InsertPriceEvidenceAsync(tx,new SubscriptionBillingPriceEvidence{BillingInstanceId=claimed.Id,ContractLineId=x.Line.Id,LineNumber=x.Line.LineNumber,UnitPrice=x.Price,DiscountPercent=x.Discount,PriceSourceListId=x.ListId,PriceSourceName=x.Name,PriceSourceScope=x.Scope,PriceSourceCurrency=x.Currency,ResolvedAtUtc=now},ct);if(await _subscriptions.MarkBillingGeneratedAsync(tx,claimed.Id,claimed.Version,draft.Id,user.Id,now,ct)!=1)throw new ConcurrencyConflictException("subscription billing instance");var generated=claimed with{Version=claimed.Version+1,Status=SubscriptionBillingInstanceStatus.Generated,SalesInvoiceId=draft.Id,SalesInvoiceNumber=draft.InvoiceNumber,GeneratedAtUtc=now,GeneratedByUserId=user.Id};await _auditEntries.CreateAsync(tx,_audit.CreateActionEntry(generated.Id,"InvoiceDraftGenerated",current,generated),ct);return((long?)draft.Id,generated);
		},token);
		if(outcome.Item1 is null)throw new InvalidOperationException(outcome.Item2.BlockReason??"Billing is blocked.");var generatedInvoice=await _invoices.GetByIdAsync(outcome.Item1.Value,token)??throw new InvalidOperationException("Generated invoice draft could not be reloaded.");return new(outcome.Item2,generatedInvoice);
	}

	private async Task EnsureContractScheduleAsync(long contractId,DateOnly asOf,CancellationToken token){var user=RequireUser();await _transactions.ExecuteAsync(async(tx,ct)=>{var contract=await _subscriptions.GetContractAsync(tx,contractId,ct)??throw new InvalidOperationException("Subscription contract was not found.");if(contract.Status!=SubscriptionContractStatus.Active)return;var guard=0;while(contract.NextBillingDate<=asOf&&guard++<120){if(contract.EndDate is{} end&&contract.NextBillingDate>end)break;var period=SubscriptionBillingSchedule.Period(contract,contract.NextBillingDate);if(await _subscriptions.FindBillingInstanceAsync(tx,contract.Id,period.PeriodStart,ct)is null)await _subscriptions.CreateBillingInstanceAsync(tx,new SubscriptionBillingInstance{ContractId=contract.Id,TermsRevision=contract.TermsRevision,PeriodStart=period.PeriodStart,PeriodEnd=period.PeriodEnd,BillingDate=contract.NextBillingDate,Status=SubscriptionBillingInstanceStatus.Due,CreatedAtUtc=DateTime.UtcNow},ct);if(await _subscriptions.AdvanceNextBillingDateAsync(tx,contract.Id,contract.Version,contract.NextBillingDate,period.NextBillingDate,user.Id,DateTime.UtcNow,ct)!=1)throw new ConcurrencyConflictException("subscription schedule");contract=contract with{Version=contract.Version+1,NextBillingDate=period.NextBillingDate};}if(guard>=120)throw new InvalidOperationException("Subscription schedule catch-up exceeded the safety limit.");},token);}

	private async Task<SubscriptionContract> TransitionAsync(long id,long version,SubscriptionContractStatus target,DateOnly effectiveDate,string action,CancellationToken token)
	{
		_authorization.RequirePermission(ApplicationPermission.SubscriptionContractsManage);var user=RequireUser();var today=DateOnly.FromDateTime(DateTime.Today);if(effectiveDate>today)throw new InvalidOperationException("Future-dated lifecycle changes are outside the bounded recurring-billing lifecycle; apply the change on its effective date.");
		return await _transactions.ExecuteAsync(async(tx,ct)=>{var before=await _subscriptions.GetContractAsync(tx,id,ct)??throw new InvalidOperationException("Subscription contract was not found.");if(before.Version!=version)throw new ConcurrencyConflictException("subscription contract");if(effectiveDate<before.StartDate)throw new InvalidOperationException("Lifecycle effective date cannot precede the contract start.");var allowed=(before.Status,target) switch{(SubscriptionContractStatus.Draft,SubscriptionContractStatus.Active)=>true,(SubscriptionContractStatus.Active,SubscriptionContractStatus.Paused)=>true,(SubscriptionContractStatus.Paused,SubscriptionContractStatus.Active)=>true,(SubscriptionContractStatus.Draft or SubscriptionContractStatus.Active or SubscriptionContractStatus.Paused,SubscriptionContractStatus.Cancelled)=>true,_=>false};if(!allowed)throw new InvalidOperationException($"Transition from {before.Status} to {target} is not allowed.");var latest=await _subscriptions.GetLatestGeneratedPeriodEndAsync(tx,id,ct);if(latest is{} last&&effectiveDate<=last&&target!=SubscriptionContractStatus.Active)throw new InvalidOperationException("Lifecycle changes cannot retroactively alter an already billed period.");var now=DateTime.UtcNow;if(await _subscriptions.SetLifecycleAsync(tx,id,before.Version,target,effectiveDate,user.Id,now,ct)!=1)throw new ConcurrencyConflictException("subscription contract");var after=before with{Version=before.Version+1,Status=target,StatusEffectiveDate=effectiveDate,UpdatedAtUtc=now,UpdatedByUserId=user.Id};await _subscriptions.InsertLifecycleEventAsync(tx,new SubscriptionLifecycleEvent{ContractId=id,Action=action,EffectiveDate=effectiveDate,PreviousStatus=before.Status,NewStatus=target,CreatedAtUtc=now,CreatedByUserId=user.Id},ct);await _auditEntries.CreateAsync(tx,_audit.CreateActionEntry(id,action,before,after),ct);return after;},token);
	}

	private async Task<SubscriptionContract> NormalizeAsync(SubscriptionContract input,CancellationToken token)
	{
		ArgumentNullException.ThrowIfNull(input);if(input.CustomerId<=0)throw new ArgumentException("A customer is required.",nameof(input));if(input.LegalEntityId==Guid.Empty)throw new ArgumentException("A legal entity is required.",nameof(input));if(input.EndDate is{} end&&end<input.StartDate)throw new ArgumentException("Contract end date cannot precede the start date.",nameof(input));if(!Enum.IsDefined(input.Cadence))throw new ArgumentException("Billing cadence is invalid.",nameof(input));if(input.Lines.Count==0)throw new ArgumentException("At least one recurring line is required.",nameof(input));var customer=await _customers.GetByIdAsync(input.CustomerId,token)??throw new InvalidOperationException("Customer was not found.");if(!customer.IsActive)throw new InvalidOperationException("Inactive customers cannot own new recurring contracts.");var currency=(input.Currency??string.Empty).Trim().ToUpperInvariant();if(currency.Length!=3)throw new ArgumentException("Contract currency must be a three-letter code.",nameof(input));var lines=new List<SubscriptionContractLine>();var lineNumber=1;
		foreach(var line in input.Lines){if(line.ItemId<=0||line.Quantity<=0||line.UnitPrice<0m||line.DiscountPercent is <0m or >100m||line.TaxRate<0m||!Enum.IsDefined(line.PricePolicy))throw new ArgumentException("Recurring line contains invalid commercial terms.",nameof(input));var item=await _items.GetByIdAsync(line.ItemId,token)??throw new InvalidOperationException($"Item {line.ItemId} was not found.");if(!item.IsActive)throw new InvalidOperationException($"Item {item.PartNumber} is inactive.");lines.Add(line with{LineNumber=lineNumber++,PartNumber=string.IsNullOrWhiteSpace(line.PartNumber)?item.PartNumber:line.PartNumber.Trim(),Description=string.IsNullOrWhiteSpace(line.Description)?item.Description:line.Description.Trim(),PriceSourceName=line.PricePolicy==SubscriptionPricePolicy.FixedContractPrice?(string.IsNullOrWhiteSpace(line.PriceSourceName)?"Contract snapshot":line.PriceSourceName):line.PriceSourceName,PriceSourceCurrency=string.IsNullOrWhiteSpace(line.PriceSourceCurrency)?currency:line.PriceSourceCurrency.Trim().ToUpperInvariant()});}
		return input with{Currency=currency,Notes=string.IsNullOrWhiteSpace(input.Notes)?null:input.Notes.Trim(),CustomerName=customer.Name,Lines=lines};
	}
	private static string Snapshot(SubscriptionContract value)=>JsonSerializer.Serialize(new{value.Id,value.ContractNumber,value.CustomerId,value.LegalEntityId,value.Currency,value.StartDate,value.EndDate,value.Cadence,value.TermsRevision,value.Lines},SnapshotJson);
	private User RequireUser()=>_authorization.CurrentUser is{IsActive:true}user?user:throw new UnauthorizedAccessException("An active signed-in user is required for subscription billing.");
}
